# Generated by Django 6.0.3 on 2026-03-08 06:48

import apps.common.util
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('state', models.CharField(max_length=255, unique=True, verbose_name='State')),
                ('nonce', models.CharField(max_length=255, verbose_name='Nonce')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('redirect_to', models.URLField(max_length=255, verbose_name='Redirect To')),
                ('expires', models.DateTimeField(verbose_name='Expires')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SSO Session',
                'verbose_name_plural': 'SSO Sessions',
            },
        ),
        migrations.CreateModel(
            name='SSOAccount',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='Provider User ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SSO Account',
                'verbose_name_plural': 'SSO Accounts',
                'indexes': [models.Index(fields=['user', 'provider'], name='sso_ssoacco_user_id_3bd55b_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='sso_ssoaccount_pr_prus_uniq')],
            },
        ),
    ]
