# Generated by Django 6.0.1 on 2026-01-11 01:21

import pghistory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sync Date')),
                ('count', models.IntegerField(db_index=True, verbose_name='Sync Count')),
                ('duration', models.FloatField(db_index=True, verbose_name='Duration (seconds)')),
            ],
            options={
                'verbose_name': 'Sync Record',
                'verbose_name_plural': 'Sync Records',
            },
        ),
        migrations.CreateModel(
            name='HotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgh_slug', models.TextField(unique=True, verbose_name='Slug')),
                ('pgh_model', models.CharField(db_index=True, max_length=64, verbose_name='Event Model')),
                ('pgh_id', models.BigIntegerField(verbose_name='Event ID')),
                ('pgh_created_at', models.DateTimeField(db_index=True, verbose_name='Created At')),
                ('pgh_label', models.TextField(verbose_name='Label')),
                ('pgh_data', pghistory.utils.JSONField(blank=True, null=True, verbose_name='Data')),
                ('pgh_diff', pghistory.utils.JSONField(blank=True, null=True, verbose_name='Diff')),
                ('pgh_context_id', models.UUIDField(blank=True, null=True, verbose_name='Context ID')),
                ('pgh_context', pghistory.utils.JSONField(blank=True, null=True, verbose_name='Context')),
                ('pgh_obj_model', models.CharField(db_index=True, max_length=64, verbose_name='Data Model')),
                ('pgh_obj_id', models.TextField(blank=True, db_index=True, null=True, verbose_name='Data ID')),
            ],
            options={
                'verbose_name': 'Hot Event',
                'verbose_name_plural': 'Hot Events',
                'indexes': [models.Index(fields=['pgh_obj_model', 'pgh_obj_id', 'pgh_created_at'], name='tracking_ho_pgh_obj_75464c_idx')],
            },
        ),
    ]
