# Generated by Django 6.0.1 on 2026-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrecord',
            name='synced',
            field=models.DateTimeField(db_index=True, verbose_name='Sync Date'),
        ),
    ]
