# Generated by Django 6.0.1 on 2026-01-11 01:22

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
                ('ancestors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), editable=False, verbose_name='Ancestors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetencyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Competency Goal',
                'verbose_name_plural': 'Competency Goals',
            },
        ),
        migrations.CreateModel(
            name='CompetencyGoalEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Number')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Factor',
                'verbose_name_plural': 'Factors',
            },
        ),
        migrations.CreateModel(
            name='FactorEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Level')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Number')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Level')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Validity Days')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Issuer')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('revoked', models.DateTimeField(blank=True, null=True, verbose_name='Revoked')),
                ('revoked_reason', models.TextField(blank=True, default='', verbose_name='Revoked Reason')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.badge', verbose_name='Badge')),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Earner')),
            ],
            options={
                'verbose_name': 'Badge Award',
                'verbose_name_plural': 'Badge Awards',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeAwardEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('revoked', models.DateTimeField(blank=True, null=True, verbose_name='Revoked')),
                ('revoked_reason', models.TextField(blank=True, default='', verbose_name='Revoked Reason')),
                ('badge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.badge', verbose_name='Badge')),
                ('earner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Earner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.badgeaward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField(verbose_name='Claim')),
                ('endorsed', models.DateTimeField(verbose_name='Endorsed')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.badge', verbose_name='Badge')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'BadgeEndorsement',
                'verbose_name_plural': 'Badge Endorsements',
            },
        ),
        migrations.CreateModel(
            name='BadgeEndorsementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('claim', models.TextField(verbose_name='Claim')),
                ('endorsed', models.DateTimeField(verbose_name='Endorsed')),
                ('badge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.badge', verbose_name='Badge')),
                ('partner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Partner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.badgeendorsement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Validity Days')),
                ('issuer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Issuer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.badge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField(verbose_name='Coverage')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.badge', verbose_name='Badge')),
            ],
            options={
                'verbose_name': 'Badge Skill',
                'verbose_name_plural': 'Badge Skills',
            },
        ),
        migrations.CreateModel(
            name='BadgeSkillEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('coverage', models.FloatField(verbose_name='Coverage')),
                ('badge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.badge', verbose_name='Badge')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.badgeskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('background_image', models.ImageField(upload_to='', verbose_name='Background Image')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('template', models.JSONField(verbose_name='Template')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Validity Days')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Issuer')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('pdf', models.FileField(upload_to='', verbose_name='PDF')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('data', models.JSONField(verbose_name='Data')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('revoked', models.DateTimeField(blank=True, null=True, verbose_name='Revoked')),
                ('revoked_reason', models.TextField(blank=True, default='', verbose_name='Revoked Reason')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.certificate', verbose_name='Certificate')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Certificate Award',
                'verbose_name_plural': 'Certificate Awards',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateAwardEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('pdf', models.FileField(upload_to='', verbose_name='PDF')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('data', models.JSONField(verbose_name='Data')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('revoked', models.DateTimeField(blank=True, null=True, verbose_name='Revoked')),
                ('revoked_reason', models.TextField(blank=True, default='', verbose_name='Revoked Reason')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('certificate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.certificate', verbose_name='Certificate')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.certificateaward')),
                ('recipient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('claim', models.TextField(verbose_name='Claim')),
                ('endorsed', models.DateTimeField(verbose_name='Endorsed')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.certificate', verbose_name='Certificate')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Certificate Endorsement',
                'verbose_name_plural': 'Certificate Endorsements',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateEndorsementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('claim', models.TextField(verbose_name='Claim')),
                ('endorsed', models.DateTimeField(verbose_name='Endorsed')),
                ('certificate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.certificate', verbose_name='Certificate')),
                ('partner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Partner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.certificateendorsement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('background_image', models.ImageField(upload_to='', verbose_name='Background Image')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('template', models.JSONField(verbose_name='Template')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Validity Days')),
                ('issuer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Issuer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.certificate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField(verbose_name='Coverage')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.certificate', verbose_name='Certificate')),
            ],
            options={
                'verbose_name': 'Certificate Skill',
                'verbose_name_plural': 'Certificate Skills',
            },
        ),
        migrations.CreateModel(
            name='CertificateSkillEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('coverage', models.FloatField(verbose_name='Coverage')),
                ('certificate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.certificate', verbose_name='Certificate')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.certificateskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('version', models.CharField(max_length=30, verbose_name='Version')),
                ('ancestors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), editable=False, verbose_name='Ancestors')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='competency__name_b4a661_idx'), models.Index(fields=['depth'], name='competency__depth_d95f5a_idx'), models.Index(fields=['path'], name='competency__path_1f40f1_idx')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."ancestors", NEW."code", NEW."depth", NEW."id", NEW."name", NEW."numchild", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."version"); RETURN NULL;', hash='48465fb83f87d65d6270d892f98f55b8776eee9d', operation='INSERT', pgid='pgtrigger_insert_insert_1d9f9', table='competency_classification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."ancestors", NEW."code", NEW."depth", NEW."id", NEW."name", NEW."numchild", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."version"); RETURN NULL;', hash='1dcfa70876c809ccc156f13f655a3b623f5e8a95', operation='UPDATE', pgid='pgtrigger_update_update_82c9b', table='competency_classification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (OLD."ancestors", OLD."code", OLD."depth", OLD."id", OLD."name", OLD."numchild", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."version"); RETURN NULL;', hash='3626b626548d46d9aa83719c97766644c7095eff', operation='DELETE', pgid='pgtrigger_delete_delete_9aed0', table='competency_classification', when='AFTER')),
        ),
        migrations.AddField(
            model_name='classificationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='classificationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.classification'),
        ),
        migrations.AddField(
            model_name='competencygoal',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.classification', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='competencygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='competencygoalevent',
            name='classification',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.classification', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='competencygoalevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='competencygoalevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.competencygoal'),
        ),
        migrations.AddField(
            model_name='competencygoalevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='competencygoal',
            name='factors',
            field=models.ManyToManyField(to='competency.factor', verbose_name='Factors'),
        ),
        migrations.AddField(
            model_name='certificateskill',
            name='factors',
            field=models.ManyToManyField(to='competency.factor', verbose_name='Factors'),
        ),
        migrations.AddField(
            model_name='badgeskill',
            name='factors',
            field=models.ManyToManyField(to='competency.factor', verbose_name='Factors'),
        ),
        migrations.AddField(
            model_name='factorevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='factorevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.factor'),
        ),
        migrations.AddField(
            model_name='skill',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.classification', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='factorevent',
            name='skill',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='factor',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='certificateskillevent',
            name='skill',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='certificateskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='badgeskillevent',
            name='skill',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='badgeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='badge',
            name='skills',
            field=models.ManyToManyField(through='competency.BadgeSkill', to='competency.skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='skillevent',
            name='classification',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.classification', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='skillevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='skillevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='competency.skill'),
        ),
        migrations.AddConstraint(
            model_name='badgeaward',
            constraint=models.UniqueConstraint(fields=('badge', 'earner'), name='competency_badgeaward_ba_ea_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeaward',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeawardevent" ("badge_id", "created", "earner_id", "expires", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "revoked", "revoked_reason") VALUES (NEW."badge_id", NEW."created", NEW."earner_id", NEW."expires", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."revoked", NEW."revoked_reason"); RETURN NULL;', hash='40fb977783ae488034b3fbde2840f69acb72090e', operation='INSERT', pgid='pgtrigger_insert_insert_9add6', table='competency_badgeaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeaward',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."badge_id" IS DISTINCT FROM (NEW."badge_id") OR OLD."earner_id" IS DISTINCT FROM (NEW."earner_id") OR OLD."expires" IS DISTINCT FROM (NEW."expires") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."revoked" IS DISTINCT FROM (NEW."revoked") OR OLD."revoked_reason" IS DISTINCT FROM (NEW."revoked_reason"))', func='INSERT INTO "competency_badgeawardevent" ("badge_id", "created", "earner_id", "expires", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "revoked", "revoked_reason") VALUES (NEW."badge_id", NEW."created", NEW."earner_id", NEW."expires", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."revoked", NEW."revoked_reason"); RETURN NULL;', hash='558341d7bf5c7f518f09c1ce8e4378577b1d154a', operation='UPDATE', pgid='pgtrigger_update_update_b64af', table='competency_badgeaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeaward',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeawardevent" ("badge_id", "created", "earner_id", "expires", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "revoked", "revoked_reason") VALUES (OLD."badge_id", OLD."created", OLD."earner_id", OLD."expires", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."revoked", OLD."revoked_reason"); RETURN NULL;', hash='2785e3910876ae7ad5117fe828be7531df7b782a', operation='DELETE', pgid='pgtrigger_delete_delete_85f59', table='competency_badgeaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeawardevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dea6e87adb433e033d32887c6d0eada2027c87fc', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3d656', table='competency_badgeawardevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='badgeendorsement',
            constraint=models.UniqueConstraint(fields=('badge', 'partner'), name='competency_badgeendorsement_ba_or_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeendorsement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeendorsementevent" ("badge_id", "claim", "endorsed", "id", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."badge_id", NEW."claim", NEW."endorsed", NEW."id", NEW."partner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d95e530cf0bda71b07b3376c5fb9feecabdc5bbd', operation='INSERT', pgid='pgtrigger_insert_insert_7d7ae', table='competency_badgeendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeendorsement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_badgeendorsementevent" ("badge_id", "claim", "endorsed", "id", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."badge_id", NEW."claim", NEW."endorsed", NEW."id", NEW."partner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='db8b676f6e1cabf1a56cbef5dc491f84f073253b', operation='UPDATE', pgid='pgtrigger_update_update_49fa8', table='competency_badgeendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeendorsement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeendorsementevent" ("badge_id", "claim", "endorsed", "id", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."badge_id", OLD."claim", OLD."endorsed", OLD."id", OLD."partner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='580adb0c88142f1c996b91b1dfecb78354cc40d1', operation='DELETE', pgid='pgtrigger_delete_delete_92948', table='competency_badgeendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeendorsementevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dd20f5497507278b8cc852ef14d4abfef8debdab', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ce079', table='competency_badgeendorsementevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='fba9b6606d00465f74e4417e5493bb5407c071d5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_bb8f2', table='competency_badgeevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['active'], name='competency__active_834e08_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificate',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateevent" ("active", "background_image", "created", "description", "id", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "template", "thumbnail", "validity_days") VALUES (NEW."active", NEW."background_image", NEW."created", NEW."description", NEW."id", NEW."issuer_id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."template", NEW."thumbnail", NEW."validity_days"); RETURN NULL;', hash='581c0ecd36df98db249f1a27271daf6790c2d580', operation='INSERT', pgid='pgtrigger_insert_insert_3d649', table='competency_certificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."background_image" IS DISTINCT FROM (NEW."background_image") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."issuer_id" IS DISTINCT FROM (NEW."issuer_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."template" IS DISTINCT FROM (NEW."template") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."validity_days" IS DISTINCT FROM (NEW."validity_days"))', func='INSERT INTO "competency_certificateevent" ("active", "background_image", "created", "description", "id", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "template", "thumbnail", "validity_days") VALUES (NEW."active", NEW."background_image", NEW."created", NEW."description", NEW."id", NEW."issuer_id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."template", NEW."thumbnail", NEW."validity_days"); RETURN NULL;', hash='3634d2709d77ba3a991fb579e81604b953d9541b', operation='UPDATE', pgid='pgtrigger_update_update_ad9c4', table='competency_certificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificate',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateevent" ("active", "background_image", "created", "description", "id", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "template", "thumbnail", "validity_days") VALUES (OLD."active", OLD."background_image", OLD."created", OLD."description", OLD."id", OLD."issuer_id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."template", OLD."thumbnail", OLD."validity_days"); RETURN NULL;', hash='88ee87c1eba68e332d0edb43b772076084eddbe4', operation='DELETE', pgid='pgtrigger_delete_delete_f937e', table='competency_certificate', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='certificateaward',
            constraint=models.UniqueConstraint(fields=('certificate', 'recipient', 'context'), name='competency_certificateaward_ce_re_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "context", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (NEW."certificate_id", NEW."context", NEW."created", NEW."data", NEW."expires", NEW."id", NEW."modified", NEW."pdf", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recipient_id", NEW."revoked", NEW."revoked_reason", NEW."thumbnail"); RETURN NULL;', hash='2149b56eff8fba3a6778a52f221600fde0997072', operation='INSERT', pgid='pgtrigger_insert_insert_f87a0', table='competency_certificateaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."certificate_id" IS DISTINCT FROM (NEW."certificate_id") OR OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."data" IS DISTINCT FROM (NEW."data") OR OLD."expires" IS DISTINCT FROM (NEW."expires") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."pdf" IS DISTINCT FROM (NEW."pdf") OR OLD."recipient_id" IS DISTINCT FROM (NEW."recipient_id") OR OLD."revoked" IS DISTINCT FROM (NEW."revoked") OR OLD."revoked_reason" IS DISTINCT FROM (NEW."revoked_reason") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail"))', func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "context", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (NEW."certificate_id", NEW."context", NEW."created", NEW."data", NEW."expires", NEW."id", NEW."modified", NEW."pdf", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recipient_id", NEW."revoked", NEW."revoked_reason", NEW."thumbnail"); RETURN NULL;', hash='e2db878a9ccd5167dcc2189c089f0caabeaa9188', operation='UPDATE', pgid='pgtrigger_update_update_f028f', table='competency_certificateaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "context", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (OLD."certificate_id", OLD."context", OLD."created", OLD."data", OLD."expires", OLD."id", OLD."modified", OLD."pdf", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recipient_id", OLD."revoked", OLD."revoked_reason", OLD."thumbnail"); RETURN NULL;', hash='66a2f6b43348cbec138b1f5bef6e6605963eccc1', operation='DELETE', pgid='pgtrigger_delete_delete_79dc4', table='competency_certificateaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateawardevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6313c66e3768e6592af09802ccd5b8a8addb376a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0a66e', table='competency_certificateawardevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='certificateendorsement',
            constraint=models.UniqueConstraint(fields=('certificate', 'partner'), name='competency_certificateendorsement_ce_or_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateendorsement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateendorsementevent" ("certificate_id", "claim", "created", "endorsed", "id", "modified", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."certificate_id", NEW."claim", NEW."created", NEW."endorsed", NEW."id", NEW."modified", NEW."partner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='ebe2fcf8994ceb0d4e8fb5fe0ec0e09c25f45a46', operation='INSERT', pgid='pgtrigger_insert_insert_20938', table='competency_certificateendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateendorsement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."certificate_id" IS DISTINCT FROM (NEW."certificate_id") OR OLD."claim" IS DISTINCT FROM (NEW."claim") OR OLD."endorsed" IS DISTINCT FROM (NEW."endorsed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."partner_id" IS DISTINCT FROM (NEW."partner_id"))', func='INSERT INTO "competency_certificateendorsementevent" ("certificate_id", "claim", "created", "endorsed", "id", "modified", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."certificate_id", NEW."claim", NEW."created", NEW."endorsed", NEW."id", NEW."modified", NEW."partner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='f3a083ee1f92280df51ff5ffc26f1cf45d7d2882', operation='UPDATE', pgid='pgtrigger_update_update_6085a', table='competency_certificateendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateendorsement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateendorsementevent" ("certificate_id", "claim", "created", "endorsed", "id", "modified", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."certificate_id", OLD."claim", OLD."created", OLD."endorsed", OLD."id", OLD."modified", OLD."partner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='1aaf2a71f37e0176fca7e8aa4fa4e74014c628b0', operation='DELETE', pgid='pgtrigger_delete_delete_ba79a', table='competency_certificateendorsement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateendorsementevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='3a25e76a01bfaf7628f245cdd732506f18f48b3d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_eb23f', table='competency_certificateendorsementevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bc25d71c12e5acdd3a90c268b78c454fc54d4919', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4ebbe', table='competency_certificateevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classificationevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7e88b7ca114db69a156216474bf679f83358c35b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b9e4b', table='competency_classificationevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoalevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5978be77717c3b985aa3baef3bf36ea9c3e90f14', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b61a0', table='competency_competencygoalevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='competencygoal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='competency_competencygoal_us_na_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."classification_id", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='eaeb0e5c1315bc63a7009f34c5a590e07aa733f1', operation='INSERT', pgid='pgtrigger_insert_insert_adb65', table='competency_competencygoal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."classification_id" IS DISTINCT FROM (NEW."classification_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."ordering" IS DISTINCT FROM (NEW."ordering") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."classification_id", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='442bdb0416a673119e941580a0fa9e1f638c1d59', operation='UPDATE', pgid='pgtrigger_update_update_460f5', table='competency_competencygoal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."classification_id", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='09ccc64c39b48bdf78015bcac3c37f4eda18fecf', operation='DELETE', pgid='pgtrigger_delete_delete_194db', table='competency_competencygoal', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['classification', 'level'], name='competency__classif_227e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='competency__code_387b24_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='competency__name_a2189b_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."classification_id", NEW."code", NEW."id", NEW."level", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."version"); RETURN NULL;', hash='17bf50b90134fe5c7a5a9d57ecee7e21ce4feb25', operation='INSERT', pgid='pgtrigger_insert_insert_b6d72', table='competency_skill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."classification_id", NEW."code", NEW."id", NEW."level", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."version"); RETURN NULL;', hash='640edd0dd67b6e917c6f415eb4b9797849d73442', operation='UPDATE', pgid='pgtrigger_update_update_238df', table='competency_skill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (OLD."classification_id", OLD."code", OLD."id", OLD."level", OLD."name", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."version"); RETURN NULL;', hash='9357020c070c509fc6a2967e26ac80974ca38ef1', operation='DELETE', pgid='pgtrigger_delete_delete_320f3', table='competency_skill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factorevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9aee2220fe55f6a2e841f9e8fbc34db3216be630', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4b439', table='competency_factorevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['code'], name='competency__code_077e33_idx'),
        ),
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['name'], name='competency__name_7ba31c_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id", "version") VALUES (NEW."code", NEW."id", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."skill_id", NEW."version"); RETURN NULL;', hash='6faa0a9f24485a9d41c8f73770e917fbd7d4c86c', operation='INSERT', pgid='pgtrigger_insert_insert_c6de9', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id", "version") VALUES (NEW."code", NEW."id", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."skill_id", NEW."version"); RETURN NULL;', hash='9d498a3ee48433f60990825763ca456e6092a3d3', operation='UPDATE', pgid='pgtrigger_update_update_a74af', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id", "version") VALUES (OLD."code", OLD."id", OLD."name", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."skill_id", OLD."version"); RETURN NULL;', hash='3370d4c28cfc60477ee890c19c15a28c485baa92', operation='DELETE', pgid='pgtrigger_delete_delete_f12cc', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateskillevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9ea55ad08701020eb5e30f791d1c40b25f331476', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_798df', table='competency_certificateskillevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='certificateskill',
            constraint=models.UniqueConstraint(fields=('certificate', 'skill'), name='competency_certificateskill_co_sk_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateskill',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateskillevent" ("certificate_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."certificate_id", NEW."coverage", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='a3c9efe36759382f7186f513eb4bd96eecd82224', operation='INSERT', pgid='pgtrigger_insert_insert_8ac44', table='competency_certificateskill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateskill',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_certificateskillevent" ("certificate_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."certificate_id", NEW."coverage", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='a572751e2e9bf2984a14cedc13e47779cbd2a7e4', operation='UPDATE', pgid='pgtrigger_update_update_bcd64', table='competency_certificateskill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateskill',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateskillevent" ("certificate_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (OLD."certificate_id", OLD."coverage", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."skill_id"); RETURN NULL;', hash='a6377f012a6e1eb858489621a0e84b1a661ef450', operation='DELETE', pgid='pgtrigger_delete_delete_8e79c', table='competency_certificateskill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeskillevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4188133e9c916b2e3711f8e8d978a08144b16420', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_542c6', table='competency_badgeskillevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='badgeskill',
            constraint=models.UniqueConstraint(fields=('badge', 'skill'), name='competency_badgeskill_ba_sk_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeskill',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeskillevent" ("badge_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."badge_id", NEW."coverage", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='5e9b1596ceb5317b15b5d68836ef4cb71f462a02', operation='INSERT', pgid='pgtrigger_insert_insert_77604', table='competency_badgeskill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeskill',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_badgeskillevent" ("badge_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."badge_id", NEW."coverage", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='f48cf0f61b0103355c6357f7b396b392bc2dee35', operation='UPDATE', pgid='pgtrigger_update_update_d6370', table='competency_badgeskill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badgeskill',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeskillevent" ("badge_id", "coverage", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (OLD."badge_id", OLD."coverage", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."skill_id"); RETURN NULL;', hash='661738db3b435824eb696d6a4e25452d385ca329', operation='DELETE', pgid='pgtrigger_delete_delete_04fba', table='competency_badgeskill', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['active'], name='competency__active_5ccbcd_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badge',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeevent" ("active", "created", "description", "id", "image", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "validity_days") VALUES (NEW."active", NEW."created", NEW."description", NEW."id", NEW."image", NEW."issuer_id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."validity_days"); RETURN NULL;', hash='f01916f53cd38683cb42ced8e5c32858283ab969', operation='INSERT', pgid='pgtrigger_insert_insert_5e512', table='competency_badge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badge',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."issuer_id" IS DISTINCT FROM (NEW."issuer_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."validity_days" IS DISTINCT FROM (NEW."validity_days"))', func='INSERT INTO "competency_badgeevent" ("active", "created", "description", "id", "image", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "validity_days") VALUES (NEW."active", NEW."created", NEW."description", NEW."id", NEW."image", NEW."issuer_id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."validity_days"); RETURN NULL;', hash='048681d7c314d4861d2ce17d70c88cf19dc66423', operation='UPDATE', pgid='pgtrigger_update_update_2eb31', table='competency_badge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='badge',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_badgeevent" ("active", "created", "description", "id", "image", "issuer_id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "validity_days") VALUES (OLD."active", OLD."created", OLD."description", OLD."id", OLD."image", OLD."issuer_id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."validity_days"); RETURN NULL;', hash='f9b11fb690e57f1d7434f3cc143c75ff5ee6716a', operation='DELETE', pgid='pgtrigger_delete_delete_8c9a8', table='competency_badge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skillevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='db8281c0950e347419a9fd491e54c4428c9e36e9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_aae50', table='competency_skillevent', when='BEFORE')),
        ),
    ]
