# Generated by Django 6.0.1 on 2026-01-11 17:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='competencygoal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='competencygoal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='competencygoal',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='competencygoal',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='competencygoalevent',
            name='ordering',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."classification_id", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='c509c6139162d8d8a99ba06292c4d344ac7751dc', operation='INSERT', pgid='pgtrigger_insert_insert_adb65', table='competency_competencygoal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."classification_id" IS DISTINCT FROM (NEW."classification_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."classification_id", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='550fde7f7f23c9c02ab635e70befacf1f9315fab', operation='UPDATE', pgid='pgtrigger_update_update_460f5', table='competency_competencygoal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competencygoal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_competencygoalevent" ("classification_id", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."classification_id", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='6f2d6ee47dd43562c3031def6470dd55ad0dc116', operation='DELETE', pgid='pgtrigger_delete_delete_194db', table='competency_competencygoal', when='AFTER')),
        ),
    ]
