# Generated by Django 6.0.1 on 2026-01-13 07:37

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_remove_competencygoal_insert_insert_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='certificateaward',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='certificateaward',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='certificateaward',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='certificateaward',
            name='competency_certificateaward_ce_re_co_ke_uniq',
        ),
        migrations.RemoveField(
            model_name='certificateawardevent',
            name='context',
        ),
        migrations.AddField(
            model_name='certificateaward',
            name='content_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Content ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateaward',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateawardevent',
            name='content_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Content ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateawardevent',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content Type'),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "content_id", "content_type_id", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (NEW."certificate_id", NEW."content_id", NEW."content_type_id", NEW."created", NEW."data", NEW."expires", NEW."id", NEW."modified", NEW."pdf", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recipient_id", NEW."revoked", NEW."revoked_reason", NEW."thumbnail"); RETURN NULL;', hash='c45d081e2228446fb3dc6896a52516287797dbb9', operation='INSERT', pgid='pgtrigger_insert_insert_f87a0', table='competency_certificateaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."certificate_id" IS DISTINCT FROM (NEW."certificate_id") OR OLD."content_id" IS DISTINCT FROM (NEW."content_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."data" IS DISTINCT FROM (NEW."data") OR OLD."expires" IS DISTINCT FROM (NEW."expires") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."pdf" IS DISTINCT FROM (NEW."pdf") OR OLD."recipient_id" IS DISTINCT FROM (NEW."recipient_id") OR OLD."revoked" IS DISTINCT FROM (NEW."revoked") OR OLD."revoked_reason" IS DISTINCT FROM (NEW."revoked_reason") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail"))', func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "content_id", "content_type_id", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (NEW."certificate_id", NEW."content_id", NEW."content_type_id", NEW."created", NEW."data", NEW."expires", NEW."id", NEW."modified", NEW."pdf", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recipient_id", NEW."revoked", NEW."revoked_reason", NEW."thumbnail"); RETURN NULL;', hash='1e3b8fec689ee34087a9d2beb4f778f98c8a1666', operation='UPDATE', pgid='pgtrigger_update_update_f028f', table='competency_certificateaward', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificateaward',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_certificateawardevent" ("certificate_id", "content_id", "content_type_id", "created", "data", "expires", "id", "modified", "pdf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recipient_id", "revoked", "revoked_reason", "thumbnail") VALUES (OLD."certificate_id", OLD."content_id", OLD."content_type_id", OLD."created", OLD."data", OLD."expires", OLD."id", OLD."modified", OLD."pdf", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recipient_id", OLD."revoked", OLD."revoked_reason", OLD."thumbnail"); RETURN NULL;', hash='8bc3abec896c3f0ac2b9717d5732b3e40c047bca', operation='DELETE', pgid='pgtrigger_delete_delete_79dc4', table='competency_certificateaward', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='certificateaward',
            constraint=models.UniqueConstraint(fields=('certificate', 'recipient', 'content_type', 'content_id'), name='competency_certificateaward_ce_re_coty_coid_uniq'),
        ),
        migrations.RemoveField(
            model_name='certificateaward',
            name='context',
        ),
    ]
