# Generated by Django 6.0.1 on 2026-01-22 09:25

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_remove_certificateaward_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='classification',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='classification',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='classification',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='factor',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='factor',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='factor',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='skill',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='skill',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='skill',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='version',
        ),
        migrations.RemoveField(
            model_name='classificationevent',
            name='version',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='version',
        ),
        migrations.RemoveField(
            model_name='factorevent',
            name='version',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='version',
        ),
        migrations.RemoveField(
            model_name='skillevent',
            name='version',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."ancestors", NEW."code", NEW."depth", NEW."id", NEW."name", NEW."numchild", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='8b6be588eaaf243351a0f4373472bebb4da0336f', operation='INSERT', pgid='pgtrigger_insert_insert_1d9f9', table='competency_classification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."ancestors", NEW."code", NEW."depth", NEW."id", NEW."name", NEW."numchild", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='f4f366d340167c27b69a3b7ed0309c00b2b3c462', operation='UPDATE', pgid='pgtrigger_update_update_82c9b', table='competency_classification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='classification',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_classificationevent" ("ancestors", "code", "depth", "id", "name", "numchild", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."ancestors", OLD."code", OLD."depth", OLD."id", OLD."name", OLD."numchild", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='d62eb73d62d8c7db6215718bdc86fdf7d686c97f', operation='DELETE', pgid='pgtrigger_delete_delete_9aed0', table='competency_classification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."code", NEW."id", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='f428c0358e4c9cfbec76b6259a6b29243afffb7b', operation='INSERT', pgid='pgtrigger_insert_insert_c6de9', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (NEW."code", NEW."id", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."skill_id"); RETURN NULL;', hash='fc5783332f934936cc7e28b474fc665a6a8ad6c5', operation='UPDATE', pgid='pgtrigger_update_update_a74af', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='factor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_factorevent" ("code", "id", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "skill_id") VALUES (OLD."code", OLD."id", OLD."name", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."skill_id"); RETURN NULL;', hash='e2cc4810c98b74861682e41f620d89013d9dbdc1', operation='DELETE', pgid='pgtrigger_delete_delete_f12cc', table='competency_factor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."classification_id", NEW."code", NEW."id", NEW."level", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d4a826c69beda281821473dee6a49c3a612ed6be', operation='INSERT', pgid='pgtrigger_insert_insert_b6d72', table='competency_skill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."classification_id", NEW."code", NEW."id", NEW."level", NEW."name", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='6d8ee22a37a211e9ce4841d2df4bce6aedbf76da', operation='UPDATE', pgid='pgtrigger_update_update_238df', table='competency_skill', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='skill',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "competency_skillevent" ("classification_id", "code", "id", "level", "name", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."classification_id", OLD."code", OLD."id", OLD."level", OLD."name", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='75d56ab6aca8443f63ba10223e30b3ce0ae9654b', operation='DELETE', pgid='pgtrigger_delete_delete_320f3', table='competency_skill', when='AFTER')),
        ),
    ]
