# Generated by Django 6.0.1 on 2026-01-11 01:22

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available From')),
                ('available_until', models.DateTimeField(verbose_name='Available Until')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available From')),
                ('available_until', models.DateTimeField(verbose_name='Available Until')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('archive', models.DateTimeField(verbose_name='Archive')),
                ('enrolled', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('archive', models.DateTimeField(verbose_name='Archive')),
                ('enrolled', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'User Catalog',
                'verbose_name_plural': 'User Catalogs',
            },
        ),
        migrations.CreateModel(
            name='UserCatalogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public") VALUES (NEW."active", NEW."available_from", NEW."available_until", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."public"); RETURN NULL;', hash='d7038a73efaf570feb198f119adb36b53eb2d9dd', operation='INSERT', pgid='pgtrigger_insert_insert_57f47', table='learning_catalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."available_from" IS DISTINCT FROM (NEW."available_from") OR OLD."available_until" IS DISTINCT FROM (NEW."available_until") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."public" IS DISTINCT FROM (NEW."public"))', func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public") VALUES (NEW."active", NEW."available_from", NEW."available_until", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."public"); RETURN NULL;', hash='dd4e0882eb847ecd62bdddb1d31547f57f1ea0b7', operation='UPDATE', pgid='pgtrigger_update_update_4c528', table='learning_catalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public") VALUES (OLD."active", OLD."available_from", OLD."available_until", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."public"); RETURN NULL;', hash='c4db56b290494f18f9573e77511c72000a2365ff', operation='DELETE', pgid='pgtrigger_delete_delete_2a67e', table='learning_catalog', when='AFTER')),
        ),
        migrations.AddField(
            model_name='catalogevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='catalogevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='learning.catalog'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.catalog', verbose_name='Catalog'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'survey']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'survey']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled By'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='enrollmentevent',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'survey']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='enrollmentevent',
            name='enrolled_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled By'),
        ),
        migrations.AddField(
            model_name='enrollmentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='enrollmentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='learning.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='usercatalog',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.catalog', verbose_name='Catalog'),
        ),
        migrations.AddField(
            model_name='usercatalog',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By'),
        ),
        migrations.AddField(
            model_name='usercatalog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='usercatalogevent',
            name='catalog',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='learning.catalog', verbose_name='Catalog'),
        ),
        migrations.AddField(
            model_name='usercatalogevent',
            name='granted_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By'),
        ),
        migrations.AddField(
            model_name='usercatalogevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='usercatalogevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='learning.usercatalog'),
        ),
        migrations.AddField(
            model_name='usercatalogevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalogevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='df5211bcc4fb50512eef166e71df7d1562ba194a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_62e6f', table='learning_catalogevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('catalog', 'content_type', 'content_id'), name='learning_catalogitem_ca_itty_itid_uniq'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'content_id', 'active'], name='learning_en_user_id_2251b5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled'], name='learning_en_enrolle_cdc8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['content_id'], name='learning_en_content_c35540_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'content_type', 'content_id'), name='enrollment_enrollment_us_itty_itid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='enrollment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_enrollmentevent" ("active", "archive", "content_id", "content_type_id", "created", "end", "enrolled", "enrolled_by_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start", "user_id") VALUES (NEW."active", NEW."archive", NEW."content_id", NEW."content_type_id", NEW."created", NEW."end", NEW."enrolled", NEW."enrolled_by_id", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start", NEW."user_id"); RETURN NULL;', hash='95d59a334054581ce0140a57c087887fc269aba0', operation='INSERT', pgid='pgtrigger_insert_insert_98af1', table='learning_enrollment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='enrollment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."archive" IS DISTINCT FROM (NEW."archive") OR OLD."content_id" IS DISTINCT FROM (NEW."content_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."end" IS DISTINCT FROM (NEW."end") OR OLD."enrolled_by_id" IS DISTINCT FROM (NEW."enrolled_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "learning_enrollmentevent" ("active", "archive", "content_id", "content_type_id", "created", "end", "enrolled", "enrolled_by_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start", "user_id") VALUES (NEW."active", NEW."archive", NEW."content_id", NEW."content_type_id", NEW."created", NEW."end", NEW."enrolled", NEW."enrolled_by_id", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start", NEW."user_id"); RETURN NULL;', hash='031ec7c35edcb95c2745966c9bb92a26ea1fe744', operation='UPDATE', pgid='pgtrigger_update_update_583fe', table='learning_enrollment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='enrollment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_enrollmentevent" ("active", "archive", "content_id", "content_type_id", "created", "end", "enrolled", "enrolled_by_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start", "user_id") VALUES (OLD."active", OLD."archive", OLD."content_id", OLD."content_type_id", OLD."created", OLD."end", OLD."enrolled", OLD."enrolled_by_id", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start", OLD."user_id"); RETURN NULL;', hash='b2766960ae947ff990403818d9b6b381c847dbb5', operation='DELETE', pgid='pgtrigger_delete_delete_48277', table='learning_enrollment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='enrollment',
            trigger=pgtrigger.compiler.Trigger(name='learning_enrollment_content_exists', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                table_name text;\n                exists_check boolean;\n            BEGIN\n                SELECT app_label || '_' || model INTO table_name\n                FROM django_content_type\n                WHERE id = NEW.content_type_id;\n\n                EXECUTE format('SELECT EXISTS(SELECT 1 FROM %I WHERE id = $1)', table_name)\n                INTO exists_check USING NEW.content_id;\n\n                IF NOT exists_check THEN\n                    RAISE EXCEPTION 'Content % does not exist in %', NEW.content_id, table_name;\n                END IF;\n\n                RETURN NEW;\n            END;\n        ", hash='b7ae7e46a9abe3aa7f3034f3151abc75c97c848f', operation='INSERT OR UPDATE', pgid='pgtrigger_learning_enrollment_content_exists_91444', table='learning_enrollment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='enrollmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='98d43b7155ce652960b65b47732b9cb19cacebf9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_cc08e', table='learning_enrollmentevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='usercatalog',
            constraint=models.UniqueConstraint(fields=('user', 'catalog'), name='learning_usercatalog_us_ca_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usercatalog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_usercatalogevent" ("catalog_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."catalog_id", NEW."created", NEW."granted_by_id", NEW."id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='05a7b8b4566fceda80cc09f818d6461278c0fac1', operation='INSERT', pgid='pgtrigger_insert_insert_8e6ec', table='learning_usercatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usercatalog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."catalog_id" IS DISTINCT FROM (NEW."catalog_id") OR OLD."granted_by_id" IS DISTINCT FROM (NEW."granted_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "learning_usercatalogevent" ("catalog_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."catalog_id", NEW."created", NEW."granted_by_id", NEW."id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='3fe7714cc91d2de1b0950150a18666b95fb1da02', operation='UPDATE', pgid='pgtrigger_update_update_e7d8a', table='learning_usercatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usercatalog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_usercatalogevent" ("catalog_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."catalog_id", OLD."created", OLD."granted_by_id", OLD."id", OLD."modified", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='a4dda30dee01d280659dd6c0d4a008cb8e1ee6cf', operation='DELETE', pgid='pgtrigger_delete_delete_3049b', table='learning_usercatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usercatalogevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d39fe2c4adf0fa94c112c16726a84cb182c373e4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b0b60', table='learning_usercatalogevent', when='BEFORE')),
        ),
    ]
