# Generated by Django 6.0.1 on 2026-01-16 12:30

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('partner', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.catalog', verbose_name='Catalog')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.cohort', verbose_name='Cohort')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
            ],
            options={
                'verbose_name': 'Cohort Catalog',
                'verbose_name_plural': 'Cohort Catalogs',
            },
        ),
        migrations.CreateModel(
            name='CohortCatalogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('catalog', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='learning.catalog', verbose_name='Catalog')),
                ('cohort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.cohort', verbose_name='Cohort')),
                ('granted_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='learning.cohortcatalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cohortcatalog',
            constraint=models.UniqueConstraint(fields=('cohort', 'catalog'), name='learning_cohortcatalog_co_ca_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortcatalog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_cohortcatalogevent" ("catalog_id", "cohort_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."catalog_id", NEW."cohort_id", NEW."created", NEW."granted_by_id", NEW."id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='15c645c6e9608d3c7fee3030a5c1b70f16c1d84a', operation='INSERT', pgid='pgtrigger_insert_insert_3dcff', table='learning_cohortcatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortcatalog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."catalog_id" IS DISTINCT FROM (NEW."catalog_id") OR OLD."cohort_id" IS DISTINCT FROM (NEW."cohort_id") OR OLD."granted_by_id" IS DISTINCT FROM (NEW."granted_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."note" IS DISTINCT FROM (NEW."note"))', func='INSERT INTO "learning_cohortcatalogevent" ("catalog_id", "cohort_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."catalog_id", NEW."cohort_id", NEW."created", NEW."granted_by_id", NEW."id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='da33db8af222fe535c04ac5ef071bbc2a14d119b', operation='UPDATE', pgid='pgtrigger_update_update_fed30', table='learning_cohortcatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortcatalog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_cohortcatalogevent" ("catalog_id", "cohort_id", "created", "granted_by_id", "id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."catalog_id", OLD."cohort_id", OLD."created", OLD."granted_by_id", OLD."id", OLD."modified", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='ff3bb631f2f6946cfed2cb72e7bd68c81b40d35e', operation='DELETE', pgid='pgtrigger_delete_delete_f0481', table='learning_cohortcatalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortcatalogevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='908d4c73cbe015da57c248210d6cfed537a6deba', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ec743', table='learning_cohortcatalogevent', when='BEFORE')),
        ),
    ]
