# Generated by Django 6.0.1 on 2026-01-16 13:18

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_cohortcatalog_cohortcatalogevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='catalogitem',
            trigger=pgtrigger.compiler.Trigger(name='learning_catalogitem_content_exists', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                table_name text;\n                exists_check boolean;\n            BEGIN\n                SELECT app_label || '_' || model INTO table_name\n                FROM django_content_type\n                WHERE id = NEW.content_type_id;\n\n                EXECUTE format('SELECT EXISTS(SELECT 1 FROM %I WHERE id = $1)', table_name)\n                INTO exists_check USING NEW.content_id;\n\n                IF NOT exists_check THEN\n                    RAISE EXCEPTION 'Content % does not exist in %', NEW.content_id, table_name;\n                END IF;\n\n                RETURN NEW;\n            END;\n        ", hash='c43109396c8d3be33398dfbaa89cab01c138e1be', operation='INSERT OR UPDATE', pgid='pgtrigger_learning_catalogitem_content_exists_3f2f3', table='learning_catalogitem', when='BEFORE')),
        ),
    ]
