# Generated by Django 6.0.1 on 2026-01-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('learning', '0003_catalogitem_learning_catalogitem_content_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'quiz', 'survey']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'quiz', 'survey']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='enrollmentevent',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ['course', 'media', 'exam', 'assignment', 'discussion', 'quiz', 'survey']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
    ]
