# Generated by Django 6.0.1 on 2026-01-23 13:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_catalogitem_content_type_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='catalog',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='catalog',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='catalog',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='catalog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='catalogevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public", "thumbnail") VALUES (NEW."active", NEW."available_from", NEW."available_until", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."public", NEW."thumbnail"); RETURN NULL;', hash='9bfb714f3db0864d6549b91f115e13d5afedcb6c', operation='INSERT', pgid='pgtrigger_insert_insert_57f47', table='learning_catalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."available_from" IS DISTINCT FROM (NEW."available_from") OR OLD."available_until" IS DISTINCT FROM (NEW."available_until") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."public" IS DISTINCT FROM (NEW."public") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail"))', func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public", "thumbnail") VALUES (NEW."active", NEW."available_from", NEW."available_until", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."public", NEW."thumbnail"); RETURN NULL;', hash='4c6894e2aa64bc1b793c7991fd22ac6a4e3a9c97', operation='UPDATE', pgid='pgtrigger_update_update_4c528', table='learning_catalog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='catalog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "learning_catalogevent" ("active", "available_from", "available_until", "created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "public", "thumbnail") VALUES (OLD."active", OLD."available_from", OLD."available_until", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."public", OLD."thumbnail"); RETURN NULL;', hash='4925642827df870027b7571664f49f310821e255', operation='DELETE', pgid='pgtrigger_delete_delete_2a67e', table='learning_catalog', when='AFTER')),
        ),
    ]
