# Generated by Django 6.0.2 on 2026-03-02 17:13

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Edited')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Action')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Content Draft',
                'verbose_name_plural': 'Content Drafts',
            },
        ),
        migrations.CreateModel(
            name='DraftEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Edited')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Action')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('author', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content type')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='studio.draft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(fields=('author', 'content_type', 'content_id'), name='studio_draft_coty_coid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='draft',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "studio_draftevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."author_id", NEW."content_id", NEW."content_type_id", NEW."detail", NEW."edited", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='74a02de2f26d4e59c7d4d0cac7fb25ac0a34ed7f', operation='INSERT', pgid='pgtrigger_insert_insert_f495e', table='studio_draft', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='draft',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "studio_draftevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."author_id", NEW."content_id", NEW."content_type_id", NEW."detail", NEW."edited", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c09f80b4afc40926883419725f88bc86fb1a5b07', operation='UPDATE', pgid='pgtrigger_update_update_477de', table='studio_draft', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='draft',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "studio_draftevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."author_id", OLD."content_id", OLD."content_type_id", OLD."detail", OLD."edited", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='a50e7f9dec70e3a03923edf02de44e193110e844', operation='DELETE', pgid='pgtrigger_delete_delete_db766', table='studio_draft', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='draftevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='011abe80fb87e61edab06b9858f92f4dd66ce930', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_dd2c4', table='studio_draftevent', when='BEFORE')),
        ),
    ]
