# Generated by Django 6.0.3 on 2026-03-19 17:25

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Edited')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Action')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Content Editing',
                'verbose_name_plural': 'Content Editings',
            },
        ),
        migrations.CreateModel(
            name='EditingEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Edited')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Action')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('author', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content type')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='studio.editing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='editing',
            constraint=models.UniqueConstraint(fields=('author', 'content_type', 'content_id'), name='studio_editing_coty_coid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='editing',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "studio_editingevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."author_id", NEW."content_id", NEW."content_type_id", NEW."detail", NEW."edited", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='6dc54e2c432d8859ea15f3a0edef97f5d2b2a429', operation='INSERT', pgid='pgtrigger_insert_insert_4cef1', table='studio_editing', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='editing',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "studio_editingevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."author_id", NEW."content_id", NEW."content_type_id", NEW."detail", NEW."edited", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c1f6badaf8cb22ff861fe1265fc4f9f7a9eb57c9', operation='UPDATE', pgid='pgtrigger_update_update_9a5c4', table='studio_editing', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='editing',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "studio_editingevent" ("author_id", "content_id", "content_type_id", "detail", "edited", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."author_id", OLD."content_id", OLD."content_type_id", OLD."detail", OLD."edited", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='27dedb0d4dbca1c8c960cb9c39d32a60d1751b66', operation='DELETE', pgid='pgtrigger_delete_delete_c1e2e', table='studio_editing', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='editingevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9ffd877bdfc5aebf92060cf13876d66eb1508081', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c43e5', table='studio_editingevent', when='BEFORE')),
        ),
    ]
