# Generated by Django 6.0.3 on 2026-03-10 12:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='appeal',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AddField(
            model_name='appealevent',
            name='reviewer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Path'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_appealevent" ("created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review", "reviewer_id") VALUES (NEW."created", NEW."explanation", NEW."id", NEW."learner_id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."question_type_id", NEW."review", NEW."reviewer_id"); RETURN NULL;', hash='a0f2a97c3d500389c6ae51a89ab359fed2f11e25', operation='INSERT', pgid='pgtrigger_insert_insert_c7b97', table='operation_appeal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."explanation" IS DISTINCT FROM (NEW."explanation") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."learner_id" IS DISTINCT FROM (NEW."learner_id") OR OLD."path" IS DISTINCT FROM (NEW."path") OR OLD."question_id" IS DISTINCT FROM (NEW."question_id") OR OLD."question_type_id" IS DISTINCT FROM (NEW."question_type_id") OR OLD."review" IS DISTINCT FROM (NEW."review") OR OLD."reviewer_id" IS DISTINCT FROM (NEW."reviewer_id"))', func='INSERT INTO "operation_appealevent" ("created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review", "reviewer_id") VALUES (NEW."created", NEW."explanation", NEW."id", NEW."learner_id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."question_type_id", NEW."review", NEW."reviewer_id"); RETURN NULL;', hash='0f827690772392e91649050a0376729b1b0ad8bb', operation='UPDATE', pgid='pgtrigger_update_update_3fe73', table='operation_appeal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_appealevent" ("created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review", "reviewer_id") VALUES (OLD."created", OLD."explanation", OLD."id", OLD."learner_id", OLD."modified", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."question_type_id", OLD."review", OLD."reviewer_id"); RETURN NULL;', hash='e9c2459d59c132d165ef47959f8145e3bee0b847', operation='DELETE', pgid='pgtrigger_delete_delete_1853c', table='operation_appeal', when='AFTER')),
        ),
    ]
