# Generated by Django 6.0.1 on 2026-01-30 12:01

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='show_on_join',
        ),
        migrations.RemoveField(
            model_name='policyevent',
            name='show_on_join',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_policyevent" ("active", "created", "description", "id", "kind", "mandatory", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "title") VALUES (NEW."active", NEW."created", NEW."description", NEW."id", NEW."kind", NEW."mandatory", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."title"); RETURN NULL;', hash='7d727d9089f0d74ed135c1da202712030ffca500', operation='INSERT', pgid='pgtrigger_insert_insert_27011', table='operation_policy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."kind" IS DISTINCT FROM (NEW."kind") OR OLD."mandatory" IS DISTINCT FROM (NEW."mandatory") OR OLD."priority" IS DISTINCT FROM (NEW."priority") OR OLD."title" IS DISTINCT FROM (NEW."title"))', func='INSERT INTO "operation_policyevent" ("active", "created", "description", "id", "kind", "mandatory", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "title") VALUES (NEW."active", NEW."created", NEW."description", NEW."id", NEW."kind", NEW."mandatory", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."title"); RETURN NULL;', hash='952182b681c43de00bc2a59a6ff6a8e98882c6a8', operation='UPDATE', pgid='pgtrigger_update_update_7eb72', table='operation_policy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_policyevent" ("active", "created", "description", "id", "kind", "mandatory", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "title") VALUES (OLD."active", OLD."created", OLD."description", OLD."id", OLD."kind", OLD."mandatory", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority", OLD."title"); RETURN NULL;', hash='48d953e93e762043f7e646c0f5b04c575c9705f9', operation='DELETE', pgid='pgtrigger_delete_delete_13c9b', table='operation_policy', when='AFTER')),
        ),
    ]
