# Generated by Django 6.0.1 on 2026-02-02 18:24

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDeviceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='operation.notificationdevice')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationdevice',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_notificationdeviceevent" ("active", "created", "device_name", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "token", "user_id") VALUES (NEW."active", NEW."created", NEW."device_name", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform", NEW."token", NEW."user_id"); RETURN NULL;', hash='0319a32fdd4e0b578e45b85f04d98b73325b6bac', operation='INSERT', pgid='pgtrigger_insert_insert_08f1b', table='operation_notificationdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationdevice',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."device_name" IS DISTINCT FROM (NEW."device_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."platform" IS DISTINCT FROM (NEW."platform") OR OLD."token" IS DISTINCT FROM (NEW."token") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "operation_notificationdeviceevent" ("active", "created", "device_name", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "token", "user_id") VALUES (NEW."active", NEW."created", NEW."device_name", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform", NEW."token", NEW."user_id"); RETURN NULL;', hash='94f9ec46e91e1fcfdd69f889dee854fad7f7b5c9', operation='UPDATE', pgid='pgtrigger_update_update_a43e3', table='operation_notificationdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationdevice',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_notificationdeviceevent" ("active", "created", "device_name", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "token", "user_id") VALUES (OLD."active", OLD."created", OLD."device_name", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform", OLD."token", OLD."user_id"); RETURN NULL;', hash='36025edd5b96692524068c7655d64b362156b729', operation='DELETE', pgid='pgtrigger_delete_delete_4e9cc', table='operation_notificationdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationdeviceevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='2612ad5fd1c5d887cdc9dd0aa932e3c0d7384360', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f2ff6', table='operation_notificationdeviceevent', when='BEFORE')),
        ),
    ]
