# Generated by Django 6.0.3 on 2026-03-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
