# Generated by Django 6.0.1 on 2026-01-30 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_remove_policy_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policyagreement',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='operation_policyagreement_us_ve_uniq'),
        ),
    ]
