# Generated by Django 6.0.1 on 2026-02-01 10:02

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_policyagreement_operation_policyagreement_us_ve_uniq'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.DateTimeField(blank=True, null=True, verbose_name='Read')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('text', 'Text'), ('fcm', 'FCM')], default='', max_length=20, verbose_name='Channel')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Sent')),
            ],
            options={
                'verbose_name': 'Message State',
                'verbose_name_plural': 'Message States',
            },
        ),
        migrations.CreateModel(
            name='MessageStateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('read', models.DateTimeField(blank=True, null=True, verbose_name='Read')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('text', 'Text'), ('fcm', 'FCM')], default='', max_length=20, verbose_name='Channel')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Sent')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='error',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='error',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='read',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='sent',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.TextField(blank=True, default='', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='message',
            name='email_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='Email Recipients'),
        ),
        migrations.AddField(
            model_name='message',
            name='fcm',
            field=models.TextField(blank=True, default='', verbose_name='FCM'),
        ),
        migrations.AddField(
            model_name='message',
            name='fcm_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='FCM Recipients'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='message',
            name='text_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='Text Recipients'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='email_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='Email Recipients'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='fcm_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='FCM Recipients'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='text_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, verbose_name='Text Recipients'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messageevent" ("created", "data", "email_recipients", "fcm_recipients", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reserved", "text_recipients", "title", "user_id") VALUES (NEW."created", NEW."data", NEW."email_recipients", NEW."fcm_recipients", NEW."group", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reserved", NEW."text_recipients", NEW."title", NEW."user_id"); RETURN NULL;', hash='036afe2c3fd0e9f865a8fe66e044f6326d0bb25f', operation='INSERT', pgid='pgtrigger_insert_insert_8e1f4', table='operation_message', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."data" IS DISTINCT FROM (NEW."data") OR OLD."email_recipients" IS DISTINCT FROM (NEW."email_recipients") OR OLD."fcm_recipients" IS DISTINCT FROM (NEW."fcm_recipients") OR OLD."group" IS DISTINCT FROM (NEW."group") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."reserved" IS DISTINCT FROM (NEW."reserved") OR OLD."text_recipients" IS DISTINCT FROM (NEW."text_recipients") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "operation_messageevent" ("created", "data", "email_recipients", "fcm_recipients", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reserved", "text_recipients", "title", "user_id") VALUES (NEW."created", NEW."data", NEW."email_recipients", NEW."fcm_recipients", NEW."group", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reserved", NEW."text_recipients", NEW."title", NEW."user_id"); RETURN NULL;', hash='e83a09e880adc3921b0655fc8c479a64c5e9c505', operation='UPDATE', pgid='pgtrigger_update_update_1c2e2', table='operation_message', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messageevent" ("created", "data", "email_recipients", "fcm_recipients", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reserved", "text_recipients", "title", "user_id") VALUES (OLD."created", OLD."data", OLD."email_recipients", OLD."fcm_recipients", OLD."group", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reserved", OLD."text_recipients", OLD."title", OLD."user_id"); RETURN NULL;', hash='4cb0b2e5147872f7052c1097615b2efa369e5a87', operation='DELETE', pgid='pgtrigger_delete_delete_3018e', table='operation_message', when='AFTER')),
        ),
        migrations.AddField(
            model_name='messagestate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagestateevent',
            name='message',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagestateevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='messagestateevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='operation.messagestate'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagestate',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messagestateevent" ("channel", "error", "id", "message_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read", "sent") VALUES (NEW."channel", NEW."error", NEW."id", NEW."message_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."read", NEW."sent"); RETURN NULL;', hash='a09b00c5633df645c76aef969d49ce7e4dff0a58', operation='INSERT', pgid='pgtrigger_insert_insert_e3cc4', table='operation_messagestate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagestate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "operation_messagestateevent" ("channel", "error", "id", "message_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read", "sent") VALUES (NEW."channel", NEW."error", NEW."id", NEW."message_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."read", NEW."sent"); RETURN NULL;', hash='d6c0739907091d3cf4f7a2e924c36f0761acc3ed', operation='UPDATE', pgid='pgtrigger_update_update_2491c', table='operation_messagestate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagestate',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messagestateevent" ("channel", "error", "id", "message_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read", "sent") VALUES (OLD."channel", OLD."error", OLD."id", OLD."message_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."read", OLD."sent"); RETURN NULL;', hash='03f00749946bb2d73d9246c131e490a5dd0f9e37', operation='DELETE', pgid='pgtrigger_delete_delete_8d13c', table='operation_messagestate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagestateevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e36f1557567bd71e45d9f76bdb2bd9869bc9d5ea', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c15ac', table='operation_messagestateevent', when='BEFORE')),
        ),
    ]
