# Generated by Django 6.0.1 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_messagestate_messagestateevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='appealevent',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='inquiryresponse',
            name='solved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solved'),
        ),
        migrations.AlterField(
            model_name='inquiryresponseevent',
            name='solved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solved'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='threadevent',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
    ]
