# Generated by Django 6.0.1 on 2026-02-01 17:18

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_appeal_closed_alter_appealevent_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.DateTimeField(auto_now_add=True, verbose_name='Read at')),
            ],
        ),
        migrations.RemoveField(
            model_name='messagestate',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagestateevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='messagestateevent',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagestateevent',
            name='pgh_context',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='message',
            name='delete_delete',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='operation_m_reserve_b29db6_idx',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='email_recipients',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='fcm_recipients',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='messageevent',
            name='text_recipients',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messageevent" ("created", "data", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title", "user_id") VALUES (NEW."created", NEW."data", NEW."group", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title", NEW."user_id"); RETURN NULL;', hash='a78533392df1c2683a6e86060484751fa07746cc', operation='INSERT', pgid='pgtrigger_insert_insert_8e1f4', table='operation_message', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."data" IS DISTINCT FROM (NEW."data") OR OLD."group" IS DISTINCT FROM (NEW."group") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "operation_messageevent" ("created", "data", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title", "user_id") VALUES (NEW."created", NEW."data", NEW."group", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title", NEW."user_id"); RETURN NULL;', hash='f9e5d99a460be54a811fc90d288530706302b2ee', operation='UPDATE', pgid='pgtrigger_update_update_1c2e2', table='operation_message', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='message',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_messageevent" ("created", "data", "group", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title", "user_id") VALUES (OLD."created", OLD."data", OLD."group", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title", OLD."user_id"); RETURN NULL;', hash='42cdf5a7b015dc44ea3d0417352105952e1bde8f', operation='DELETE', pgid='pgtrigger_delete_delete_3018e', table='operation_message', when='AFTER')),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operation.message', verbose_name='Message'),
        ),
        migrations.DeleteModel(
            name='MessageState',
        ),
        migrations.DeleteModel(
            name='MessageStateEvent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email_recipients',
        ),
        migrations.RemoveField(
            model_name='message',
            name='fcm',
        ),
        migrations.RemoveField(
            model_name='message',
            name='fcm_recipients',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text_recipients',
        ),
    ]
