# Generated by Django 6.0.1 on 2026-02-02 09:54

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_messageread_remove_messagestate_message_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appeal',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='inquiry',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='inquiry',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='inquiry',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='thread',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='thread',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='thread',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='appeal',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='appealevent',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='inquiryevent',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='thread',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='threadevent',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_appealevent" ("closed", "created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review") VALUES (NEW."closed", NEW."created", NEW."explanation", NEW."id", NEW."learner_id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."question_type_id", NEW."review"); RETURN NULL;', hash='07dc4960990fcedf7f9620a936cce816acbd698e', operation='INSERT', pgid='pgtrigger_insert_insert_c7b97', table='operation_appeal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."closed" IS DISTINCT FROM (NEW."closed") OR OLD."explanation" IS DISTINCT FROM (NEW."explanation") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."learner_id" IS DISTINCT FROM (NEW."learner_id") OR OLD."path" IS DISTINCT FROM (NEW."path") OR OLD."question_id" IS DISTINCT FROM (NEW."question_id") OR OLD."question_type_id" IS DISTINCT FROM (NEW."question_type_id") OR OLD."review" IS DISTINCT FROM (NEW."review"))', func='INSERT INTO "operation_appealevent" ("closed", "created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review") VALUES (NEW."closed", NEW."created", NEW."explanation", NEW."id", NEW."learner_id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."question_type_id", NEW."review"); RETURN NULL;', hash='2c23232d27ee0da91c7f196c32ca8e150e0fbf01', operation='UPDATE', pgid='pgtrigger_update_update_3fe73', table='operation_appeal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_appealevent" ("closed", "created", "explanation", "id", "learner_id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "question_type_id", "review") VALUES (OLD."closed", OLD."created", OLD."explanation", OLD."id", OLD."learner_id", OLD."modified", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."question_type_id", OLD."review"); RETURN NULL;', hash='dcc8a44c3d2f096c700ab570834bc022b126d98b', operation='DELETE', pgid='pgtrigger_delete_delete_1853c', table='operation_appeal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inquiry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_inquiryevent" ("content_id", "content_type_id", "created", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "title", "writer_id") VALUES (NEW."content_id", NEW."content_type_id", NEW."created", NEW."id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question", NEW."title", NEW."writer_id"); RETURN NULL;', hash='6ee5c163cd766bda9c8483f5a03a2c2038001c5b', operation='INSERT', pgid='pgtrigger_insert_insert_4cbaf', table='operation_inquiry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inquiry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."content_id" IS DISTINCT FROM (NEW."content_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."path" IS DISTINCT FROM (NEW."path") OR OLD."question" IS DISTINCT FROM (NEW."question") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."writer_id" IS DISTINCT FROM (NEW."writer_id"))', func='INSERT INTO "operation_inquiryevent" ("content_id", "content_type_id", "created", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "title", "writer_id") VALUES (NEW."content_id", NEW."content_type_id", NEW."created", NEW."id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question", NEW."title", NEW."writer_id"); RETURN NULL;', hash='eee8f2fe0fa8dc24331e8ef730761cba7c9dfd81', operation='UPDATE', pgid='pgtrigger_update_update_a579a', table='operation_inquiry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inquiry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_inquiryevent" ("content_id", "content_type_id", "created", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "title", "writer_id") VALUES (OLD."content_id", OLD."content_type_id", OLD."created", OLD."id", OLD."modified", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question", OLD."title", OLD."writer_id"); RETURN NULL;', hash='c7cacda00d534ba9d9fc60044f79199786b0cb47', operation='DELETE', pgid='pgtrigger_delete_delete_1d930', table='operation_inquiry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='thread',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_threadevent" ("closed", "comment_count", "created", "description", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rating_avg", "rating_count", "rating_sum", "subject_id", "subject_type_id", "title") VALUES (NEW."closed", NEW."comment_count", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rating_avg", NEW."rating_count", NEW."rating_sum", NEW."subject_id", NEW."subject_type_id", NEW."title"); RETURN NULL;', hash='01088d876ea0657b8dade0dc7956e452fd18e80c', operation='INSERT', pgid='pgtrigger_insert_insert_ea3a9', table='operation_thread', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='thread',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."closed" IS DISTINCT FROM (NEW."closed") OR OLD."comment_count" IS DISTINCT FROM (NEW."comment_count") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."path" IS DISTINCT FROM (NEW."path") OR OLD."rating_avg" IS DISTINCT FROM (NEW."rating_avg") OR OLD."rating_count" IS DISTINCT FROM (NEW."rating_count") OR OLD."rating_sum" IS DISTINCT FROM (NEW."rating_sum") OR OLD."subject_id" IS DISTINCT FROM (NEW."subject_id") OR OLD."subject_type_id" IS DISTINCT FROM (NEW."subject_type_id") OR OLD."title" IS DISTINCT FROM (NEW."title"))', func='INSERT INTO "operation_threadevent" ("closed", "comment_count", "created", "description", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rating_avg", "rating_count", "rating_sum", "subject_id", "subject_type_id", "title") VALUES (NEW."closed", NEW."comment_count", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rating_avg", NEW."rating_count", NEW."rating_sum", NEW."subject_id", NEW."subject_type_id", NEW."title"); RETURN NULL;', hash='68e94affe0587bfd7064155a049a8b7ee5eea7ac', operation='UPDATE', pgid='pgtrigger_update_update_2f223', table='operation_thread', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='thread',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "operation_threadevent" ("closed", "comment_count", "created", "description", "id", "modified", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rating_avg", "rating_count", "rating_sum", "subject_id", "subject_type_id", "title") VALUES (OLD."closed", OLD."comment_count", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rating_avg", OLD."rating_count", OLD."rating_sum", OLD."subject_id", OLD."subject_type_id", OLD."title"); RETURN NULL;', hash='105939e7c5f4a44a7956ce0c0dc22be865938358', operation='DELETE', pgid='pgtrigger_delete_delete_2ddab', table='operation_thread', when='AFTER')),
        ),
    ]
