# Generated by Django 6.0.1 on 2026-02-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_remove_appeal_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageread',
            options={'verbose_name': 'Message Read', 'verbose_name_plural': 'Message Reads'},
        ),
    ]
