# Generated by Django 6.0.1 on 2026-01-11 01:19

import apps.common.storage
import apps.common.util
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='토큰')),
                ('expires', models.DateTimeField(verbose_name='만료')),
            ],
            options={
                'verbose_name': '차단된 토큰',
                'verbose_name_plural': '차단된 토큰',
            },
        ),
        migrations.CreateModel(
            name='BlacklistedTokenEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('token', models.CharField(max_length=500, verbose_name='토큰')),
                ('expires', models.DateTimeField(verbose_name='만료')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('code', models.CharField(max_length=30, verbose_name='코드')),
                ('success', models.BooleanField(default=False, verbose_name='성공')),
                ('fingerprint', models.CharField(max_length=255, verbose_name='지문')),
                ('device_type', models.CharField(default='totp', max_length=50, verbose_name='기기 유형')),
                ('consumer_id', models.CharField(max_length=36, verbose_name='사용 ID')),
            ],
            options={
                'verbose_name': 'OTP 로그',
                'verbose_name_plural': 'OTP 로그',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpLogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('code', models.CharField(max_length=30, verbose_name='코드')),
                ('success', models.BooleanField(default=False, verbose_name='성공')),
                ('fingerprint', models.CharField(max_length=255, verbose_name='지문')),
                ('device_type', models.CharField(default='totp', max_length=50, verbose_name='기기 유형')),
                ('consumer_id', models.CharField(max_length=36, verbose_name='사용 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('kind', models.CharField(choices=[('bookmark', '북마크'), ('like', '좋아요'), ('flag', '신고')], max_length=10, verbose_name='유형')),
                ('target_id', models.CharField(max_length=36, verbose_name='대상 ID')),
            ],
            options={
                'verbose_name': '반응',
                'verbose_name_plural': '반응',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('kind', models.CharField(choices=[('bookmark', '북마크'), ('like', '좋아요'), ('flag', '신고')], max_length=10, verbose_name='유형')),
                ('target_id', models.CharField(max_length=36, verbose_name='대상 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('expires', models.DateTimeField(verbose_name='만료')),
            ],
            options={
                'verbose_name': '임시 비밀번호',
                'verbose_name_plural': '임시 비밀번호',
            },
        ),
        migrations.CreateModel(
            name='TempPasswordEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('expires', models.DateTimeField(verbose_name='만료')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('token', models.CharField(db_index=True, max_length=500, verbose_name='토큰')),
                ('expires', models.DateTimeField(verbose_name='만료')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='사용자 에이전트')),
            ],
            options={
                'verbose_name': '토큰',
                'verbose_name_plural': '토큰',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('token', models.CharField(max_length=500, verbose_name='토큰')),
                ('expires', models.DateTimeField(verbose_name='만료')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='사용자 에이전트')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('avatar', models.ImageField(blank=True, null=True, storage=apps.common.storage.AvatarStorage(access_key='minima', bucket_name='minima', endpoint_url='http://localhost:9000', location='avatar', querystring_expire=86400, secret_key='minima.dev'), upload_to='', verbose_name='아바타')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='닉네임')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='전화번호')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('language', models.CharField(blank=True, default='', max_length=10, verbose_name='언어')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='환경설정')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고 관리자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('avatar', models.ImageField(blank=True, null=True, storage=apps.common.storage.AvatarStorage(access_key='minima', bucket_name='minima', endpoint_url='http://localhost:9000', location='avatar', querystring_expire=86400, secret_key='minima.dev'), upload_to='', verbose_name='아바타')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='닉네임')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='전화번호')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('language', models.CharField(blank=True, default='', max_length=10, verbose_name='언어')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='환경설정')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고 관리자')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blacklistedtoken',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_blacklistedtokenevent" ("expires", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."expires", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."token"); RETURN NULL;', hash='9627aa446dce923a0444614d43b94b20af1d82b2', operation='INSERT', pgid='pgtrigger_insert_insert_b1cb4', table='account_blacklistedtoken', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blacklistedtoken',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "account_blacklistedtokenevent" ("expires", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."expires", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."token"); RETURN NULL;', hash='2895fb4c48f669074d6f3240a1e6e102a4a43ea6', operation='UPDATE', pgid='pgtrigger_update_update_ca001', table='account_blacklistedtoken', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blacklistedtoken',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_blacklistedtokenevent" ("expires", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (OLD."expires", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."token"); RETURN NULL;', hash='f2eca6bf7fd390cd4efd16b98b4f3810da4c8715', operation='DELETE', pgid='pgtrigger_delete_delete_664ee', table='account_blacklistedtoken', when='AFTER')),
        ),
        migrations.AddField(
            model_name='blacklistedtokenevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='blacklistedtokenevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='account.blacklistedtoken'),
        ),
        migrations.AddField(
            model_name='otplog',
            name='consumer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='사용 유형'),
        ),
        migrations.AddField(
            model_name='otplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='otplogevent',
            name='consumer_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='사용 유형'),
        ),
        migrations.AddField(
            model_name='otplogevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='otplogevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='account.otplog'),
        ),
        migrations.AddField(
            model_name='otplogevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='대상 유형'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='reactionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='reactionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='account.reaction'),
        ),
        migrations.AddField(
            model_name='reactionevent',
            name='target_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='대상 유형'),
        ),
        migrations.AddField(
            model_name='reactionevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='temppassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='temppasswordevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='temppasswordevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='account.temppassword'),
        ),
        migrations.AddField(
            model_name='temppasswordevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='tokenevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='tokenevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='account.token'),
        ),
        migrations.AddField(
            model_name='tokenevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='account_use_name_a82ece_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='account_use_nicknam_592ac7_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_userevent" ("avatar", "birth_date", "created", "email", "id", "is_active", "is_staff", "is_superuser", "language", "modified", "name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "preferences") VALUES (NEW."avatar", NEW."birth_date", NEW."created", NEW."email", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."modified", NEW."name", NEW."nickname", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."preferences"); RETURN NULL;', hash='90ffa5af630dcfd5fe991cd40dc7a2868eca2be3', operation='INSERT', pgid='pgtrigger_insert_insert_ae8bc', table='account_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."avatar" IS DISTINCT FROM (NEW."avatar") OR OLD."birth_date" IS DISTINCT FROM (NEW."birth_date") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."nickname" IS DISTINCT FROM (NEW."nickname") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."preferences" IS DISTINCT FROM (NEW."preferences"))', func='INSERT INTO "account_userevent" ("avatar", "birth_date", "created", "email", "id", "is_active", "is_staff", "is_superuser", "language", "modified", "name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "preferences") VALUES (NEW."avatar", NEW."birth_date", NEW."created", NEW."email", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."modified", NEW."name", NEW."nickname", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."preferences"); RETURN NULL;', hash='7d86aac7bd0ca3cbe64ac2ae81499e8983ac5575', operation='UPDATE', pgid='pgtrigger_update_update_66d56', table='account_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_userevent" ("avatar", "birth_date", "created", "email", "id", "is_active", "is_staff", "is_superuser", "language", "modified", "name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "preferences") VALUES (OLD."avatar", OLD."birth_date", OLD."created", OLD."email", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."language", OLD."modified", OLD."name", OLD."nickname", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."preferences"); RETURN NULL;', hash='f571f1c097cadaafb48f0d0660983d8397e02293', operation='DELETE', pgid='pgtrigger_delete_delete_378ac', table='account_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blacklistedtokenevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6781e8f3699a0b8e6ef5765203f76db06e812bf0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0e472', table='account_blacklistedtokenevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='otplog',
            index=models.Index(fields=['consumer_type', 'consumer_id'], name='account_otplog_coty_coid_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='otplog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_otplogevent" ("code", "consumer_id", "consumer_type_id", "created", "device_type", "fingerprint", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "success", "user_id") VALUES (NEW."code", NEW."consumer_id", NEW."consumer_type_id", NEW."created", NEW."device_type", NEW."fingerprint", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."success", NEW."user_id"); RETURN NULL;', hash='d5c288dc606baea1c112cd8d714e7494cd6ba81a', operation='INSERT', pgid='pgtrigger_insert_insert_83d9b', table='account_otplog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='otplog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."consumer_id" IS DISTINCT FROM (NEW."consumer_id") OR OLD."consumer_type_id" IS DISTINCT FROM (NEW."consumer_type_id") OR OLD."device_type" IS DISTINCT FROM (NEW."device_type") OR OLD."fingerprint" IS DISTINCT FROM (NEW."fingerprint") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."success" IS DISTINCT FROM (NEW."success") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "account_otplogevent" ("code", "consumer_id", "consumer_type_id", "created", "device_type", "fingerprint", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "success", "user_id") VALUES (NEW."code", NEW."consumer_id", NEW."consumer_type_id", NEW."created", NEW."device_type", NEW."fingerprint", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."success", NEW."user_id"); RETURN NULL;', hash='e197639521e3ef2ca83974c2979484943f7ef87e', operation='UPDATE', pgid='pgtrigger_update_update_fe51f', table='account_otplog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='otplog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_otplogevent" ("code", "consumer_id", "consumer_type_id", "created", "device_type", "fingerprint", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "success", "user_id") VALUES (OLD."code", OLD."consumer_id", OLD."consumer_type_id", OLD."created", OLD."device_type", OLD."fingerprint", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."success", OLD."user_id"); RETURN NULL;', hash='8eeea494013be46e1731df295fe207e2cc3f1a3a', operation='DELETE', pgid='pgtrigger_delete_delete_bf419', table='account_otplog', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='otplogevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='b0cbfc7efc744f782bacbb917b8d0c1e7c7b4419', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c7211', table='account_otplogevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='account_reaction_us_kaid_taty_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reaction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_reactionevent" ("created", "id", "kind", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "target_type_id", "user_id") VALUES (NEW."created", NEW."id", NEW."kind", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."target_id", NEW."target_type_id", NEW."user_id"); RETURN NULL;', hash='d825078a0a6be63e54b8320f40bd3f2de0548172', operation='INSERT', pgid='pgtrigger_insert_insert_ca096', table='account_reaction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reaction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."kind" IS DISTINCT FROM (NEW."kind") OR OLD."target_id" IS DISTINCT FROM (NEW."target_id") OR OLD."target_type_id" IS DISTINCT FROM (NEW."target_type_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "account_reactionevent" ("created", "id", "kind", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "target_type_id", "user_id") VALUES (NEW."created", NEW."id", NEW."kind", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."target_id", NEW."target_type_id", NEW."user_id"); RETURN NULL;', hash='3b887370a7695e70292024d4e5f100ec48f02814', operation='UPDATE', pgid='pgtrigger_update_update_115b3', table='account_reaction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reaction',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_reactionevent" ("created", "id", "kind", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "target_type_id", "user_id") VALUES (OLD."created", OLD."id", OLD."kind", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."target_id", OLD."target_type_id", OLD."user_id"); RETURN NULL;', hash='1ec935fa1f7844738c43b68f64d182ba146c0d25', operation='DELETE', pgid='pgtrigger_delete_delete_2229e', table='account_reaction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reactionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0ed9a13705de79f6ea10863b949860973c6282af', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_251f0', table='account_reactionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='temppassword',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_temppasswordevent" ("expires", "id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."expires", NEW."id", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='2f25049920db6cab89bac563880517f14fd44f9b', operation='INSERT', pgid='pgtrigger_insert_insert_89b0f', table='account_temppassword', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='temppassword',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "account_temppasswordevent" ("expires", "id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."expires", NEW."id", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='0aa38473d69a09de843bf257351e4c0750c29c47', operation='UPDATE', pgid='pgtrigger_update_update_439e7', table='account_temppassword', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='temppassword',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_temppasswordevent" ("expires", "id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."expires", OLD."id", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='2e04e64db5883d6979cfbdd2325cc35acdd3a93c', operation='DELETE', pgid='pgtrigger_delete_delete_154ac', table='account_temppassword', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='temppasswordevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f9286a25f00726258d4dbfbc8e7a265ce65badb8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_67944', table='account_temppasswordevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='token',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_tokenevent" ("created", "expires", "id", "ip_address", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token", "user_agent", "user_id") VALUES (NEW."created", NEW."expires", NEW."id", NEW."ip_address", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."token", NEW."user_agent", NEW."user_id"); RETURN NULL;', hash='c867e7451da4ac9d07a7d0af5ce225a64f3820ed', operation='INSERT', pgid='pgtrigger_insert_insert_b1e75', table='account_token', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='token',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."expires" IS DISTINCT FROM (NEW."expires") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."ip_address" IS DISTINCT FROM (NEW."ip_address") OR OLD."token" IS DISTINCT FROM (NEW."token") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."user_agent" IS DISTINCT FROM (NEW."user_agent"))', func='INSERT INTO "account_tokenevent" ("created", "expires", "id", "ip_address", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token", "user_agent", "user_id") VALUES (NEW."created", NEW."expires", NEW."id", NEW."ip_address", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."token", NEW."user_agent", NEW."user_id"); RETURN NULL;', hash='3833f97c584d5498eea37fe0c41b1dbc6238dfbc', operation='UPDATE', pgid='pgtrigger_update_update_31e68', table='account_token', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='token',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_tokenevent" ("created", "expires", "id", "ip_address", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token", "user_agent", "user_id") VALUES (OLD."created", OLD."expires", OLD."id", OLD."ip_address", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."token", OLD."user_agent", OLD."user_id"); RETURN NULL;', hash='c8c3c83892d54fdecc58f7d3f5ad50a26ae6e892', operation='DELETE', pgid='pgtrigger_delete_delete_7e6ac', table='account_token', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tokenevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7a8b9b0b3cb32077a49bf6c62610bdbcedfbc8a5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_09002', table='account_tokenevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e0c52ab0bf325f3ac32084ca15895f2093019899', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_9a64f', table='account_userevent', when='BEFORE')),
        ),
    ]
