# Generated by Django 6.0.1 on 2026-01-13 07:37

import apps.common.storage
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterModelOptions(
            name='otplog',
            options={'verbose_name': 'OTP Log', 'verbose_name_plural': 'OTP Logs'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
        migrations.AlterModelOptions(
            name='temppassword',
            options={'verbose_name': 'Temporary Password', 'verbose_name_plural': 'Temporary Passwords'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(max_length=500, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='blacklistedtokenevent',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='blacklistedtokenevent',
            name='token',
            field=models.CharField(max_length=500, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='consumer_id',
            field=models.CharField(max_length=36, verbose_name='Consumer ID'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='consumer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Consumer Type'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='device_type',
            field=models.CharField(default='totp', max_length=50, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='fingerprint',
            field=models.CharField(max_length=255, verbose_name='Fingerprint'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='consumer_id',
            field=models.CharField(max_length=36, verbose_name='Consumer ID'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='consumer_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Consumer Type'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='device_type',
            field=models.CharField(default='totp', max_length=50, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='fingerprint',
            field=models.CharField(max_length=255, verbose_name='Fingerprint'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='otplogevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('like', 'Like'), ('flag', 'Flag')], max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target_id',
            field=models.CharField(max_length=36, verbose_name='Target ID'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Target Type'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reactionevent',
            name='kind',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('like', 'Like'), ('flag', 'Flag')], max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='reactionevent',
            name='target_id',
            field=models.CharField(max_length=36, verbose_name='Target ID'),
        ),
        migrations.AlterField(
            model_name='reactionevent',
            name='target_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Target Type'),
        ),
        migrations.AlterField(
            model_name='reactionevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='temppassword',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='temppassword',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='temppassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='temppasswordevent',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='temppasswordevent',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='temppasswordevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='token',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='tokenevent',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='tokenevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='tokenevent',
            name='token',
            field=models.CharField(max_length=500, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='tokenevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tokenevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.AvatarStorage(access_key='minima', bucket_name='minima', endpoint_url='http://localhost:9000', location='avatar', querystring_expire=86400, secret_key='minima.dev'), upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Preferences'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.AvatarStorage(access_key='minima', bucket_name='minima', endpoint_url='http://localhost:9000', location='avatar', querystring_expire=86400, secret_key='minima.dev'), upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Preferences'),
        ),
    ]
