# Generated by Django 6.0.1 on 2026-01-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_blacklistedtoken_options_alter_otplog_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='account_reaction_us_kaid_taty_uniq',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReactionEvent',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
