# Generated by Django 6.0.1 on 2026-01-11 01:20

import apps.common.util
import apps.content.models
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('format', models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('ebook', 'Ebook'), ('html', 'HTML'), ('pdf', 'PDF')], max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('uploaded', models.BooleanField(default=False, verbose_name='Uploaded')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('format', models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('ebook', 'Ebook'), ('html', 'HTML'), ('pdf', 'PDF')], max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('uploaded', models.BooleanField(default=False, verbose_name='Uploaded')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='content.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('note', models.TextField(verbose_name='Note')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('note', models.TextField(verbose_name='Note')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='content.note')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicAccessMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('archive', models.DateTimeField(verbose_name='Archive')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Public Access Media',
                'verbose_name_plural': 'Public Access Medias',
            },
        ),
        migrations.CreateModel(
            name='PublicAccessMediaEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('archive', models.DateTimeField(verbose_name='Archive')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='content.publicaccessmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, verbose_name='Language')),
                ('body', models.TextField(verbose_name='Body')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Subtitle',
                'verbose_name_plural': 'Subtitles',
            },
        ),
        migrations.CreateModel(
            name='SubtitleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('lang', models.CharField(max_length=10, verbose_name='Language')),
                ('body', models.TextField(verbose_name='Body')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='content.subtitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('last_position', models.FloatField(verbose_name='Last Position')),
                ('watch_bits', apps.content.models.VarBitField(blank=True, null=True, verbose_name='Watch Bits')),
                ('rate', models.FloatField(verbose_name='Watch Rate')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('watch_bits', apps.content.models.VarBitField(blank=True, null=True, verbose_name='Watch Bits')),
                ('rate', models.FloatField(verbose_name='Watch Rate')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='content.watch')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_mediaevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "uploaded", "url", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."thumbnail", NEW."title", NEW."uploaded", NEW."url", NEW."verification_required"); RETURN NULL;', hash='c110b8d97cd8001ecab1c357afa8fa05242ee820', operation='INSERT', pgid='pgtrigger_insert_insert_fc9e0', table='content_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."uploaded" IS DISTINCT FROM (NEW."uploaded") OR OLD."url" IS DISTINCT FROM (NEW."url") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "content_mediaevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "uploaded", "url", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."thumbnail", NEW."title", NEW."uploaded", NEW."url", NEW."verification_required"); RETURN NULL;', hash='2519e2f32e52b3cca42f7b87aae02881f7eb719c', operation='UPDATE', pgid='pgtrigger_update_update_56c38', table='content_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_mediaevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "uploaded", "url", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."thumbnail", OLD."title", OLD."uploaded", OLD."url", OLD."verification_required"); RETURN NULL;', hash='b2c4315b4b83ffdae3cfef9f1c36ca4e0d2e768f', operation='DELETE', pgid='pgtrigger_delete_delete_5e45c', table='content_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='mediaevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c5aa0f93d0b2817b0943511e68e4af6602403b0b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_76545', table='content_mediaevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'media', 'context'), name='content_note_us_me_co_keuniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_noteevent" ("context", "created", "id", "media_id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."context", NEW."created", NEW."id", NEW."media_id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='701c1114f89c3af4c77ee5998c7fd203ca55d079', operation='INSERT', pgid='pgtrigger_insert_insert_70fb2', table='content_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "content_noteevent" ("context", "created", "id", "media_id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."context", NEW."created", NEW."id", NEW."media_id", NEW."modified", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='95a380717ca94e988ec88da822157c191c8c8496', operation='UPDATE', pgid='pgtrigger_update_update_2f73b', table='content_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_noteevent" ("context", "created", "id", "media_id", "modified", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."context", OLD."created", OLD."id", OLD."media_id", OLD."modified", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='875b4e9ef156d9b838065df5a7ac1c00e2bdca47', operation='DELETE', pgid='pgtrigger_delete_delete_71435', table='content_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noteevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f2dbf1ec2d35fd4a87e458e6c6fee006df82802b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_be996', table='content_noteevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_publicaccessmediaevent" ("archive", "end", "id", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (NEW."archive", NEW."end", NEW."id", NEW."media_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start"); RETURN NULL;', hash='eb1127ef87695fd5edca7e582fd2c8b0b73cebf5', operation='INSERT', pgid='pgtrigger_insert_insert_ef879', table='content_publicaccessmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "content_publicaccessmediaevent" ("archive", "end", "id", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (NEW."archive", NEW."end", NEW."id", NEW."media_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start"); RETURN NULL;', hash='a77b7a6ba9108f6731fce943734d78a622e6715a', operation='UPDATE', pgid='pgtrigger_update_update_3819b', table='content_publicaccessmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_publicaccessmediaevent" ("archive", "end", "id", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (OLD."archive", OLD."end", OLD."id", OLD."media_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start"); RETURN NULL;', hash='51c4da94ea983d57555d0eee741f3f6e16ee9882', operation='DELETE', pgid='pgtrigger_delete_delete_ddc14', table='content_publicaccessmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmediaevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='65ebf1173c7158df0a5ca711e99e07359ebaf744', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_88c80', table='content_publicaccessmediaevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.UniqueConstraint(fields=('media', 'lang'), name='content_subtitle_me_la_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subtitle',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_subtitleevent" ("body", "id", "lang", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."body", NEW."id", NEW."lang", NEW."media_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='2700129185ab329ba88eb1351e3d1d57c526e68c', operation='INSERT', pgid='pgtrigger_insert_insert_f6fd3', table='content_subtitle', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subtitle',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "content_subtitleevent" ("body", "id", "lang", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."body", NEW."id", NEW."lang", NEW."media_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='dd5ade6bb545a6bb3b86197487037104b675a575', operation='UPDATE', pgid='pgtrigger_update_update_1b31d', table='content_subtitle', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subtitle',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_subtitleevent" ("body", "id", "lang", "media_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."body", OLD."id", OLD."lang", OLD."media_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='d13695eee462f6d4c7fa8e2acb0b9493eb871cfe', operation='DELETE', pgid='pgtrigger_delete_delete_9cba6', table='content_subtitle', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subtitleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6f328d7ad9b64b25cf40c1f92abe119e762c3a61', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_dcd00', table='content_subtitleevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['user_id', 'context'], name='content_wat_user_id_f21710_idx'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('user', 'media', 'context'), name='content_watch_us_me_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watch',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_watchevent" ("context", "created", "id", "media_id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "user_id", "watch_bits") VALUES (NEW."context", NEW."created", NEW."id", NEW."media_id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rate", NEW."user_id", NEW."watch_bits"); RETURN NULL;', hash='9a74ef4b9b80aabf6ff3afe1204fa1a7b6ddb663', operation='INSERT', pgid='pgtrigger_insert_insert_ed900', table='content_watch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watch',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."watch_bits" IS DISTINCT FROM (NEW."watch_bits"))', func='INSERT INTO "content_watchevent" ("context", "created", "id", "media_id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "user_id", "watch_bits") VALUES (NEW."context", NEW."created", NEW."id", NEW."media_id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rate", NEW."user_id", NEW."watch_bits"); RETURN NULL;', hash='a4c30e724130f7aa54b905577ad348c2a08f8236', operation='UPDATE', pgid='pgtrigger_update_update_7cf93', table='content_watch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watch',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_watchevent" ("context", "created", "id", "media_id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "user_id", "watch_bits") VALUES (OLD."context", OLD."created", OLD."id", OLD."media_id", OLD."modified", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rate", OLD."user_id", OLD."watch_bits"); RETURN NULL;', hash='f09956ec81d4895fa287bcb389053f4a8e034364', operation='DELETE', pgid='pgtrigger_delete_delete_38707', table='content_watch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watchevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='40439646d2bcc72fec2d30775b19b467c1560c7e', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_93fd7', table='content_watchevent', when='BEFORE')),
        ),
    ]
