# Generated by Django 6.0.1 on 2026-01-18 13:42

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='publicaccessmedia',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='publicaccessmedia',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='publicaccessmedia',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='publicaccessmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaccessmedia',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='publicaccessmediaevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaccessmediaevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_publicaccessmediaevent" ("archive", "created", "end", "id", "media_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (NEW."archive", NEW."created", NEW."end", NEW."id", NEW."media_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start"); RETURN NULL;', hash='62c49339a1c6a0b7f663de4236bb4c0cb1461f47', operation='INSERT', pgid='pgtrigger_insert_insert_ef879', table='content_publicaccessmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."archive" IS DISTINCT FROM (NEW."archive") OR OLD."end" IS DISTINCT FROM (NEW."end") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."start" IS DISTINCT FROM (NEW."start"))', func='INSERT INTO "content_publicaccessmediaevent" ("archive", "created", "end", "id", "media_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (NEW."archive", NEW."created", NEW."end", NEW."id", NEW."media_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start"); RETURN NULL;', hash='2398a33e75fd14a41303aa3967f5d79685887c57', operation='UPDATE', pgid='pgtrigger_update_update_3819b', table='content_publicaccessmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicaccessmedia',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_publicaccessmediaevent" ("archive", "created", "end", "id", "media_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start") VALUES (OLD."archive", OLD."created", OLD."end", OLD."id", OLD."media_id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start"); RETURN NULL;', hash='1a2d0f82d134618928126a91d95a76dd1d35bc62', operation='DELETE', pgid='pgtrigger_delete_delete_ddc14', table='content_publicaccessmedia', when='AFTER')),
        ),
    ]
