# Generated by Django 6.0.1 on 2026-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quiz.quiz', verbose_name='Quizzes'),
        ),
    ]
