# Generated by Django 6.0.1 on 2026-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_media_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('ebook', 'Ebook'), ('html', 'HTML'), ('pdf', 'PDF'), ('live', 'Live')], max_length=30, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='mediaevent',
            name='format',
            field=models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('ebook', 'Ebook'), ('html', 'HTML'), ('pdf', 'PDF'), ('live', 'Live')], max_length=30, verbose_name='Format'),
        ),
    ]
