# Generated by Django 6.0.2 on 2026-03-03 12:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_media_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='media',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='mediaevent',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_mediaevent" ("audience", "channel", "created", "description", "duration", "featured", "format", "id", "license", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "thumbnail", "title", "url", "verification_required") VALUES (NEW."audience", NEW."channel", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."license", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."thumbnail", NEW."title", NEW."url", NEW."verification_required"); RETURN NULL;', hash='d0e286c74db1799bd9047f85b12b8606d5210f67', operation='INSERT', pgid='pgtrigger_insert_insert_fc9e0', table='content_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."channel" IS DISTINCT FROM (NEW."channel") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."license" IS DISTINCT FROM (NEW."license") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."url" IS DISTINCT FROM (NEW."url") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "content_mediaevent" ("audience", "channel", "created", "description", "duration", "featured", "format", "id", "license", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "thumbnail", "title", "url", "verification_required") VALUES (NEW."audience", NEW."channel", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."license", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."thumbnail", NEW."title", NEW."url", NEW."verification_required"); RETURN NULL;', hash='e4ffd628e26761e6f9a30e02d092cc7724f546e4', operation='UPDATE', pgid='pgtrigger_update_update_56c38', table='content_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "content_mediaevent" ("audience", "channel", "created", "description", "duration", "featured", "format", "id", "license", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "thumbnail", "title", "url", "verification_required") VALUES (OLD."audience", OLD."channel", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."license", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."thumbnail", OLD."title", OLD."url", OLD."verification_required"); RETURN NULL;', hash='1b4b164ddb12ef8493ece66bcfd2f785e22fb9cb', operation='DELETE', pgid='pgtrigger_delete_delete_5e45c', table='content_media', when='AFTER')),
        ),
    ]
