# Generated by Django 6.0.1 on 2026-01-11 01:20

import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.question')),
                ('paper', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.questionpaper', verbose_name='Question Paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionpaper', verbose_name='Question Paper'),
        ),
        migrations.CreateModel(
            name='QuestionPaperEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.questionpaper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('hashed_email', models.CharField(max_length=64, verbose_name='Hashed Email')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('complete_message', models.TextField(blank=True, default='', verbose_name='Complete Message')),
                ('anonymous', models.BooleanField(default=True, verbose_name='Anonymous')),
                ('likert_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, verbose_name='Likert Options')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionpaper', verbose_name='Question Paper')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('hashed_email', models.CharField(max_length=64, verbose_name='Hashed Email')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.submission')),
                ('respondent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
                ('survey', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.survey', verbose_name='Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Survey'),
        ),
        migrations.CreateModel(
            name='SurveyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('complete_message', models.TextField(blank=True, default='', verbose_name='Complete Message')),
                ('anonymous', models.BooleanField(default=True, verbose_name='Anonymous')),
                ('likert_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, verbose_name='Likert Options')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('paper', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.questionpaper', verbose_name='Question Paper')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='questionpaper',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='survey_questionpaper_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpaper',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionpaperevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='6cf8c89ae35ce5303d7ada6a4e0fc0d7542a223f', operation='INSERT', pgid='pgtrigger_insert_insert_b3e2f', table='survey_questionpaper', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpaper',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "survey_questionpaperevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='5373184b22f1839f4dfd32c9c05e93f3584ef5bb', operation='UPDATE', pgid='pgtrigger_update_update_bfc4f', table='survey_questionpaper', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpaper',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionpaperevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='dbbd82a049c5c0f61749db4b3347758876ea3a7f', operation='DELETE', pgid='pgtrigger_delete_delete_6ef7d', table='survey_questionpaper', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d78b37e15e0d247600b5ad092f90baec3c27b200', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7567d', table='survey_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "paper_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."mandatory", NEW."options", NEW."ordering", NEW."paper_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question", NEW."supplement"); RETURN NULL;', hash='b154097b338ad47e856148fc7495d61b8eb27174', operation='INSERT', pgid='pgtrigger_insert_insert_9df2d', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "paper_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."mandatory", NEW."options", NEW."ordering", NEW."paper_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question", NEW."supplement"); RETURN NULL;', hash='3c0e3283ed541f383e455e289e43f2667e3f697e', operation='UPDATE', pgid='pgtrigger_update_update_08217', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "paper_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question", "supplement") VALUES (OLD."format", OLD."id", OLD."mandatory", OLD."options", OLD."ordering", OLD."paper_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question", OLD."supplement"); RETURN NULL;', hash='9d9091735210e4333e323318a3241967c52c4baa', operation='DELETE', pgid='pgtrigger_delete_delete_40ba8', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpaperevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='29157b8325aaeef478d967aadd2debb5b27752c5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d44a4', table='survey_questionpaperevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."likert_options", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."paper_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='3d0c80c9364ddb61c2ee21d0306388089ed0df58', operation='INSERT', pgid='pgtrigger_insert_insert_69de8', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."anonymous" IS DISTINCT FROM (NEW."anonymous") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."complete_message" IS DISTINCT FROM (NEW."complete_message") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."likert_options" IS DISTINCT FROM (NEW."likert_options") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."paper_id" IS DISTINCT FROM (NEW."paper_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."likert_options", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."paper_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='422762824e79e8614fa85bf81b0149aea693476e', operation='UPDATE', pgid='pgtrigger_update_update_76063', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "thumbnail", "title", "verification_required") VALUES (OLD."anonymous", OLD."audience", OLD."complete_message", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."likert_options", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."paper_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='e878e22368c78d6e176a92b13981153c1035819b', operation='DELETE', pgid='pgtrigger_delete_delete_3408b', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8524f6ee0bd37bc9d33ddeeb6cde4c9378610cdd', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_61717', table='survey_submissionevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['hashed_email'], name='survey_subm_hashed__762554_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('respondent__isnull', False)), fields=('survey', 'respondent'), name='survey_submission_su_re_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('survey', 'hashed_email'), name='survey_submission_su_haem_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "created", "hashed_email", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."created", NEW."hashed_email", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='f6b0cc564be571a93af88506848af1d127fa9976', operation='INSERT', pgid='pgtrigger_insert_insert_ebca0', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."hashed_email" IS DISTINCT FROM (NEW."hashed_email") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."respondent_id" IS DISTINCT FROM (NEW."respondent_id") OR OLD."survey_id" IS DISTINCT FROM (NEW."survey_id"))', func='INSERT INTO "survey_submissionevent" ("active", "answers", "created", "hashed_email", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."created", NEW."hashed_email", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='90f5922984a0c5ea83eb657b36f5a4c1615d2129', operation='UPDATE', pgid='pgtrigger_update_update_d6efc', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "created", "hashed_email", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (OLD."active", OLD."answers", OLD."created", OLD."hashed_email", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."respondent_id", OLD."survey_id"); RETURN NULL;', hash='3876fdc898e78e1a0a82ba0e77697cc8577256f4', operation='DELETE', pgid='pgtrigger_delete_delete_fa339', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='surveyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='3f250b20788a10195e24ff213ff940cb31b9a6a9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e32d2', table='survey_surveyevent', when='BEFORE')),
        ),
    ]
