# Generated by Django 6.0.2 on 2026-02-24 05:50

import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.question')),
                ('pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='QuestionPoolEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.questionpool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('complete_message', models.TextField(blank=True, default='', verbose_name='Complete Message')),
                ('anonymous', models.BooleanField(default=True, verbose_name='Anonymous')),
                ('show_results', models.BooleanField(default=False, verbose_name='Show Results')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('question_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.submission')),
                ('respondent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
                ('survey', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.survey', verbose_name='Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Survey'),
        ),
        migrations.CreateModel(
            name='SurveyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('complete_message', models.TextField(blank=True, default='', verbose_name='Complete Message')),
                ('anonymous', models.BooleanField(default=True, verbose_name='Anonymous')),
                ('show_results', models.BooleanField(default=False, verbose_name='Show Results')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='survey.survey')),
                ('question_pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='survey_questionpool_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='6b9c8496a18cf6a7b7a93305dc64fc8e66e90423', operation='INSERT', pgid='pgtrigger_insert_insert_bb0ec', table='survey_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "survey_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='cee2871c295387133d3edc90ccdc20c204f0212d', operation='UPDATE', pgid='pgtrigger_update_update_30228', table='survey_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='ece85f3d141adea4f19e3bd8c1cc3513f79ffb6b', operation='DELETE', pgid='pgtrigger_delete_delete_62cb9', table='survey_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d78b37e15e0d247600b5ad092f90baec3c27b200', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7567d', table='survey_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."mandatory", NEW."options", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='32cc9f9e91c52425cf32a2b535c0cb93c444f877', operation='INSERT', pgid='pgtrigger_insert_insert_9df2d', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."mandatory", NEW."options", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='7a23a3e4e29529a0d55a57e34ba8abdaf5ec44b4', operation='UPDATE', pgid='pgtrigger_update_update_08217', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_questionevent" ("format", "id", "mandatory", "options", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "question", "supplement") VALUES (OLD."format", OLD."id", OLD."mandatory", OLD."options", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pool_id", OLD."question", OLD."supplement"); RETURN NULL;', hash='573266f91b5fb5e308d40f960a43f78a07f620fd', operation='DELETE', pgid='pgtrigger_delete_delete_40ba8', table='survey_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpoolevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='069a87d51403973523d3be6f4ee0791a642895e7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a8eae', table='survey_questionpoolevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='cf049c97c09d55b435d07a2b8fcb97aa5c07abdf', operation='INSERT', pgid='pgtrigger_insert_insert_69de8', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."anonymous" IS DISTINCT FROM (NEW."anonymous") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."complete_message" IS DISTINCT FROM (NEW."complete_message") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."show_results" IS DISTINCT FROM (NEW."show_results") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='d26a6b2ad7958e8c48103888e80f5caa7745b7a0', operation='UPDATE', pgid='pgtrigger_update_update_76063', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (OLD."anonymous", OLD."audience", OLD."complete_message", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_pool_id", OLD."show_results", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='2a13eddd2f5050ffada4d3156be445e992e67ed2', operation='DELETE', pgid='pgtrigger_delete_delete_3408b', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8524f6ee0bd37bc9d33ddeeb6cde4c9378610cdd', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_61717', table='survey_submissionevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('respondent__isnull', False)), fields=('survey', 'respondent', 'context'), name='survey_submission_su_re_co_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='fb6452cbb3d1aa9db4ef53a62f1270494387eee1', operation='INSERT', pgid='pgtrigger_insert_insert_ebca0', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."respondent_id" IS DISTINCT FROM (NEW."respondent_id") OR OLD."survey_id" IS DISTINCT FROM (NEW."survey_id"))', func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='df81725ebc81e5c1babeffc37a9679597ebbf435', operation='UPDATE', pgid='pgtrigger_update_update_d6efc', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (OLD."active", OLD."answers", OLD."context", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."respondent_id", OLD."survey_id"); RETURN NULL;', hash='3362fcb2b71555f84a98337b039e412024fceeeb', operation='DELETE', pgid='pgtrigger_delete_delete_fa339', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='surveyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='3f250b20788a10195e24ff213ff940cb31b9a6a9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e32d2', table='survey_surveyevent', when='BEFORE')),
        ),
    ]
