# Generated by Django 6.0.2 on 2026-02-25 05:23

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='submissionevent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='submissionevent',
            name='modified',
        ),
        migrations.AddField(
            model_name='submission',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='submission',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='survey',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='surveyevent',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "started", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."id", NEW."mode", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."respondent_id", NEW."started", NEW."survey_id"); RETURN NULL;', hash='994783c4693b6fcb8288760aadb9d3cb6a148c8a', operation='INSERT', pgid='pgtrigger_insert_insert_ebca0', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "started", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."id", NEW."mode", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."respondent_id", NEW."started", NEW."survey_id"); RETURN NULL;', hash='d773d7c6d9033665cf3f111104f9fc97481c556c', operation='UPDATE', pgid='pgtrigger_update_update_d6efc', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "started", "survey_id") VALUES (OLD."active", OLD."answers", OLD."context", OLD."id", OLD."mode", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."respondent_id", OLD."started", OLD."survey_id"); RETURN NULL;', hash='e38565e0b5e22fd144cba1f30438a49c20bb0f56', operation='DELETE', pgid='pgtrigger_delete_delete_fa339', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='66b93365d3e4dfad976fc854256990d120a29ee6', operation='INSERT', pgid='pgtrigger_insert_insert_69de8', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."anonymous" IS DISTINCT FROM (NEW."anonymous") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."complete_message" IS DISTINCT FROM (NEW."complete_message") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."show_results" IS DISTINCT FROM (NEW."show_results") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='9765e2d59ac04d380cf132094cb23d549cea4490', operation='UPDATE', pgid='pgtrigger_update_update_76063', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (OLD."anonymous", OLD."audience", OLD."complete_message", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."show_results", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='95898b40ee3f5ff1d9fc223ba9ccb3c1f4c34b26', operation='DELETE', pgid='pgtrigger_delete_delete_3408b', table='survey_survey', when='AFTER')),
        ),
    ]
