# Generated by Django 6.0.2 on 2026-03-03 12:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='published',
        ),
        migrations.RemoveField(
            model_name='surveyevent',
            name='published',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='cf049c97c09d55b435d07a2b8fcb97aa5c07abdf', operation='INSERT', pgid='pgtrigger_insert_insert_69de8', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."anonymous" IS DISTINCT FROM (NEW."anonymous") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."complete_message" IS DISTINCT FROM (NEW."complete_message") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."show_results" IS DISTINCT FROM (NEW."show_results") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_pool_id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='d26a6b2ad7958e8c48103888e80f5caa7745b7a0', operation='UPDATE', pgid='pgtrigger_update_update_76063', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "show_results", "thumbnail", "title", "verification_required") VALUES (OLD."anonymous", OLD."audience", OLD."complete_message", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_pool_id", OLD."show_results", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='2a13eddd2f5050ffada4d3156be445e992e67ed2', operation='DELETE', pgid='pgtrigger_delete_delete_3408b', table='survey_survey', when='AFTER')),
        ),
    ]
