# Generated by Django 6.0.1 on 2026-01-14 12:49

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='submission',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='survey',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='survey_submission_su_re_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='survey_submission_su_haem_uniq',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='survey_subm_hashed__762554_idx',
        ),
        migrations.RemoveField(
            model_name='submissionevent',
            name='hashed_email',
        ),
        migrations.AddField(
            model_name='submission',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key'),
        ),
        migrations.AddField(
            model_name='survey',
            name='show_results',
            field=models.BooleanField(default=False, verbose_name='Show Results'),
        ),
        migrations.AddField(
            model_name='surveyevent',
            name='show_results',
            field=models.BooleanField(default=False, verbose_name='Show Results'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='', verbose_name='Thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyevent',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='', verbose_name='Thumbnail'),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='fb6452cbb3d1aa9db4ef53a62f1270494387eee1', operation='INSERT', pgid='pgtrigger_insert_insert_ebca0', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."respondent_id" IS DISTINCT FROM (NEW."respondent_id") OR OLD."survey_id" IS DISTINCT FROM (NEW."survey_id"))', func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (NEW."active", NEW."answers", NEW."context", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."respondent_id", NEW."survey_id"); RETURN NULL;', hash='df81725ebc81e5c1babeffc37a9679597ebbf435', operation='UPDATE', pgid='pgtrigger_update_update_d6efc', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_submissionevent" ("active", "answers", "context", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "respondent_id", "survey_id") VALUES (OLD."active", OLD."answers", OLD."context", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."respondent_id", OLD."survey_id"); RETURN NULL;', hash='3362fcb2b71555f84a98337b039e412024fceeeb', operation='DELETE', pgid='pgtrigger_delete_delete_fa339', table='survey_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."likert_options", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."paper_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='4ce9cc6304515afb78dc3838611386ea4d9dd685', operation='INSERT', pgid='pgtrigger_insert_insert_69de8', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."anonymous" IS DISTINCT FROM (NEW."anonymous") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."complete_message" IS DISTINCT FROM (NEW."complete_message") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."likert_options" IS DISTINCT FROM (NEW."likert_options") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."paper_id" IS DISTINCT FROM (NEW."paper_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."show_results" IS DISTINCT FROM (NEW."show_results") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_results", "thumbnail", "title", "verification_required") VALUES (NEW."anonymous", NEW."audience", NEW."complete_message", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."likert_options", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."paper_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."show_results", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='21d69246376e73929597a93f2a1b429bb397285b', operation='UPDATE', pgid='pgtrigger_update_update_76063', table='survey_survey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='survey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "survey_surveyevent" ("anonymous", "audience", "complete_message", "created", "description", "duration", "featured", "format", "id", "likert_options", "max_attempts", "modified", "owner_id", "paper_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_results", "thumbnail", "title", "verification_required") VALUES (OLD."anonymous", OLD."audience", OLD."complete_message", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."likert_options", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."paper_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."show_results", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='6d443aa67e353994f5dbd36a9c28b87f7f33d133', operation='DELETE', pgid='pgtrigger_delete_delete_3408b', table='survey_survey', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('respondent__isnull', False)), fields=('survey', 'respondent', 'context'), name='survey_submission_su_re_co_uniq'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='hashed_email',
        ),
    ]
