# Generated by Django 6.0.1 on 2026-01-11 01:21

import apps.common.models
import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('point', models.PositiveSmallIntegerField(verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Performance Level',
                'verbose_name_plural': 'Performance Levels',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('attachment_file_count', models.PositiveSmallIntegerField(default=1, verbose_name='Attachment File Count')),
                ('attachment_file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, verbose_name='Attachment File Types')),
                ('sample_attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sample Attachment')),
                ('plagiarism_threshold', models.PositiveSmallIntegerField(verbose_name='Plagiarism Threshold Percentage')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Reference')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='SolutionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Reference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Extracted Text')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Extracted Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('honor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='Assignment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceLevelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('point', models.PositiveSmallIntegerField(verbose_name='Point')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.performancelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('not_detected', 'Not Detected'), ('detected', 'Detected'), ('excused', 'Excused'), ('not_resolved', 'Not Resolved')], db_index=True, max_length=20, verbose_name='Status')),
                ('similarity_percentage', models.FloatField(verbose_name='Similarity Percentage')),
                ('flagged_text', models.TextField(verbose_name='Flagged Text')),
                ('source_text', models.TextField(verbose_name='Source Text')),
                ('source_user_id', models.CharField(max_length=36, verbose_name='Source User ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Plagiarism Check',
                'verbose_name_plural': 'Plagiarism Checks',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlagiarismCheckEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('not_detected', 'Not Detected'), ('detected', 'Detected'), ('excused', 'Excused'), ('not_resolved', 'Not Resolved')], max_length=20, verbose_name='Status')),
                ('similarity_percentage', models.FloatField(verbose_name='Similarity Percentage')),
                ('flagged_text', models.TextField(verbose_name='Flagged Text')),
                ('source_text', models.TextField(verbose_name='Source Text')),
                ('source_user_id', models.CharField(max_length=36, verbose_name='Source User ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.attempt', verbose_name='Attempt')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.plagiarismcheck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('assignment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.assignment', verbose_name='Assignment')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.attempt')),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.question', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('attachment_file_count', models.PositiveSmallIntegerField(default=1, verbose_name='Attachment File Count')),
                ('attachment_file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, verbose_name='Attachment File Types')),
                ('sample_attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sample Attachment')),
                ('plagiarism_threshold', models.PositiveSmallIntegerField(verbose_name='Plagiarism Threshold Percentage')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.question')),
                ('pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='AssignmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('honor_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.assignment')),
                ('question_pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='question_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='QuestionPoolEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.questionpool')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubric',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_rubricevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d27df3b6be63689583c758bcd93a885bcfa2cf35', operation='INSERT', pgid='pgtrigger_insert_insert_66c38', table='assignment_rubric', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubric',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_rubricevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='cdc60edf00c4655eacb014cc217764a940cdd9ff', operation='UPDATE', pgid='pgtrigger_update_update_f0a7b', table='assignment_rubric', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubric',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_rubricevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='f216c97dab4260cb6f65c52954a6bc21cf2ab72e', operation='DELETE', pgid='pgtrigger_delete_delete_9409f', table='assignment_rubric', when='AFTER')),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.rubric', verbose_name='Rubric'),
        ),
        migrations.AddField(
            model_name='performancelevelevent',
            name='criterion',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.rubriccriterion', verbose_name='Criterion'),
        ),
        migrations.AddField(
            model_name='performancelevel',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.rubriccriterion', verbose_name='Criterion'),
        ),
        migrations.AddField(
            model_name='rubriccriterionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='rubriccriterionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='rubriccriterionevent',
            name='rubric',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.rubric', verbose_name='Rubric'),
        ),
        migrations.AddField(
            model_name='rubricevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='rubricevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.rubric'),
        ),
        migrations.AddField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='solution',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.rubric', verbose_name='Rubric'),
        ),
        migrations.AddField(
            model_name='solutionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='solutionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.solution'),
        ),
        migrations.AddField(
            model_name='solutionevent',
            name='question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='solutionevent',
            name='rubric',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.rubric', verbose_name='Rubric'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.attempt', verbose_name='Attempt'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='attempt',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.attempt', verbose_name='Attempt'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='assignment.submission'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='58a31d7f27fe1833fa1dd0aa5319afd3b698fae1', operation='INSERT', pgid='pgtrigger_insert_insert_6a1f3', table='assignment_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."completed" IS DISTINCT FROM (NEW."completed") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."earned_details" IS DISTINCT FROM (NEW."earned_details") OR OLD."earned_point" IS DISTINCT FROM (NEW."earned_point") OR OLD."feedback" IS DISTINCT FROM (NEW."feedback") OR OLD."grader_id" IS DISTINCT FROM (NEW."grader_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."possible_point" IS DISTINCT FROM (NEW."possible_point") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "assignment_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='775b6592de68c11e1b5e83bc3e85c16ebe7b946e', operation='UPDATE', pgid='pgtrigger_update_update_17cd7', table='assignment_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (OLD."attempt_id", OLD."completed", OLD."confirmed", OLD."created", OLD."earned_details", OLD."earned_point", OLD."feedback", OLD."grader_id", OLD."id", OLD."modified", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."possible_point", OLD."score"); RETURN NULL;', hash='653857207784fa1595d9209805d5bcf9b2d317d4', operation='DELETE', pgid='pgtrigger_delete_delete_827ec', table='assignment_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4522377fa64784cde80f05d04d67f4f31fb41425', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_cc37c', table='assignment_gradeevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plagiarismcheck',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_plagiarismcheckevent" ("attempt_id", "created", "flagged_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "similarity_percentage", "source_text", "source_user_id", "status") VALUES (NEW."attempt_id", NEW."created", NEW."flagged_text", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."similarity_percentage", NEW."source_text", NEW."source_user_id", NEW."status"); RETURN NULL;', hash='710269a92b61990a0b5d1633ba14c1794c784781', operation='INSERT', pgid='pgtrigger_insert_insert_a4d26', table='assignment_plagiarismcheck', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plagiarismcheck',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."flagged_text" IS DISTINCT FROM (NEW."flagged_text") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."reason" IS DISTINCT FROM (NEW."reason") OR OLD."similarity_percentage" IS DISTINCT FROM (NEW."similarity_percentage") OR OLD."source_text" IS DISTINCT FROM (NEW."source_text") OR OLD."source_user_id" IS DISTINCT FROM (NEW."source_user_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "assignment_plagiarismcheckevent" ("attempt_id", "created", "flagged_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "similarity_percentage", "source_text", "source_user_id", "status") VALUES (NEW."attempt_id", NEW."created", NEW."flagged_text", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."similarity_percentage", NEW."source_text", NEW."source_user_id", NEW."status"); RETURN NULL;', hash='b7ae24d215687748a20551cd94d0e426411ed5b8', operation='UPDATE', pgid='pgtrigger_update_update_0d600', table='assignment_plagiarismcheck', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plagiarismcheck',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_plagiarismcheckevent" ("attempt_id", "created", "flagged_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "similarity_percentage", "source_text", "source_user_id", "status") VALUES (OLD."attempt_id", OLD."created", OLD."flagged_text", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason", OLD."similarity_percentage", OLD."source_text", OLD."source_user_id", OLD."status"); RETURN NULL;', hash='58a5297387b3499acac16285bedde56977174c65', operation='DELETE', pgid='pgtrigger_delete_delete_fe7d6', table='assignment_plagiarismcheck', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plagiarismcheckevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9a4d44e7f7eceaebd73f9eb30f19ef7e9c01a3de', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_8ee15', table='assignment_plagiarismcheckevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attemptevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='803f24308a69a5d6d4b7c7faa63b4e136b61b2e0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d00d0', table='assignment_attemptevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['learner_id', 'active'], name='assignment__learner_416448_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('assignment', 'learner', 'context'), name='assignment_attempt_as_le_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "started") VALUES (NEW."active", NEW."assignment_id", NEW."context", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."started"); RETURN NULL;', hash='8ab2a2faea3581799239b78386b8412b83d9168a', operation='INSERT', pgid='pgtrigger_insert_insert_0e484', table='assignment_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "started") VALUES (NEW."active", NEW."assignment_id", NEW."context", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."started"); RETURN NULL;', hash='9047dfb040186af21c0d31e845a222915d7f7721', operation='UPDATE', pgid='pgtrigger_update_update_a72bb', table='assignment_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "started") VALUES (OLD."active", OLD."assignment_id", OLD."context", OLD."id", OLD."learner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."started"); RETURN NULL;', hash='3241d6e487bc02350e4ec1bc1c586ca81353bde7', operation='DELETE', pgid='pgtrigger_delete_delete_49776', table='assignment_attempt', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='assignment_questionpool_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='567bb9be54d616726070619fae0735c5f5def71e', operation='INSERT', pgid='pgtrigger_insert_insert_39920', table='assignment_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='132bc0ee3f645bea7b667656fa07789a5d0d6774', operation='UPDATE', pgid='pgtrigger_update_update_f24b2', table='assignment_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='fbe722e15c9b2b38f2214a45be2311f1ac005ead', operation='DELETE', pgid='pgtrigger_delete_delete_8337f', table='assignment_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='84a5dd230f048acc389c1911316490814a1ead14', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_35ed4', table='assignment_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "sample_attachment", "supplement") VALUES (NEW."attachment_file_count", NEW."attachment_file_types", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plagiarism_threshold", NEW."pool_id", NEW."question", NEW."sample_attachment", NEW."supplement"); RETURN NULL;', hash='264356de2d836c6c58d3c92712043cde6af008a5', operation='INSERT', pgid='pgtrigger_insert_insert_ec4a4', table='assignment_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "sample_attachment", "supplement") VALUES (NEW."attachment_file_count", NEW."attachment_file_types", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plagiarism_threshold", NEW."pool_id", NEW."question", NEW."sample_attachment", NEW."supplement"); RETURN NULL;', hash='ee2a4bed5b1fb8a491a91223ffb55c797c01fe4d', operation='UPDATE', pgid='pgtrigger_update_update_6ef6c', table='assignment_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "sample_attachment", "supplement") VALUES (OLD."attachment_file_count", OLD."attachment_file_types", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plagiarism_threshold", OLD."pool_id", OLD."question", OLD."sample_attachment", OLD."supplement"); RETURN NULL;', hash='d057a810f491c52d085c4d84bb5b211851b8da19', operation='DELETE', pgid='pgtrigger_delete_delete_dc36d', table='assignment_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e4132665eb66c628449af58e386cc304fe6c91cd', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b43b7', table='assignment_assignmentevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='assignment_assignment_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='fb53e6fd7f6e48244ad68fc0acb91b1ee6d995eb', operation='INSERT', pgid='pgtrigger_insert_insert_e3a8d', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='4a7ea5378235d3cc8ac57edbcd9dcb2c499906d4', operation='UPDATE', pgid='pgtrigger_update_update_629e4', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='a664227325ec3bff43b642bedc46c55314d73b8b', operation='DELETE', pgid='pgtrigger_delete_delete_1054f', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpoolevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='504060dafa7151ff525a8edd59b4af31a8611c7d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ef48c', table='assignment_questionpoolevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='assigment_rubriccriterion_ru_na_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubriccriterion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_rubriccriterionevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rubric_id") VALUES (NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rubric_id"); RETURN NULL;', hash='3fe11db339a068f9e2054fcac71324cd3e26c7a9', operation='INSERT', pgid='pgtrigger_insert_insert_b7607', table='assignment_rubriccriterion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubriccriterion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_rubriccriterionevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rubric_id") VALUES (NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rubric_id"); RETURN NULL;', hash='8d220772323ee686468b3ec64fc61aa73a70d5a1', operation='UPDATE', pgid='pgtrigger_update_update_c41ae', table='assignment_rubriccriterion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubriccriterion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_rubriccriterionevent" ("description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rubric_id") VALUES (OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rubric_id"); RETURN NULL;', hash='f9705245e222275733c26351f29806de467fe7e7', operation='DELETE', pgid='pgtrigger_delete_delete_f4f0a', table='assignment_rubriccriterion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performancelevelevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='37fb8569ad09ac5316ea92acd78d964d0ffce754', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7c88c', table='assignment_performancelevelevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='performancelevel',
            constraint=models.UniqueConstraint(fields=('criterion', 'name'), name='assignment_performancelevel_cr_na_uniq'),
        ),
        migrations.AddConstraint(
            model_name='performancelevel',
            constraint=models.UniqueConstraint(fields=('criterion', 'point'), name='assignment_performancelevel_cr_po_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performancelevel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_performancelevelevent" ("criterion_id", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point") VALUES (NEW."criterion_id", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point"); RETURN NULL;', hash='3ce3ddb0f08d07b8667cb386e79009c8d7c62b5a', operation='INSERT', pgid='pgtrigger_insert_insert_1c627', table='assignment_performancelevel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performancelevel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_performancelevelevent" ("criterion_id", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point") VALUES (NEW."criterion_id", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point"); RETURN NULL;', hash='b896a63ab1a98bfed68f41270254b3757275b5f1', operation='UPDATE', pgid='pgtrigger_update_update_9ee31', table='assignment_performancelevel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performancelevel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_performancelevelevent" ("criterion_id", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point") VALUES (OLD."criterion_id", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point"); RETURN NULL;', hash='c76c3114aeb5a3e9821c926eed44cc07f33b556b', operation='DELETE', pgid='pgtrigger_delete_delete_967f1', table='assignment_performancelevel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubriccriterionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='23f1a3502fde805476777334388bac9e4522b6a9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f664d', table='assignment_rubriccriterionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rubricevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f10fef20e08264b0188f59a66fcb147eedd24822', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_76901', table='assignment_rubricevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_solutionevent" ("explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference", "rubric_id") VALUES (NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."reference", NEW."rubric_id"); RETURN NULL;', hash='3a442a6ae199c25e0babee95239392eeefdb2884', operation='INSERT', pgid='pgtrigger_insert_insert_1c170', table='assignment_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_solutionevent" ("explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference", "rubric_id") VALUES (NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."reference", NEW."rubric_id"); RETURN NULL;', hash='6f1127e427dcf09bb870a5f9de17e6abece3686e', operation='UPDATE', pgid='pgtrigger_update_update_aeb29', table='assignment_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_solutionevent" ("explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference", "rubric_id") VALUES (OLD."explanation", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."reference", OLD."rubric_id"); RETURN NULL;', hash='8fe922b42142e14296ea9b277ce844b6504bf95a', operation='DELETE', pgid='pgtrigger_delete_delete_e1f79', table='assignment_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solutionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bc3b6a7f3f384814ef83dba2b43b8081df477fd4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_09dc1', table='assignment_solutionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_submissionevent" ("answer", "attempt_id", "created", "extracted_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answer", NEW."attempt_id", NEW."created", NEW."extracted_text", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='c0813c5d90a6e945fd50db3c583d9e293a65c25d', operation='INSERT', pgid='pgtrigger_insert_insert_3d5fe', table='assignment_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."answer" IS DISTINCT FROM (NEW."answer") OR OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."extracted_text" IS DISTINCT FROM (NEW."extracted_text") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "assignment_submissionevent" ("answer", "attempt_id", "created", "extracted_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answer", NEW."attempt_id", NEW."created", NEW."extracted_text", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='6bdabe716af1b8a232d4e846ec83babb1d410e30', operation='UPDATE', pgid='pgtrigger_update_update_aca16', table='assignment_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_submissionevent" ("answer", "attempt_id", "created", "extracted_text", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."answer", OLD."attempt_id", OLD."created", OLD."extracted_text", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='60dd0e2bdc9c8f2fb35153342a69052c37d8229d', operation='DELETE', pgid='pgtrigger_delete_delete_f04d9', table='assignment_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dd031294d1e4bd7cdd5682c3f702124c660d9015', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e57c1', table='assignment_submissionevent', when='BEFORE')),
        ),
    ]
