# Generated by Django 6.0.1 on 2026-01-19 17:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."assignment_id", NEW."context", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='c04907a097d685ee6684ace60c68dd2b8d5933da', operation='INSERT', pgid='pgtrigger_insert_insert_0e484', table='assignment_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."assignment_id", NEW."context", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='9c2e52b9eb196119443537081ffb2c365bc5eac1', operation='UPDATE', pgid='pgtrigger_update_update_a72bb', table='assignment_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_attemptevent" ("active", "assignment_id", "context", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (OLD."active", OLD."assignment_id", OLD."context", OLD."id", OLD."learner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."retry", OLD."started"); RETURN NULL;', hash='548df147d898cd8fa8d99278a9a391dfbb9f1a97', operation='DELETE', pgid='pgtrigger_delete_delete_49776', table='assignment_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='assignment_attempt_retry_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                SELECT COALESCE(MAX(retry), -1) + 1\n                INTO NEW.retry\n                FROM assignment_attempt\n                WHERE assignment_id = NEW.assignment_id \n                  AND learner_id = NEW.learner_id \n                  AND context = NEW.context;\n                RETURN NEW;\n            END;\n        ', hash='96bc17a484a6d13d67b5b4f96e434f36eec8987c', operation='INSERT', pgid='pgtrigger_assignment_attempt_retry_count_dc701', table='assignment_attempt', when='BEFORE')),
        ),
    ]
