# Generated by Django 6.0.3 on 2026-03-06 09:25

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_assignment_insert_insert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='question',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='solutionevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='solutionevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='solutionevent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='solutionevent',
            name='rubric',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment.rubric', verbose_name='Rubric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentevent',
            name='rubric',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='assignment.rubric', verbose_name='Rubric'),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."rubric_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='1cd6f2ed24dcbe90b52e9632cc7b10b27259160e', operation='INSERT', pgid='pgtrigger_insert_insert_e3a8d', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."rubric_id" IS DISTINCT FROM (NEW."rubric_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."rubric_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='9303206dde629794b00824d3a5367925f1fdd159', operation='UPDATE', pgid='pgtrigger_update_update_629e4', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."rubric_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='da98a79a403fb93d0acea3abcf35aa374ae18916', operation='DELETE', pgid='pgtrigger_delete_delete_1054f', table='assignment_assignment', when='AFTER')),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='SolutionEvent',
        ),
    ]
