# Generated by Django 6.0.3 on 2026-03-06 10:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_remove_solution_question_remove_solution_rubric_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assignment',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='question',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='question',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='question',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sample_attachment',
        ),
        migrations.RemoveField(
            model_name='questionevent',
            name='sample_attachment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='sample_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Sample Attachment'),
        ),
        migrations.AddField(
            model_name='assignmentevent',
            name='sample_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Sample Attachment'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "sample_attachment", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."rubric_id", NEW."sample_attachment", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='21ac5a1dbcdaca2a2780136fbf794154a596c62c', operation='INSERT', pgid='pgtrigger_insert_insert_e3a8d', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."rubric_id" IS DISTINCT FROM (NEW."rubric_id") OR OLD."sample_attachment" IS DISTINCT FROM (NEW."sample_attachment") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "sample_attachment", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."rubric_id", NEW."sample_attachment", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='31e50859d395027d1fe45fdebb78d526da55e3b8', operation='UPDATE', pgid='pgtrigger_update_update_629e4', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assignment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_assignmentevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "rubric_id", "sample_attachment", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."rubric_id", OLD."sample_attachment", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='bd3967fe3520f4bc3eb34aa5628ee090a3020e92', operation='DELETE', pgid='pgtrigger_delete_delete_1054f', table='assignment_assignment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "supplement") VALUES (NEW."attachment_file_count", NEW."attachment_file_types", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plagiarism_threshold", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='ac65eeb67c670d74ad31e29e2cdec60661b4dedf', operation='INSERT', pgid='pgtrigger_insert_insert_ec4a4', table='assignment_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "supplement") VALUES (NEW."attachment_file_count", NEW."attachment_file_types", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plagiarism_threshold", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='eff17638cb2cc8f38a72a5929750b25e7ab7272f', operation='UPDATE', pgid='pgtrigger_update_update_6ef6c', table='assignment_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "assignment_questionevent" ("attachment_file_count", "attachment_file_types", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plagiarism_threshold", "pool_id", "question", "supplement") VALUES (OLD."attachment_file_count", OLD."attachment_file_types", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plagiarism_threshold", OLD."pool_id", OLD."question", OLD."supplement"); RETURN NULL;', hash='3ec3e58da7ff73b07683a37d8a7c7348328ba765', operation='DELETE', pgid='pgtrigger_delete_delete_dc36d', table='assignment_question', when='AFTER')),
        ),
    ]
