# Generated by Django 6.0.1 on 2026-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Execution Duration (seconds)')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('active_account_count', models.IntegerField(default=0, verbose_name='Total Account')),
                ('active_enrollment_count', models.IntegerField(default=0, verbose_name='Total Enrollment')),
                ('course_passed_count', models.IntegerField(default=0, verbose_name='Course Passed')),
            ],
            options={
                'verbose_name': 'Daily Snapshot',
                'verbose_name_plural': 'Daily Snapshots',
            },
        ),
        migrations.CreateModel(
            name='DailyUsageFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Execution Duration (seconds)')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('registration_count', models.IntegerField(default=0, verbose_name='Registration')),
                ('login_count', models.IntegerField(default=0, verbose_name='Login')),
                ('attachment_count', models.IntegerField(default=0, verbose_name='Attachment')),
                ('inquiry_count', models.IntegerField(default=0, verbose_name='Inquiry')),
                ('appeal_count', models.IntegerField(default=0, verbose_name='Appeal')),
                ('message_sent_count', models.IntegerField(default=0, verbose_name='Message Sent')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment')),
                ('partner_count', models.IntegerField(default=0, verbose_name='Partner')),
                ('partner_employee_count', models.IntegerField(default=0, verbose_name='Partner Employee')),
                ('cohort_count', models.IntegerField(default=0, verbose_name='Cohort')),
                ('competency_goal_count', models.IntegerField(default=0, verbose_name='Competency Goal')),
                ('badge_award_count', models.IntegerField(default=0, verbose_name='Badge Award')),
                ('certificate_award_count', models.IntegerField(default=0, verbose_name='Certificate Award')),
                ('media_count', models.IntegerField(default=0, verbose_name='Media')),
                ('public_access_media_count', models.IntegerField(default=0, verbose_name='Public Access Media')),
                ('watch_count', models.IntegerField(default=0, verbose_name='Watch')),
                ('survey_count', models.IntegerField(default=0, verbose_name='Survey')),
                ('survey_submission_count', models.IntegerField(default=0, verbose_name='Survey Submission')),
                ('quiz_count', models.IntegerField(default=0, verbose_name='Quiz')),
                ('quiz_submission_count', models.IntegerField(default=0, verbose_name='Quiz Submission')),
                ('exam_count', models.IntegerField(default=0, verbose_name='Exam')),
                ('exam_submission_count', models.IntegerField(default=0, verbose_name='Exam Submission')),
                ('exam_grade_completed_count', models.IntegerField(default=0, verbose_name='Exam Grade Completed')),
                ('exam_grade_confirmed_count', models.IntegerField(default=0, verbose_name='Exam Grade Confirmed')),
                ('assignment_count', models.IntegerField(default=0, verbose_name='Assignment')),
                ('assignment_submission_count', models.IntegerField(default=0, verbose_name='Assignment Submission')),
                ('assignment_grade_completed_count', models.IntegerField(default=0, verbose_name='Assignment Grade Completed')),
                ('assignment_grade_confirmed_count', models.IntegerField(default=0, verbose_name='Assignment Grade Confirmed')),
                ('discussion_count', models.IntegerField(default=0, verbose_name='Discussion')),
                ('discussion_post_count', models.IntegerField(default=0, verbose_name='Discussion Post')),
                ('discussion_grade_completed_count', models.IntegerField(default=0, verbose_name='Discussion Grade Completed')),
                ('discussion_grade_confirmed_count', models.IntegerField(default=0, verbose_name='Discussion Grade Confirmed')),
                ('course_count', models.IntegerField(default=0, verbose_name='Course')),
                ('course_engagement_count', models.IntegerField(default=0, verbose_name='Course Engagement')),
                ('course_grade_confirmed_count', models.IntegerField(default=0, verbose_name='Course Grade Confirmed')),
                ('enrollment_count', models.IntegerField(default=0, verbose_name='Enrollment')),
                ('catalog_count', models.IntegerField(default=0, verbose_name='Catalog')),
                ('user_catalog_count', models.IntegerField(default=0, verbose_name='User Catalog')),
                ('cohort_catalog_count', models.IntegerField(default=0, verbose_name='Cohort Catalog')),
                ('product_count', models.IntegerField(default=0, verbose_name='Product')),
                ('coupon_count', models.IntegerField(default=0, verbose_name='Coupon')),
                ('order_count', models.IntegerField(default=0, verbose_name='Order')),
                ('payment_count', models.IntegerField(default=0, verbose_name='Payment')),
                ('refund_count', models.IntegerField(default=0, verbose_name='Refund')),
                ('assistant_chat_message_count', models.IntegerField(default=0, verbose_name='Assistant Chat Message')),
            ],
            options={
                'verbose_name': 'Daily Usage Fact',
                'verbose_name_plural': 'Daily Usage Facts',
            },
        ),
    ]
