# Generated by Django 6.0.1 on 2026-01-11 01:20

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('business_number', models.CharField(max_length=50, unique=True, verbose_name='Business Number')),
            ],
            options={
                'verbose_name': 'Business Site',
                'verbose_name_plural': 'Business Sites',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.cohort', verbose_name='Cohort')),
            ],
            options={
                'verbose_name': 'Cohort Employee',
                'verbose_name_plural': 'Cohort Employees',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('education_manager', 'Education Manager'), ('marketing_manager', 'Marketing Manager'), ('financial_manager', 'Financial Manager')], max_length=30, verbose_name='Role')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.cohort', verbose_name='Cohort')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cohort Staff',
                'verbose_name_plural': 'Cohort Staffs',
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='staffs',
            field=models.ManyToManyField(blank=True, through='partner.CohortStaff', to=settings.AUTH_USER_MODEL, verbose_name='Staffs'),
        ),
        migrations.CreateModel(
            name='CohortStaffEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('education_manager', 'Education Manager'), ('marketing_manager', 'Marketing Manager'), ('financial_manager', 'Financial Manager')], max_length=30, verbose_name='Role')),
                ('cohort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.cohort', verbose_name='Cohort')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohortstaff')),
                ('staff', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('encrypted_id_number', models.CharField(blank=True, max_length=255, verbose_name='ID Number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone')),
                ('team', models.CharField(blank=True, default='', max_length=50, verbose_name='Team')),
                ('job_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Position')),
                ('job_title', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Title')),
                ('employment_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Status')),
                ('employment_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Type')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.businesssite', verbose_name='Business Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortEmployeeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('cohort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.cohort', verbose_name='Cohort')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohortemployee')),
                ('employee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohortemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='employees',
            field=models.ManyToManyField(to='partner.employee', verbose_name='Employees'),
        ),
        migrations.CreateModel(
            name='EmployeeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('encrypted_id_number', models.CharField(blank=True, max_length=255, verbose_name='ID Number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone')),
                ('team', models.CharField(blank=True, default='', max_length=50, verbose_name='Team')),
                ('job_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Position')),
                ('job_title', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Title')),
                ('employment_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Status')),
                ('employment_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Type')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.employee')),
                ('site', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.businesssite', verbose_name='Business Site')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'abstract': False,
                'indexes': [models.Index(fields=['email'], name='partner_par_email_761118_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessSiteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('business_number', models.CharField(max_length=50, verbose_name='Business Number')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.businesssite')),
                ('partner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='businesssite',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Partner'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (NEW."address", NEW."created", NEW."description", NEW."email", NEW."id", NEW."logo", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."website"); RETURN NULL;', hash='0104aebe8a2aae8b2703d2831b29aa34f83c96a8', operation='INSERT', pgid='pgtrigger_insert_insert_b4de1', table='partner_partner', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."address" IS DISTINCT FROM (NEW."address") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."logo" IS DISTINCT FROM (NEW."logo") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."website" IS DISTINCT FROM (NEW."website"))', func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (NEW."address", NEW."created", NEW."description", NEW."email", NEW."id", NEW."logo", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."website"); RETURN NULL;', hash='0a6a0ff3c3a7f461b5b1259dace852f4679b7c60', operation='UPDATE', pgid='pgtrigger_update_update_240cd', table='partner_partner', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (OLD."address", OLD."created", OLD."description", OLD."email", OLD."id", OLD."logo", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."website"); RETURN NULL;', hash='40b59d4ae98810f8237de4075b598636fab239a6', operation='DELETE', pgid='pgtrigger_delete_delete_97aaa', table='partner_partner', when='AFTER')),
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.partner'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='387b71be8bd620939f5be44467867fec0fb1ba18', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_24640', table='partner_cohortevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cohortstaff',
            constraint=models.UniqueConstraint(fields=('cohort', 'staff'), name='partner_cohortstaff_co_sta_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (NEW."cohort_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."staff_id"); RETURN NULL;', hash='3cbc455a3c817948320966e83629fef897f56225', operation='INSERT', pgid='pgtrigger_insert_insert_d966a', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (NEW."cohort_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."staff_id"); RETURN NULL;', hash='c6736cf63cb9b2ac63242c84f2a3e83966194063', operation='UPDATE', pgid='pgtrigger_update_update_3029a', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (OLD."cohort_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."staff_id"); RETURN NULL;', hash='d0570936caada9c3c24af9c3e1a63b090fd6b538', operation='DELETE', pgid='pgtrigger_delete_delete_fb4fd', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaffevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='13b47ca7837bf923dc09d1154e068b90e006bd78', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_49a16', table='partner_cohortstaffevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='partner_emp_name_edba4b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='partner_emp_email_627ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='partner_emp_phone_7d9b57_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['team'], name='partner_emp_team_762b9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('site', 'email'), name='partner_employee_si_em_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employee',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_employeeevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "site_id", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_id_number", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."site_id", NEW."team", NEW."user_id"); RETURN NULL;', hash='bc7b3dd92ea81cae93486e952493af392191106a', operation='INSERT', pgid='pgtrigger_insert_insert_452cc', table='partner_employee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employee',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."birth_date" IS DISTINCT FROM (NEW."birth_date") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."employment_status" IS DISTINCT FROM (NEW."employment_status") OR OLD."employment_type" IS DISTINCT FROM (NEW."employment_type") OR OLD."encrypted_id_number" IS DISTINCT FROM (NEW."encrypted_id_number") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."job_position" IS DISTINCT FROM (NEW."job_position") OR OLD."job_title" IS DISTINCT FROM (NEW."job_title") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."site_id" IS DISTINCT FROM (NEW."site_id") OR OLD."team" IS DISTINCT FROM (NEW."team") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "partner_employeeevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "site_id", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_id_number", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."site_id", NEW."team", NEW."user_id"); RETURN NULL;', hash='ca2266c32274b97629f279204eb649b54f986618', operation='UPDATE', pgid='pgtrigger_update_update_de891', table='partner_employee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employee',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_employeeevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "site_id", "team", "user_id") VALUES (OLD."birth_date", OLD."created", OLD."email", OLD."employment_status", OLD."employment_type", OLD."encrypted_id_number", OLD."id", OLD."job_position", OLD."job_title", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."site_id", OLD."team", OLD."user_id"); RETURN NULL;', hash='411cbf98ecff71dfe5716dc68263fc84dc2940a8', operation='DELETE', pgid='pgtrigger_delete_delete_4c53d', table='partner_employee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortemployeeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='da98dc7522eb930f91f92a09cab0d21e91ad3a5c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_052f0', table='partner_cohortemployeeevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cohortemployee',
            constraint=models.UniqueConstraint(fields=('cohort', 'employee'), name='partner_cohortemployee_co_em_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortemployee',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortemployeeevent" ("cohort_id", "created", "employee_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cohort_id", NEW."created", NEW."employee_id", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='150fbfb9973b38084be65f534775acb221616c06', operation='INSERT', pgid='pgtrigger_insert_insert_bdec3', table='partner_cohortemployee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortemployee',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."cohort_id" IS DISTINCT FROM (NEW."cohort_id") OR OLD."employee_id" IS DISTINCT FROM (NEW."employee_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "partner_cohortemployeeevent" ("cohort_id", "created", "employee_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cohort_id", NEW."created", NEW."employee_id", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='aec991e468097e2d0e8de3bfe773d46d613add57', operation='UPDATE', pgid='pgtrigger_update_update_1221c', table='partner_cohortemployee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortemployee',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortemployeeevent" ("cohort_id", "created", "employee_id", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cohort_id", OLD."created", OLD."employee_id", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='be34b49ad5799b335ea6a45c625fb95c2e7ae14b', operation='DELETE', pgid='pgtrigger_delete_delete_7aecb', table='partner_cohortemployee', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d833840e7b89278806574a8ed3dbed2923131eaf', operation='INSERT', pgid='pgtrigger_insert_insert_e8fd5', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name"))', func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c80997aa6ce01d03a8d84548f429a0a79c0c8ebd', operation='UPDATE', pgid='pgtrigger_update_update_965e8', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='5e43e6c396f824b33551bb93cd2ba6657e008e8f', operation='DELETE', pgid='pgtrigger_delete_delete_ee772', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employeeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c3ee468f1c3e6f3f4b112983ab78d5a7486226e9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_5a060', table='partner_employeeevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='businesssiteevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='65b3989bead21c8aeda1db935e335de78dad5b3b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_becd0', table='partner_businesssiteevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='businesssite',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='partner_business_pa_na_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='businesssite',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_businesssiteevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."business_number", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."partner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='ade8e77fc2d0dec7240420e6ac168dd512358571', operation='INSERT', pgid='pgtrigger_insert_insert_6c84c', table='partner_businesssite', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='businesssite',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."business_number" IS DISTINCT FROM (NEW."business_number") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."partner_id" IS DISTINCT FROM (NEW."partner_id"))', func='INSERT INTO "partner_businesssiteevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."business_number", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."partner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='dd87110c25cc338b2901e6780ad5def26840e4f4', operation='UPDATE', pgid='pgtrigger_update_update_af9cc', table='partner_businesssite', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='businesssite',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_businesssiteevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."business_number", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", OLD."partner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='aff0a4cc15eb1238ca5a135479f070809f57aec1', operation='DELETE', pgid='pgtrigger_delete_delete_661f4', table='partner_businesssite', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partnerevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='56c6830b5148f30963ee99b53a38c8813212bcdc', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4d8b2', table='partner_partnerevent', when='BEFORE')),
        ),
    ]
