# Generated by Django 6.0.1 on 2026-01-24 17:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('business_number', models.CharField(max_length=50, unique=True, verbose_name='Business Number')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.cohort', verbose_name='Cohort')),
            ],
            options={
                'verbose_name': 'Cohort Member',
                'verbose_name_plural': 'Cohort Members',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('education_manager', 'Education Manager'), ('marketing_manager', 'Marketing Manager'), ('financial_manager', 'Financial Manager')], max_length=30, verbose_name='Role')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.cohort', verbose_name='Cohort')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cohort Staff',
                'verbose_name_plural': 'Cohort Staffs',
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='staffs',
            field=models.ManyToManyField(blank=True, through='partner.CohortStaff', to=settings.AUTH_USER_MODEL, verbose_name='Staffs'),
        ),
        migrations.CreateModel(
            name='CohortStaffEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('education_manager', 'Education Manager'), ('marketing_manager', 'Marketing Manager'), ('financial_manager', 'Financial Manager')], max_length=30, verbose_name='Role')),
                ('cohort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.cohort', verbose_name='Cohort')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohortstaff')),
                ('staff', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('encrypted_id_number', models.CharField(blank=True, max_length=255, verbose_name='ID Number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone')),
                ('team', models.CharField(blank=True, default='', max_length=50, verbose_name='Team')),
                ('job_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Position')),
                ('job_title', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Title')),
                ('employment_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Status')),
                ('employment_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.group', verbose_name='Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortMemberEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('cohort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.cohort', verbose_name='Cohort')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.cohortmember')),
                ('member', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.member', verbose_name='Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohortmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='members',
            field=models.ManyToManyField(through='partner.CohortMember', to='partner.member', verbose_name='Members'),
        ),
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('encrypted_id_number', models.CharField(blank=True, max_length=255, verbose_name='ID Number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone')),
                ('team', models.CharField(blank=True, default='', max_length=50, verbose_name='Team')),
                ('job_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Position')),
                ('job_title', models.CharField(blank=True, default='', max_length=50, verbose_name='Job Title')),
                ('employment_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Status')),
                ('employment_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Employment Type')),
                ('group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.group', verbose_name='Group')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.member')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'abstract': False,
                'indexes': [models.Index(fields=['email'], name='partner_par_email_761118_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('business_number', models.CharField(max_length=50, verbose_name='Business Number')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.group')),
                ('partner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Partner'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (NEW."address", NEW."created", NEW."description", NEW."email", NEW."id", NEW."logo", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."website"); RETURN NULL;', hash='0104aebe8a2aae8b2703d2831b29aa34f83c96a8', operation='INSERT', pgid='pgtrigger_insert_insert_b4de1', table='partner_partner', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."address" IS DISTINCT FROM (NEW."address") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."logo" IS DISTINCT FROM (NEW."logo") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."website" IS DISTINCT FROM (NEW."website"))', func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (NEW."address", NEW."created", NEW."description", NEW."email", NEW."id", NEW."logo", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."website"); RETURN NULL;', hash='0a6a0ff3c3a7f461b5b1259dace852f4679b7c60', operation='UPDATE', pgid='pgtrigger_update_update_240cd', table='partner_partner', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partner',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_partnerevent" ("address", "created", "description", "email", "id", "logo", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "website") VALUES (OLD."address", OLD."created", OLD."description", OLD."email", OLD."id", OLD."logo", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."website"); RETURN NULL;', hash='40b59d4ae98810f8237de4075b598636fab239a6', operation='DELETE', pgid='pgtrigger_delete_delete_97aaa', table='partner_partner', when='AFTER')),
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='partner.partner'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='387b71be8bd620939f5be44467867fec0fb1ba18', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_24640', table='partner_cohortevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cohortstaff',
            constraint=models.UniqueConstraint(fields=('cohort', 'staff'), name='partner_cohortstaff_co_sta_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (NEW."cohort_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."staff_id"); RETURN NULL;', hash='3cbc455a3c817948320966e83629fef897f56225', operation='INSERT', pgid='pgtrigger_insert_insert_d966a', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (NEW."cohort_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."staff_id"); RETURN NULL;', hash='c6736cf63cb9b2ac63242c84f2a3e83966194063', operation='UPDATE', pgid='pgtrigger_update_update_3029a', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaff',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortstaffevent" ("cohort_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "staff_id") VALUES (OLD."cohort_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."staff_id"); RETURN NULL;', hash='d0570936caada9c3c24af9c3e1a63b090fd6b538', operation='DELETE', pgid='pgtrigger_delete_delete_fb4fd', table='partner_cohortstaff', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortstaffevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='13b47ca7837bf923dc09d1154e068b90e006bd78', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_49a16', table='partner_cohortstaffevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='partner_mem_name_4ce779_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='partner_mem_email_e72847_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='partner_mem_phone_64504b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['team'], name='partner_mem_team_5121e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('group', 'email'), name='partner_member_si_em_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_id_number", NEW."group_id", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."team", NEW."user_id"); RETURN NULL;', hash='f4690e8088fb0aa1d1d0dd5a1b48354d883ae68f', operation='INSERT', pgid='pgtrigger_insert_insert_ab333', table='partner_member', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."birth_date" IS DISTINCT FROM (NEW."birth_date") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."employment_status" IS DISTINCT FROM (NEW."employment_status") OR OLD."employment_type" IS DISTINCT FROM (NEW."employment_type") OR OLD."encrypted_id_number" IS DISTINCT FROM (NEW."encrypted_id_number") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."job_position" IS DISTINCT FROM (NEW."job_position") OR OLD."job_title" IS DISTINCT FROM (NEW."job_title") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."team" IS DISTINCT FROM (NEW."team") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_id_number", NEW."group_id", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."team", NEW."user_id"); RETURN NULL;', hash='4a9a3c0a4c97fd8ca773beff51cd0a8128d71337', operation='UPDATE', pgid='pgtrigger_update_update_64721', table='partner_member', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_id_number", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (OLD."birth_date", OLD."created", OLD."email", OLD."employment_status", OLD."employment_type", OLD."encrypted_id_number", OLD."group_id", OLD."id", OLD."job_position", OLD."job_title", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."team", OLD."user_id"); RETURN NULL;', hash='cdfe480e456a4ba1397afa1cc07e2a2966953099', operation='DELETE', pgid='pgtrigger_delete_delete_6385d', table='partner_member', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortmemberevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='eb2495c6362200e30475c14639d12460ab74601b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0cabe', table='partner_cohortmemberevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cohortmember',
            constraint=models.UniqueConstraint(fields=('cohort', 'member'), name='partner_cohortmember_co_em_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortmember',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortmemberevent" ("cohort_id", "created", "id", "member_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cohort_id", NEW."created", NEW."id", NEW."member_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='2e5ca51162f1fd00b9f99a0dd19960f8912cee6a', operation='INSERT', pgid='pgtrigger_insert_insert_b2cc4', table='partner_cohortmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortmember',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."cohort_id" IS DISTINCT FROM (NEW."cohort_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."member_id" IS DISTINCT FROM (NEW."member_id"))', func='INSERT INTO "partner_cohortmemberevent" ("cohort_id", "created", "id", "member_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cohort_id", NEW."created", NEW."id", NEW."member_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='60c24e6646df5184529df5276a3716a5330a4878', operation='UPDATE', pgid='pgtrigger_update_update_09326', table='partner_cohortmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohortmember',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortmemberevent" ("cohort_id", "created", "id", "member_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cohort_id", OLD."created", OLD."id", OLD."member_id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='76c486b4ce1cdddfe3e3021269659d2616f80b8c', operation='DELETE', pgid='pgtrigger_delete_delete_26227', table='partner_cohortmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d833840e7b89278806574a8ed3dbed2923131eaf', operation='INSERT', pgid='pgtrigger_insert_insert_e8fd5', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name"))', func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c80997aa6ce01d03a8d84548f429a0a79c0c8ebd', operation='UPDATE', pgid='pgtrigger_update_update_965e8', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cohort',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_cohortevent" ("created", "description", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='5e43e6c396f824b33551bb93cd2ba6657e008e8f', operation='DELETE', pgid='pgtrigger_delete_delete_ee772', table='partner_cohort', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='memberevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bfa97e540a9e3debefe1dee0159238fa1832968c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e1dd9', table='partner_memberevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a53f312785b5b4080d913b4381b64c5da38b8446', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a4ccd', table='partner_groupevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='partner_group_pa_na_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_groupevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."business_number", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."partner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='52ab1136baa053b84f0316871f69604273470803', operation='INSERT', pgid='pgtrigger_insert_insert_33cfa', table='partner_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."business_number" IS DISTINCT FROM (NEW."business_number") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."partner_id" IS DISTINCT FROM (NEW."partner_id"))', func='INSERT INTO "partner_groupevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."business_number", NEW."created", NEW."description", NEW."id", NEW."modified", NEW."name", NEW."partner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='93f886583e841d0d0baed0fafdaf40204fb8c49f', operation='UPDATE', pgid='pgtrigger_update_update_75eda', table='partner_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_groupevent" ("business_number", "created", "description", "id", "modified", "name", "partner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."business_number", OLD."created", OLD."description", OLD."id", OLD."modified", OLD."name", OLD."partner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='0060ac00f8ab2d4d4e35f01137f635341dcb0287', operation='DELETE', pgid='pgtrigger_delete_delete_00e7b', table='partner_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partnerevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='56c6830b5148f30963ee99b53a38c8813212bcdc', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4d8b2', table='partner_partnerevent', when='BEFORE')),
        ),
    ]
