# Generated by Django 6.0.1 on 2026-01-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortstaff',
            name='role',
            field=models.CharField(choices=[('education_manager', 'Education Manager')], max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='cohortstaffevent',
            name='role',
            field=models.CharField(choices=[('education_manager', 'Education Manager')], max_length=30, verbose_name='Role'),
        ),
    ]
