# Generated by Django 6.0.1 on 2026-01-18 04:00

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS partner_cohort_employees CASCADE;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='cohort',
                    name='employees',
                    field=models.ManyToManyField(
                        through='partner.CohortEmployee', 
                        to='partner.employee', 
                        verbose_name='Employees'
                    ),
                ),
            ],
        ),
    ]
