# Generated by Django 6.0.1 on 2026-02-01 16:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_cohortstaff_role_alter_cohortstaffevent_role'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='member',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='member',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='member',
            name='delete_delete',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='encrypted_id_number',
            new_name='encrypted_personal_id',
        ),
        migrations.RenameField(
            model_name='memberevent',
            old_name='encrypted_id_number',
            new_name='encrypted_personal_id',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_personal_id", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_personal_id", NEW."group_id", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."team", NEW."user_id"); RETURN NULL;', hash='a0d7975661189d18e2f24cec6dbbc388a2242ceb', operation='INSERT', pgid='pgtrigger_insert_insert_ab333', table='partner_member', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."birth_date" IS DISTINCT FROM (NEW."birth_date") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."employment_status" IS DISTINCT FROM (NEW."employment_status") OR OLD."employment_type" IS DISTINCT FROM (NEW."employment_type") OR OLD."encrypted_personal_id" IS DISTINCT FROM (NEW."encrypted_personal_id") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."job_position" IS DISTINCT FROM (NEW."job_position") OR OLD."job_title" IS DISTINCT FROM (NEW."job_title") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."team" IS DISTINCT FROM (NEW."team") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_personal_id", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (NEW."birth_date", NEW."created", NEW."email", NEW."employment_status", NEW."employment_type", NEW."encrypted_personal_id", NEW."group_id", NEW."id", NEW."job_position", NEW."job_title", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."team", NEW."user_id"); RETURN NULL;', hash='b7e609eee6ffb52a3057ee18971861d65252be6f', operation='UPDATE', pgid='pgtrigger_update_update_64721', table='partner_member', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='member',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "partner_memberevent" ("birth_date", "created", "email", "employment_status", "employment_type", "encrypted_personal_id", "group_id", "id", "job_position", "job_title", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "team", "user_id") VALUES (OLD."birth_date", OLD."created", OLD."email", OLD."employment_status", OLD."employment_type", OLD."encrypted_personal_id", OLD."group_id", OLD."id", OLD."job_position", OLD."job_title", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."team", OLD."user_id"); RETURN NULL;', hash='f51ab17a6da296ad93259eaa7586bf4691221052', operation='DELETE', pgid='pgtrigger_delete_delete_6385d', table='partner_member', when='AFTER')),
        ),
    ]
