# Generated by Django 6.0.1 on 2026-01-11 01:22

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, verbose_name='Kind')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('min_order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Order Price')),
                ('usage_limit', models.PositiveSmallIntegerField(verbose_name='Usage Limit')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('store_id', models.CharField(max_length=100, verbose_name='Store ID')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='GatewayEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('store_id', models.CharField(max_length=100, verbose_name='Store ID')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20, verbose_name='Status')),
                ('order_number', models.CharField(max_length=24, unique=True, verbose_name='Order Number')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Discount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Customer Phone')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Order Coupon',
                'verbose_name_plural': 'Order Coupons',
            },
        ),
        migrations.CreateModel(
            name='OrderCouponEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20, verbose_name='Status')),
                ('order_number', models.CharField(max_length=24, verbose_name='Order Number')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Discount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Customer Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProductEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_data', models.JSONField(verbose_name='Payment Data')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_data', models.JSONField(verbose_name='Payment Data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('display_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Display Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('display_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Display Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('validity_days', models.PositiveSmallIntegerField(default=60, verbose_name='Validity Days')),
                ('item_id', models.CharField(max_length=36, verbose_name='Item ID')),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItemEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('validity_days', models.PositiveSmallIntegerField(default=60, verbose_name='Validity Days')),
                ('item_id', models.CharField(max_length=36, verbose_name='Item ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='Status')),
                ('refund_id', models.CharField(max_length=100, verbose_name='Refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('refund_data', models.JSONField(blank=True, default=dict, verbose_name='Refund Data')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='Status')),
                ('refund_id', models.CharField(max_length=100, verbose_name='Refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('refund_data', models.JSONField(blank=True, default=dict, verbose_name='Refund Data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.cart')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'Cart Product',
                'verbose_name_plural': 'Cart Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartProductEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('cart', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.cart', verbose_name='Cart')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.cartproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, verbose_name='Kind')),
                ('code', models.CharField(max_length=24, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('min_order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Order Price')),
                ('usage_limit', models.PositiveSmallIntegerField(verbose_name='Usage Limit')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gateway',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_gatewayevent" ("expires", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "store_id") VALUES (NEW."expires", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."store_id"); RETURN NULL;', hash='3a9a538ac21e3d0c2205f9d0d7f10b92f89c556f', operation='INSERT', pgid='pgtrigger_insert_insert_1ab78', table='store_gateway', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gateway',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "store_gatewayevent" ("expires", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "store_id") VALUES (NEW."expires", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."store_id"); RETURN NULL;', hash='b3cb847b90ac8ee8ed66b5e7c4d6452e120cd1de', operation='UPDATE', pgid='pgtrigger_update_update_aac58', table='store_gateway', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gateway',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_gatewayevent" ("expires", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "store_id") VALUES (OLD."expires", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."store_id"); RETURN NULL;', hash='5837540925ad69a099dcd7b89a0d7d794110ffcd', operation='DELETE', pgid='pgtrigger_delete_delete_af572', table='store_gateway', when='AFTER')),
        ),
        migrations.AddField(
            model_name='gatewayevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='gatewayevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.gateway'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='ordercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='ordercoupon',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='ordercouponevent',
            name='coupon',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='ordercouponevent',
            name='order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='ordercouponevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='ordercouponevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.ordercoupon'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderproductevent',
            name='order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderproductevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='orderproductevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.orderproduct'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gateway', verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='gateway',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.gateway', verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.payment'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='operation.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_set',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='operation.TaggedItem', to='operation.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='orderproductevent',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='store.product', verbose_name='Applicable Products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='+', to='store.product', verbose_name='Excluded Products'),
        ),
        migrations.AddField(
            model_name='cartproductevent',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='store.CartProduct', to='store.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.product'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productitemevent',
            name='item_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='productitemevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='productitemevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.productitem'),
        ),
        migrations.AddField(
            model_name='productitemevent',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='payment',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='store.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='store.refund'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='processed_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cartevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0a41f3a39d470057a6699cd4e28fb4d801c13086', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ae02f', table='store_cartevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='couponevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='07ec26a9178661e45ba75dc103caf8bf797a83cb', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_423cb', table='store_couponevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gatewayevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='854db9a3b71039cf4be4dac49f546614af2aa307', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a4d32', table='store_gatewayevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name'], name='store_order_custome_275ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='store_order_custome_97b3a3_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_orderevent" ("created", "customer_email", "customer_id", "customer_name", "customer_phone", "id", "modified", "order_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "subtotal", "total_amount", "total_discount") VALUES (NEW."created", NEW."customer_email", NEW."customer_id", NEW."customer_name", NEW."customer_phone", NEW."id", NEW."modified", NEW."order_number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."subtotal", NEW."total_amount", NEW."total_discount"); RETURN NULL;', hash='4c54276b4ebc3ba53ccf21c6f897415c2920f56b', operation='INSERT', pgid='pgtrigger_insert_insert_b3932', table='store_order', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."customer_id" IS DISTINCT FROM (NEW."customer_id") OR OLD."customer_email" IS DISTINCT FROM (NEW."customer_email") OR OLD."customer_name" IS DISTINCT FROM (NEW."customer_name") OR OLD."customer_phone" IS DISTINCT FROM (NEW."customer_phone") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."order_number" IS DISTINCT FROM (NEW."order_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."subtotal" IS DISTINCT FROM (NEW."subtotal") OR OLD."total_amount" IS DISTINCT FROM (NEW."total_amount") OR OLD."total_discount" IS DISTINCT FROM (NEW."total_discount"))', func='INSERT INTO "store_orderevent" ("created", "customer_email", "customer_id", "customer_name", "customer_phone", "id", "modified", "order_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "subtotal", "total_amount", "total_discount") VALUES (NEW."created", NEW."customer_email", NEW."customer_id", NEW."customer_name", NEW."customer_phone", NEW."id", NEW."modified", NEW."order_number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."subtotal", NEW."total_amount", NEW."total_discount"); RETURN NULL;', hash='a931222b734deee0b0c71abdf8c805198b3857ea', operation='UPDATE', pgid='pgtrigger_update_update_e447f', table='store_order', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_orderevent" ("created", "customer_email", "customer_id", "customer_name", "customer_phone", "id", "modified", "order_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "subtotal", "total_amount", "total_discount") VALUES (OLD."created", OLD."customer_email", OLD."customer_id", OLD."customer_name", OLD."customer_phone", OLD."id", OLD."modified", OLD."order_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."subtotal", OLD."total_amount", OLD."total_discount"); RETURN NULL;', hash='2927e0b7e0d6079717b44b1ca484fdea5259b7f9', operation='DELETE', pgid='pgtrigger_delete_delete_f95ab', table='store_order', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='ordercoupon',
            constraint=models.UniqueConstraint(fields=('order', 'coupon'), name='store_ordercoupon_or_co_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordercoupon',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_ordercouponevent" ("coupon_id", "id", "order_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."coupon_id", NEW."id", NEW."order_id", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='245f90f234a2d2e0a4c7ec8a85417fbba87639fc', operation='INSERT', pgid='pgtrigger_insert_insert_f264e', table='store_ordercoupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordercoupon',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "store_ordercouponevent" ("coupon_id", "id", "order_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."coupon_id", NEW."id", NEW."order_id", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='a73c234c655b8ca59346890dc5ed5cd42d6a8b4c', operation='UPDATE', pgid='pgtrigger_update_update_780f9', table='store_ordercoupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordercoupon',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_ordercouponevent" ("coupon_id", "id", "order_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."coupon_id", OLD."id", OLD."order_id", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='e57b18e903a4456b8bc3b7c8f47f8604d8fc639f', operation='DELETE', pgid='pgtrigger_delete_delete_2da55', table='store_ordercoupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordercouponevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d048cb70b11cc78d59416a5ed77c998ef702c403', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_96c77', table='store_ordercouponevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='03e429870523a8c10b6de7d225a68b55f7b5c7db', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2e475', table='store_orderevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='store_payme_status_5e5751_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_paymentevent" ("amount", "created", "gateway_id", "id", "modified", "order_id", "payment_data", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "transaction_id") VALUES (NEW."amount", NEW."created", NEW."gateway_id", NEW."id", NEW."modified", NEW."order_id", NEW."payment_data", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."transaction_id"); RETURN NULL;', hash='d047d8be16f0bf1f6ef2ddb8aafd6c1b37511fb8', operation='INSERT', pgid='pgtrigger_insert_insert_d9102', table='store_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."gateway_id" IS DISTINCT FROM (NEW."gateway_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."order_id" IS DISTINCT FROM (NEW."order_id") OR OLD."payment_data" IS DISTINCT FROM (NEW."payment_data") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."transaction_id" IS DISTINCT FROM (NEW."transaction_id"))', func='INSERT INTO "store_paymentevent" ("amount", "created", "gateway_id", "id", "modified", "order_id", "payment_data", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "transaction_id") VALUES (NEW."amount", NEW."created", NEW."gateway_id", NEW."id", NEW."modified", NEW."order_id", NEW."payment_data", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."transaction_id"); RETURN NULL;', hash='cc85504f91a8358294963bd15100059609a0239e', operation='UPDATE', pgid='pgtrigger_update_update_562a6', table='store_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_paymentevent" ("amount", "created", "gateway_id", "id", "modified", "order_id", "payment_data", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "transaction_id") VALUES (OLD."amount", OLD."created", OLD."gateway_id", OLD."id", OLD."modified", OLD."order_id", OLD."payment_data", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."transaction_id"); RETURN NULL;', hash='7343e4cb4123b9f553f6c47d705877712359d50b', operation='DELETE', pgid='pgtrigger_delete_delete_bde12', table='store_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dc96589006622bfad5573ab290d8b3bf8f9f289c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_440dd', table='store_paymentevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='store_produ_status_3ab676_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_productevent" ("created", "description", "display_price", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "status", "thumbnail") VALUES (NEW."created", NEW."description", NEW."display_price", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price", NEW."status", NEW."thumbnail"); RETURN NULL;', hash='43034d141d7587778ae1e53d602282e398ce3c01', operation='INSERT', pgid='pgtrigger_insert_insert_09563', table='store_product', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."display_price" IS DISTINCT FROM (NEW."display_price") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."price" IS DISTINCT FROM (NEW."price") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail"))', func='INSERT INTO "store_productevent" ("created", "description", "display_price", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "status", "thumbnail") VALUES (NEW."created", NEW."description", NEW."display_price", NEW."id", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price", NEW."status", NEW."thumbnail"); RETURN NULL;', hash='61ff14b5f1b534cf32d4f40868cbcc09338a3b09', operation='UPDATE', pgid='pgtrigger_update_update_ff994', table='store_product', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_productevent" ("created", "description", "display_price", "id", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "status", "thumbnail") VALUES (OLD."created", OLD."description", OLD."display_price", OLD."id", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."price", OLD."status", OLD."thumbnail"); RETURN NULL;', hash='7bdc995eebc44348c447c09c4a29fcca807810d5', operation='DELETE', pgid='pgtrigger_delete_delete_56270', table='store_product', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderproductevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4c4b5cff12af6e59af5822cad90eb00fc8d7406f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_51e0c', table='store_orderproductevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderproduct',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_orderproductevent" ("created", "discount_amount", "id", "modified", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "product_id", "product_name") VALUES (NEW."created", NEW."discount_amount", NEW."id", NEW."modified", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price", NEW."product_id", NEW."product_name"); RETURN NULL;', hash='289946e84a68d82481b831bd5491abf475dde88f', operation='INSERT', pgid='pgtrigger_insert_insert_bcffe', table='store_orderproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderproduct',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."discount_amount" IS DISTINCT FROM (NEW."discount_amount") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."order_id" IS DISTINCT FROM (NEW."order_id") OR OLD."price" IS DISTINCT FROM (NEW."price") OR OLD."product_id" IS DISTINCT FROM (NEW."product_id") OR OLD."product_name" IS DISTINCT FROM (NEW."product_name"))', func='INSERT INTO "store_orderproductevent" ("created", "discount_amount", "id", "modified", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "product_id", "product_name") VALUES (NEW."created", NEW."discount_amount", NEW."id", NEW."modified", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price", NEW."product_id", NEW."product_name"); RETURN NULL;', hash='6b4d5694207a96171d3ef882919857df3ea73b65', operation='UPDATE', pgid='pgtrigger_update_update_d4f95', table='store_orderproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderproduct',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_orderproductevent" ("created", "discount_amount", "id", "modified", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price", "product_id", "product_name") VALUES (OLD."created", OLD."discount_amount", OLD."id", OLD."modified", OLD."order_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."price", OLD."product_id", OLD."product_name"); RETURN NULL;', hash='06f0d517756f2a1cd38a5f97d03be7aefda03f9f', operation='DELETE', pgid='pgtrigger_delete_delete_dfc03', table='store_orderproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coupon',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_couponevent" ("active", "code", "created", "description", "discount_value", "id", "kind", "min_order_price", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "usage_limit", "valid_from", "valid_until") VALUES (NEW."active", NEW."code", NEW."created", NEW."description", NEW."discount_value", NEW."id", NEW."kind", NEW."min_order_price", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."usage_limit", NEW."valid_from", NEW."valid_until"); RETURN NULL;', hash='8b5ebdd0e060c7e8e5892bbd19d103d2ccf8cac7', operation='INSERT', pgid='pgtrigger_insert_insert_12f01', table='store_coupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coupon',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."discount_value" IS DISTINCT FROM (NEW."discount_value") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."kind" IS DISTINCT FROM (NEW."kind") OR OLD."min_order_price" IS DISTINCT FROM (NEW."min_order_price") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."usage_limit" IS DISTINCT FROM (NEW."usage_limit") OR OLD."valid_from" IS DISTINCT FROM (NEW."valid_from") OR OLD."valid_until" IS DISTINCT FROM (NEW."valid_until"))', func='INSERT INTO "store_couponevent" ("active", "code", "created", "description", "discount_value", "id", "kind", "min_order_price", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "usage_limit", "valid_from", "valid_until") VALUES (NEW."active", NEW."code", NEW."created", NEW."description", NEW."discount_value", NEW."id", NEW."kind", NEW."min_order_price", NEW."modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."usage_limit", NEW."valid_from", NEW."valid_until"); RETURN NULL;', hash='25e5aff393b19ce2b23a53094417b8fb80c79c7b', operation='UPDATE', pgid='pgtrigger_update_update_97f7c', table='store_coupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coupon',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_couponevent" ("active", "code", "created", "description", "discount_value", "id", "kind", "min_order_price", "modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "usage_limit", "valid_from", "valid_until") VALUES (OLD."active", OLD."code", OLD."created", OLD."description", OLD."discount_value", OLD."id", OLD."kind", OLD."min_order_price", OLD."modified", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."usage_limit", OLD."valid_from", OLD."valid_until"); RETURN NULL;', hash='6e6b4743a7c0a29cd316c91ae41045cf7267e031', operation='DELETE', pgid='pgtrigger_delete_delete_06afd', table='store_coupon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cartproductevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='503c295b3cc086f00e7927281252f251d360ce01', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d61cc', table='store_cartproductevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='store_cartproduct_ca_pr_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cartproduct',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_cartproductevent" ("cart_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id") VALUES (NEW."cart_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."product_id"); RETURN NULL;', hash='fe66e12ade81b7e925ae49cbb790c97f21b245c2', operation='INSERT', pgid='pgtrigger_insert_insert_b20e6', table='store_cartproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cartproduct',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."cart_id" IS DISTINCT FROM (NEW."cart_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."product_id" IS DISTINCT FROM (NEW."product_id"))', func='INSERT INTO "store_cartproductevent" ("cart_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id") VALUES (NEW."cart_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."product_id"); RETURN NULL;', hash='9cfc5555fe07be756a98958e0d32b88101243a87', operation='UPDATE', pgid='pgtrigger_update_update_3ec74', table='store_cartproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cartproduct',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_cartproductevent" ("cart_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id") VALUES (OLD."cart_id", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."product_id"); RETURN NULL;', hash='5f539cacd0689bf0aa7316cf0bced664f4e432d5', operation='DELETE', pgid='pgtrigger_delete_delete_8a1fe', table='store_cartproduct', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_active_cart_per_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cart',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_cartevent" ("active", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."active", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."user_id"); RETURN NULL;', hash='493c3eec18238aef8ceaff0fad6ff9839c90819e', operation='INSERT', pgid='pgtrigger_insert_insert_89a7e', table='store_cart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cart',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "store_cartevent" ("active", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (NEW."active", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."user_id"); RETURN NULL;', hash='9a6d7b1c731e0cd44835ab08a46ca883ba163cb4', operation='UPDATE', pgid='pgtrigger_update_update_3617b', table='store_cart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cart',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_cartevent" ("active", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "user_id") VALUES (OLD."active", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."user_id"); RETURN NULL;', hash='f9c515f1e61854fd586ecbabec48de83e2655b85', operation='DELETE', pgid='pgtrigger_delete_delete_87f5d', table='store_cart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='productevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a5a4a2b6f942e3c1615b841b87d0b69e02962d0a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ac0d1', table='store_productevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='productitem',
            index=models.Index(fields=['item_type', 'item_id'], name='store_produ_item_ty_5cef09_idx'),
        ),
        migrations.AddConstraint(
            model_name='productitem',
            constraint=models.UniqueConstraint(fields=('product', 'item_type', 'item_id'), name='store_productitem_pr_itty_itid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='productitem',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_productitemevent" ("created", "id", "item_id", "item_type_id", "modified", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id", "validity_days") VALUES (NEW."created", NEW."id", NEW."item_id", NEW."item_type_id", NEW."modified", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."product_id", NEW."validity_days"); RETURN NULL;', hash='f29338ded94a140d3e9206dddd581e070fa52cc6', operation='INSERT', pgid='pgtrigger_insert_insert_db43e', table='store_productitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='productitem',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."item_type_id" IS DISTINCT FROM (NEW."item_type_id") OR OLD."ordering" IS DISTINCT FROM (NEW."ordering") OR OLD."product_id" IS DISTINCT FROM (NEW."product_id") OR OLD."validity_days" IS DISTINCT FROM (NEW."validity_days"))', func='INSERT INTO "store_productitemevent" ("created", "id", "item_id", "item_type_id", "modified", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id", "validity_days") VALUES (NEW."created", NEW."id", NEW."item_id", NEW."item_type_id", NEW."modified", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."product_id", NEW."validity_days"); RETURN NULL;', hash='46c552727460fab08400b7604e407a0c114a794d', operation='UPDATE', pgid='pgtrigger_update_update_c38ce', table='store_productitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='productitem',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_productitemevent" ("created", "id", "item_id", "item_type_id", "modified", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id", "validity_days") VALUES (OLD."created", OLD."id", OLD."item_id", OLD."item_type_id", OLD."modified", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."product_id", OLD."validity_days"); RETURN NULL;', hash='6e7743fcfc00bfc3dbc4ce96e215452a0e7fdd0f', operation='DELETE', pgid='pgtrigger_delete_delete_e3f44', table='store_productitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='productitemevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='34907983e7ff2c7951781e9c6d89f523159b5588', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_56383', table='store_productitemevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='store_refun_status_643445_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_refundevent" ("amount", "created", "id", "modified", "payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_by_id", "reason", "refund_data", "refund_id", "status") VALUES (NEW."amount", NEW."created", NEW."id", NEW."modified", NEW."payment_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."processed_by_id", NEW."reason", NEW."refund_data", NEW."refund_id", NEW."status"); RETURN NULL;', hash='8a47f5a3575d04ec4fd395bbdeee98ab139980f0', operation='INSERT', pgid='pgtrigger_insert_insert_1c577', table='store_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."payment_id" IS DISTINCT FROM (NEW."payment_id") OR OLD."processed_by_id" IS DISTINCT FROM (NEW."processed_by_id") OR OLD."reason" IS DISTINCT FROM (NEW."reason") OR OLD."refund_data" IS DISTINCT FROM (NEW."refund_data") OR OLD."refund_id" IS DISTINCT FROM (NEW."refund_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "store_refundevent" ("amount", "created", "id", "modified", "payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_by_id", "reason", "refund_data", "refund_id", "status") VALUES (NEW."amount", NEW."created", NEW."id", NEW."modified", NEW."payment_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."processed_by_id", NEW."reason", NEW."refund_data", NEW."refund_id", NEW."status"); RETURN NULL;', hash='4e421856fdaa862aa1c28bc274cf0fbcdc9160c1', operation='UPDATE', pgid='pgtrigger_update_update_5eeda', table='store_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "store_refundevent" ("amount", "created", "id", "modified", "payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_by_id", "reason", "refund_data", "refund_id", "status") VALUES (OLD."amount", OLD."created", OLD."id", OLD."modified", OLD."payment_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."processed_by_id", OLD."reason", OLD."refund_data", OLD."refund_id", OLD."status"); RETURN NULL;', hash='d06a167e50f6920dcc5402424f0de2235aa5b0d1', operation='DELETE', pgid='pgtrigger_delete_delete_d4647', table='store_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refundevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c4a0fcb0b125e3f72c52ba7c3f9fa684112ea97c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6b5db', table='store_refundevent', when='BEFORE')),
        ),
    ]
