# Generated by Django 6.0.3 on 2026-03-11 17:59

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('exam', 'assignment', 'discussion')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Tutor Allocation',
                'verbose_name_plural': 'Tutor Allocations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('content_id', models.CharField(max_length=36, verbose_name='Content ID')),
                ('content_type', models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ('exam', 'assignment', 'discussion')}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Content type')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tutor.allocation')),
                ('tutor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('tutor', 'content_type', 'content_id'), name='tutor_allocation_coty_coid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tutor_allocationevent" ("active", "content_id", "content_type_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tutor_id") VALUES (NEW."active", NEW."content_id", NEW."content_type_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tutor_id"); RETURN NULL;', hash='d32c9391e8701a85b0f0e9ed380044660422222c', operation='INSERT', pgid='pgtrigger_insert_insert_d54dd', table='tutor_allocation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."content_id" IS DISTINCT FROM (NEW."content_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."tutor_id" IS DISTINCT FROM (NEW."tutor_id"))', func='INSERT INTO "tutor_allocationevent" ("active", "content_id", "content_type_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tutor_id") VALUES (NEW."active", NEW."content_id", NEW."content_type_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."tutor_id"); RETURN NULL;', hash='ca721b80fb7aa65fb12a8d402beff29e90f3075a', operation='UPDATE', pgid='pgtrigger_update_update_86aff', table='tutor_allocation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tutor_allocationevent" ("active", "content_id", "content_type_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tutor_id") VALUES (OLD."active", OLD."content_id", OLD."content_type_id", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tutor_id"); RETURN NULL;', hash='bb5f3cad86ea0cea7eaf7e4e43fd1f0459c0af29', operation='DELETE', pgid='pgtrigger_delete_delete_57622', table='tutor_allocation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4530583757a0806520333f7a3bab587961ab3263', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7a1fd', table='tutor_allocationevent', when='BEFORE')),
        ),
    ]
