# Generated by Django 6.0.3 on 2026-03-11 17:59

import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency', '0001_initial'),
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Templates')),
            ],
            options={
                'verbose_name': 'Message Preset',
                'verbose_name_plural': 'Message Presets',
            },
        ),
        migrations.CreateModel(
            name='MessagePresetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Templates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('item_id', models.CharField(max_length=36, verbose_name='Item ID')),
                ('item_type', models.ForeignKey(limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('objective', models.TextField(blank=True, default='', verbose_name='Objective')),
                ('preview_url', models.URLField(blank=True, null=True, verbose_name='Preview URL')),
                ('effort_hours', models.PositiveSmallIntegerField(verbose_name='Effort Hours')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('common', 'Common')], max_length=20, verbose_name='Level')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.faq', verbose_name='FAQ')),
                ('honor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('message_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.messagepreset', verbose_name='Message Preset')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('item_id', models.CharField(max_length=36, verbose_name='Item ID')),
                ('item_type', models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Item Type')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.assessment')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.course', verbose_name='Course'),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.category', verbose_name='Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategoryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.category', verbose_name='Category')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.coursecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to='competency.certificate', verbose_name='Certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Certificate',
                'verbose_name_plural': 'Course Certificates',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCertificateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('certificate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='competency.certificate', verbose_name='Certificate')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.coursecertificate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('lead', models.BooleanField(default=False, verbose_name='Lead')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='course.course', verbose_name='Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructorEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('lead', models.BooleanField(default=False, verbose_name='Lead')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('instructor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.instructor', verbose_name='Instructor')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.courseinstructor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='course.course', verbose_name='Course')),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course', verbose_name='Related Course')),
            ],
            options={
                'verbose_name': 'Related Course',
                'verbose_name_plural': 'Related Courses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRelationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.courserelation')),
                ('related_course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Related Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_surveys', to='course.course', verbose_name='Course')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Course Survey',
                'verbose_name_plural': 'Course Surveys',
            },
        ),
        migrations.CreateModel(
            name='CourseSurveyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.coursesurvey')),
                ('survey', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.survey', verbose_name='Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('lock', models.DateTimeField(verbose_name='Lock')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('realm', models.CharField(choices=[('student', 'Student'), ('studio', 'Studio'), ('tutor', 'Tutor')], db_index=True, default='student', max_length=30, verbose_name='Realm')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('lock', models.DateTimeField(verbose_name='Lock')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('realm', models.CharField(choices=[('student', 'Student'), ('studio', 'Studio'), ('tutor', 'Tutor')], default='student', max_length=30, verbose_name='Realm')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.engagement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('details', models.JSONField(verbose_name='Details')),
                ('score', models.FloatField(verbose_name='Score')),
                ('completion_rate', models.FloatField(verbose_name='Completion Rate')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.engagement', verbose_name='Engagement')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
            ],
            options={
                'verbose_name': 'Gradebook',
                'verbose_name_plural': 'Gradebooks',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradebookEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('details', models.JSONField(verbose_name='Details')),
                ('score', models.FloatField(verbose_name='Score')),
                ('completion_rate', models.FloatField(verbose_name='Completion Rate')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('engagement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.engagement', verbose_name='Engagement')),
                ('grader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.gradebook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_weight', models.PositiveSmallIntegerField(default=100, verbose_name='Assessment Weight')),
                ('completion_weight', models.PositiveSmallIntegerField(default=0, verbose_name='Completion Weight')),
                ('completion_passing_point', models.PositiveSmallIntegerField(default=80, verbose_name='Completion Passing Point')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_policy', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Grading Policy',
                'verbose_name_plural': 'Grading Policies',
            },
        ),
        migrations.CreateModel(
            name='GradingPolicyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('assessment_weight', models.PositiveSmallIntegerField(default=100, verbose_name='Assessment Weight')),
                ('completion_weight', models.PositiveSmallIntegerField(default=0, verbose_name='Completion Weight')),
                ('completion_passing_point', models.PositiveSmallIntegerField(default=80, verbose_name='Completion Passing Point')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.gradingpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days)')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_medias', to='course.lesson', verbose_name='Lesson')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Lesson Media',
                'verbose_name_plural': 'Lesson Medias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonMediaEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('lesson', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.lesson', verbose_name='Lesson')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.lessonmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('objective', models.TextField(blank=True, default='', verbose_name='Objective')),
                ('preview_url', models.URLField(blank=True, null=True, verbose_name='Preview URL')),
                ('effort_hours', models.PositiveSmallIntegerField(verbose_name='Effort Hours')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('common', 'Common')], max_length=20, verbose_name='Level')),
                ('faq', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.faq', verbose_name='FAQ')),
                ('honor_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.course')),
                ('message_preset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.messagepreset', verbose_name='Message Preset')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."templates", NEW."title"); RETURN NULL;', hash='9cd7f44b90b2d85f9375d57c98646cc466baf431', operation='INSERT', pgid='pgtrigger_insert_insert_2ab28', table='course_messagepreset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."templates", NEW."title"); RETURN NULL;', hash='11d5dafc4401c223cdc79861ef45a7c2f739ee31', operation='UPDATE', pgid='pgtrigger_update_update_1065e', table='course_messagepreset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (OLD."description", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."templates", OLD."title"); RETURN NULL;', hash='5c89a7410d23901493ddd4da76adfd868f7356f7', operation='DELETE', pgid='pgtrigger_delete_delete_c2b48', table='course_messagepreset', when='AFTER')),
        ),
        migrations.AddField(
            model_name='messagepresetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='messagepresetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.messagepreset'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f9ef44948d7b0cc08d2f83e55a6c0d55bbcfd467', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a4546', table='course_assessmentevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['item_type', 'item_id'], name='course_asse_item_ty_cecb28_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('course', 'item_type', 'item_id'), name='course_assessment_co_itty_itid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."item_id", NEW."item_type_id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."weight"); RETURN NULL;', hash='3996e15ca2fa7f9af65cf905513d7852b1a25668', operation='INSERT', pgid='pgtrigger_insert_insert_976d7', table='course_assessment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."item_id", NEW."item_type_id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."weight"); RETURN NULL;', hash='bd917fd5d19736c6729dc62e7f49d0eefebfc269', operation='UPDATE', pgid='pgtrigger_update_update_df9e0', table='course_assessment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (OLD."course_id", OLD."end_offset", OLD."id", OLD."item_id", OLD."item_type_id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."weight"); RETURN NULL;', hash='58f213f965751fb4a266ac14bde5fd57821126ca', operation='DELETE', pgid='pgtrigger_delete_delete_8e406', table='course_assessment', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='coursecategory',
            constraint=models.UniqueConstraint(fields=('course', 'category'), name='course_coursecategory_co_ca_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursecategoryevent" ("category_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."category_id", NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d67bdf871af9a2e2fd7c5b69a685d6ae311d5c31', operation='INSERT', pgid='pgtrigger_insert_insert_1a4fe', table='course_coursecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_coursecategoryevent" ("category_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."category_id", NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='6f1ad1aac6eef1be6af13d570af82ffa48e2f758', operation='UPDATE', pgid='pgtrigger_update_update_89b84', table='course_coursecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecategory',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursecategoryevent" ("category_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."category_id", OLD."course_id", OLD."id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='2665c278f59ff1e9156645ef70807ab41156b95d', operation='DELETE', pgid='pgtrigger_delete_delete_15592', table='course_coursecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecategoryevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9eb0853dd19493a2ec3abf04dd8075e3e6b853be', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_df9c4', table='course_coursecategoryevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='coursecertificate',
            constraint=models.UniqueConstraint(fields=('course', 'certificate'), name='course_coursecertificate_co_ce_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecertificate',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursecertificateevent" ("certificate_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."certificate_id", NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='a3ce1470a600bfff7cce01268a66be34100b8730', operation='INSERT', pgid='pgtrigger_insert_insert_1b9a7', table='course_coursecertificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecertificate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_coursecertificateevent" ("certificate_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."certificate_id", NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='a8ec83f14deb6f22169d36d67074b640bac22539', operation='UPDATE', pgid='pgtrigger_update_update_507d2', table='course_coursecertificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecertificate',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursecertificateevent" ("certificate_id", "course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."certificate_id", OLD."course_id", OLD."id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='dc634799a0ec4f4947fe9c510d5093325fdad75c', operation='DELETE', pgid='pgtrigger_delete_delete_d0aeb', table='course_coursecertificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursecertificateevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='41f77f72a3c2064106649461967f343599fc71aa', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2158b', table='course_coursecertificateevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course', 'instructor'), name='course_courseinstructor_co_in_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "label", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."course_id", NEW."id", NEW."instructor_id", NEW."label", NEW."lead", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='1eacd45540ba5ea9c5e21f22025bc7f710941c99', operation='INSERT', pgid='pgtrigger_insert_insert_d457a', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "label", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."course_id", NEW."id", NEW."instructor_id", NEW."label", NEW."lead", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='541b7456fe8a61f8796f4773667b1e81c76252ae', operation='UPDATE', pgid='pgtrigger_update_update_066e4', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "label", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."course_id", OLD."id", OLD."instructor_id", OLD."label", OLD."lead", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='60f87e8e681e0bbbf6a396c1b519f1189020755e', operation='DELETE', pgid='pgtrigger_delete_delete_6cad4', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructorevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='02c654d89c7d7a629f40561785a1f5212094784f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a0cf5', table='course_courseinstructorevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='courserelation',
            constraint=models.UniqueConstraint(fields=('course', 'related_course'), name='course_courserelation_co_re_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courserelation',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courserelationevent" ("course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "related_course_id") VALUES (NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."related_course_id"); RETURN NULL;', hash='decc2e86ea01e745a389ee882130ed6a459cb1b6', operation='INSERT', pgid='pgtrigger_insert_insert_e19d5', table='course_courserelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courserelation',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_courserelationevent" ("course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "related_course_id") VALUES (NEW."course_id", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."related_course_id"); RETURN NULL;', hash='44061efb5d97588366b337a6eb8305b25d6c465e', operation='UPDATE', pgid='pgtrigger_update_update_8709a', table='course_courserelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courserelation',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courserelationevent" ("course_id", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "related_course_id") VALUES (OLD."course_id", OLD."id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."related_course_id"); RETURN NULL;', hash='27dc65404fd42605f6283daeac1b244a15bdfbb9', operation='DELETE', pgid='pgtrigger_delete_delete_45455', table='course_courserelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courserelationevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='939a4147099fb3e200303e804dfe30092dba0c13', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4e0f1', table='course_courserelationevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='coursesurvey',
            constraint=models.UniqueConstraint(fields=('course', 'survey'), name='course_coursesurvey_co_su_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."survey_id"); RETURN NULL;', hash='b3c692efe5e4e3d2e2f965ef1aba57ceedcc5bdf', operation='INSERT', pgid='pgtrigger_insert_insert_11218', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."survey_id"); RETURN NULL;', hash='383f15879ba137abffda89033679974bee2868f4', operation='UPDATE', pgid='pgtrigger_update_update_e49be', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (OLD."course_id", OLD."end_offset", OLD."id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."survey_id"); RETURN NULL;', hash='6d2ee0c6432e91b1bc2244d2dd0c2f09f0d27efb', operation='DELETE', pgid='pgtrigger_delete_delete_7ee27', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurveyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c40e816ecc1fc5c64264da576ae9736beea4749b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3ddef', table='course_coursesurveyevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['learner_id', 'active'], name='course_enga_learner_d73edb_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('course', 'learner'), name='course_engagement_co_le_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "lock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "realm", "started") VALUES (NEW."active", NEW."context", NEW."course_id", NEW."id", NEW."learner_id", NEW."lock", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."realm", NEW."started"); RETURN NULL;', hash='1e9e34003967f775b713d52dcd183f50f780aca0', operation='INSERT', pgid='pgtrigger_insert_insert_dc2ef', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "lock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "realm", "started") VALUES (NEW."active", NEW."context", NEW."course_id", NEW."id", NEW."learner_id", NEW."lock", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."realm", NEW."started"); RETURN NULL;', hash='2ccc4386f50b22851ea503494e995f65fed6d24f', operation='UPDATE', pgid='pgtrigger_update_update_bc152', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "lock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "realm", "started") VALUES (OLD."active", OLD."context", OLD."course_id", OLD."id", OLD."learner_id", OLD."lock", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."realm", OLD."started"); RETURN NULL;', hash='c20d45621859efe71ec12863517037b6c916d06c', operation='DELETE', pgid='pgtrigger_delete_delete_39407', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cd7a283f257446e37420ff52c4447e5fd99e8a9f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_aca6b', table='course_engagementevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (NEW."completion_rate", NEW."confirmed", NEW."created", NEW."details", NEW."engagement_id", NEW."grader_id", NEW."id", NEW."modified", NEW."note", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."score"); RETURN NULL;', hash='17e9ce31cd0515fb3497dc5aeb814099f95c84df', operation='INSERT', pgid='pgtrigger_insert_insert_8a111', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."completion_rate" IS DISTINCT FROM (NEW."completion_rate") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."details" IS DISTINCT FROM (NEW."details") OR OLD."engagement_id" IS DISTINCT FROM (NEW."engagement_id") OR OLD."grader_id" IS DISTINCT FROM (NEW."grader_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (NEW."completion_rate", NEW."confirmed", NEW."created", NEW."details", NEW."engagement_id", NEW."grader_id", NEW."id", NEW."modified", NEW."note", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."score"); RETURN NULL;', hash='72f070d966c3ba92e441fcec7c1e6c794211634d', operation='UPDATE', pgid='pgtrigger_update_update_498d7', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (OLD."completion_rate", OLD."confirmed", OLD."created", OLD."details", OLD."engagement_id", OLD."grader_id", OLD."id", OLD."modified", OLD."note", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."score"); RETURN NULL;', hash='66f10f9480a24fa543416de010c860e9458bf298', operation='DELETE', pgid='pgtrigger_delete_delete_aba98', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebookevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5ede85b84dce8d1784fbae07a6c176cff7933aa8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_252f1', table='course_gradebookevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."assessment_weight", NEW."completion_passing_point", NEW."completion_weight", NEW."course_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='1ad717d651b9dcfb962d4ce75bf61003b758ed4c', operation='INSERT', pgid='pgtrigger_insert_insert_9f27f', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."assessment_weight", NEW."completion_passing_point", NEW."completion_weight", NEW."course_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='717b008caebdeb241765db662fb9e3dcd3c37f01', operation='UPDATE', pgid='pgtrigger_update_update_eb935', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."assessment_weight", OLD."completion_passing_point", OLD."completion_weight", OLD."course_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='0e54137a78bb16bbd5a35fb16314d2dab0a94188', operation='DELETE', pgid='pgtrigger_delete_delete_7ade4', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4d8f76a7659a9748ee46b29af4f924e003a7b197', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0d3cc', table='course_gradingpolicyevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset"); RETURN NULL;', hash='ad834032f198d27db215a38dfa6a827c48c260a8', operation='INSERT', pgid='pgtrigger_insert_insert_d0598', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_lessonevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."label", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset"); RETURN NULL;', hash='39bfc18f3a5e903b14ce4e721155a63c7a17247e', operation='UPDATE', pgid='pgtrigger_update_update_1ef1e', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "end_offset", "id", "label", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset") VALUES (OLD."course_id", OLD."end_offset", OLD."id", OLD."label", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset"); RETURN NULL;', hash='488375c744eca0de9c18490a74ca15a4a9b0790a', operation='DELETE', pgid='pgtrigger_delete_delete_9190d', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='05f4765679fc9105b65fd66f081b8d26035629f8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3c3de', table='course_lessonevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='lessonmedia',
            constraint=models.UniqueConstraint(fields=('lesson', 'media'), name='course_lessonmedia_le_me_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."lesson_id", NEW."media_id", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='b8e5eb9fc674e0854ab8526978956b940722ea52', operation='INSERT', pgid='pgtrigger_insert_insert_f7547', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."lesson_id", NEW."media_id", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c737a5308431cb0054da307547f5a877cbfce824', operation='UPDATE', pgid='pgtrigger_update_update_5f7cd', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."lesson_id", OLD."media_id", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='2a29b0d84faa7a7ec1aeac8bc79869646a0eb143', operation='DELETE', pgid='pgtrigger_delete_delete_62a0a', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='course_lessonmedia_unifier', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF EXISTS (\n                SELECT 1\n                FROM course_lessonmedia lm\n                JOIN course_lesson l ON l.id = lm.lesson_id\n                WHERE lm.media_id = NEW.media_id\n                  AND l.course_id = (\n                      SELECT course_id\n                      FROM course_lesson\n                      WHERE id = NEW.lesson_id\n                      LIMIT 1\n                  )\n                  AND NOT (lm.lesson_id = NEW.lesson_id AND lm.media_id = NEW.media_id)\n            ) THEN\n                RAISE EXCEPTION 'Media already exists in this course';\n            END IF;\n            RETURN NEW;\n        ", hash='1491f26344b8e9ac53a4d8a3d3267cf19564b299', operation='INSERT OR UPDATE', pgid='pgtrigger_course_lessonmedia_unifier_55a84', table='course_lessonmedia', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmediaevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='806d35a36cb1bdd03c0c970f30b3ea61a809013f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3d264', table='course_lessonmediaevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f09adf896ea92dc6a8893e28a7dde9013cae8066', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a11bd', table='course_courseevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='course_course_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "grade_due_days", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."preview_url", NEW."published", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='b3939aedb9fa4063d8597071a191c0a448ce77ff', operation='INSERT', pgid='pgtrigger_insert_insert_b0bd1', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."effort_hours" IS DISTINCT FROM (NEW."effort_hours") OR OLD."faq_id" IS DISTINCT FROM (NEW."faq_id") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."level" IS DISTINCT FROM (NEW."level") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."message_preset_id" IS DISTINCT FROM (NEW."message_preset_id") OR OLD."objective" IS DISTINCT FROM (NEW."objective") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."preview_url" IS DISTINCT FROM (NEW."preview_url") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "course_courseevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "grade_due_days", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."preview_url", NEW."published", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='390a525812f48a2d95f11b97e1ce9d1f567c27e1', operation='UPDATE', pgid='pgtrigger_update_update_8ff8f', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "grade_due_days", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."effort_hours", OLD."faq_id", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."level", OLD."max_attempts", OLD."message_preset_id", OLD."modified", OLD."objective", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."preview_url", OLD."published", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='5d8e0b26f6fa0ecd69fd5a5f2e3ac07b122e02a9', operation='DELETE', pgid='pgtrigger_delete_delete_36642', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='course_course_create_grading_policy', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO course_gradingpolicy (\n                course_id, assessment_weight, completion_weight, completion_passing_point\n            ) VALUES (\n                NEW.id, 100, 0, 80\n            );\n            RETURN NEW;\n        ', hash='2a1a440128250fd2bfc0802b65cdc22403216b02', operation='INSERT', pgid='pgtrigger_course_course_create_grading_policy_f5613', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepresetevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bf5fa50fcebc8eaca18260a46c3e11eefd16dac8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e9086', table='course_messagepresetevent', when='BEFORE')),
        ),
    ]
