# Generated by Django 6.0.1 on 2026-01-11 01:22

import apps.common.models
import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency', '0001_initial'),
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '메시지 프리셋',
                'verbose_name_plural': '메시지 프리셋',
            },
        ),
        migrations.CreateModel(
            name='MessagePresetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='템플릿')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='가중치')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='시작 오프셋 (일)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='종료 오프셋 (일) (시작 오프셋 기준)')),
                ('item_id', models.CharField(max_length=36, verbose_name='항목 ID')),
                ('item_type', models.ForeignKey(limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='항목 유형')),
            ],
            options={
                'verbose_name': '평가',
                'verbose_name_plural': '평가',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('objective', models.TextField(blank=True, default='', verbose_name='목표')),
                ('preview_url', models.URLField(blank=True, null=True, verbose_name='미리보기 URL')),
                ('effort_hours', models.PositiveSmallIntegerField(verbose_name='학습 시간')),
                ('level', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급'), ('common', '공통')], max_length=20, verbose_name='레벨')),
                ('categories', models.ManyToManyField(blank=True, to='operation.category', verbose_name='카테고리')),
                ('certificates', models.ManyToManyField(blank=True, to='competency.certificate', verbose_name='수료증')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.faq', verbose_name='자주 묻는 질문')),
                ('honor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='윤리 서약')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('related_courses', models.ManyToManyField(blank=True, to='course.course', verbose_name='관련 과정')),
            ],
            options={
                'verbose_name': '과정',
                'verbose_name_plural': '과정',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('weight', models.PositiveSmallIntegerField(verbose_name='가중치')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='시작 오프셋 (일)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='종료 오프셋 (일) (시작 오프셋 기준)')),
                ('item_id', models.CharField(max_length=36, verbose_name='항목 ID')),
                ('item_type', models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='항목 유형')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.assessment')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정'),
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('lead', models.BooleanField(default=False, verbose_name='리드')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.instructor', verbose_name='강사')),
            ],
            options={
                'verbose_name': '강사',
                'verbose_name_plural': '강사',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, through='course.CourseInstructor', to='operation.instructor', verbose_name='강사'),
        ),
        migrations.CreateModel(
            name='CourseInstructorEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('lead', models.BooleanField(default=False, verbose_name='리드')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
                ('instructor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.instructor', verbose_name='강사')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.courseinstructor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('timing', models.CharField(choices=[('pre', '사전'), ('post', '게시글'), ('free', '자유')], default='free', max_length=10, verbose_name='시점')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='surveys',
            field=models.ManyToManyField(blank=True, through='course.CourseSurvey', to='survey.survey', verbose_name='설문조사'),
        ),
        migrations.CreateModel(
            name='CourseSurveyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('timing', models.CharField(choices=[('pre', '사전'), ('post', '게시글'), ('free', '자유')], default='free', max_length=10, verbose_name='시점')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.coursesurvey')),
                ('survey', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.survey', verbose_name='설문조사')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학습자')),
            ],
            options={
                'verbose_name': '수강',
                'verbose_name_plural': '수강',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('details', models.JSONField(verbose_name='세부사항')),
                ('score', models.FloatField(verbose_name='점수')),
                ('completion_rate', models.FloatField(verbose_name='완료율')),
                ('passed', models.BooleanField(verbose_name='합격')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='확정됨')),
                ('note', models.TextField(blank=True, default='', verbose_name='노트')),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.engagement', verbose_name='수강')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='채점자')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradebookEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('details', models.JSONField(verbose_name='세부사항')),
                ('score', models.FloatField(verbose_name='점수')),
                ('completion_rate', models.FloatField(verbose_name='완료율')),
                ('passed', models.BooleanField(verbose_name='합격')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='확정됨')),
                ('note', models.TextField(blank=True, default='', verbose_name='노트')),
                ('engagement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.engagement', verbose_name='수강')),
                ('grader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='채점자')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.gradebook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_weight', models.PositiveSmallIntegerField(default=100, verbose_name='평가 가중치')),
                ('completion_weight', models.PositiveSmallIntegerField(default=0, verbose_name='진도율 점수 반영')),
                ('completion_passing_point', models.PositiveSmallIntegerField(default=80, verbose_name='진도율 합격 점수')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정')),
            ],
            options={
                'verbose_name': '채점 정책',
                'verbose_name_plural': '채점 정책',
            },
        ),
        migrations.CreateModel(
            name='GradingPolicyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('assessment_weight', models.PositiveSmallIntegerField(default=100, verbose_name='평가 가중치')),
                ('completion_weight', models.PositiveSmallIntegerField(default=0, verbose_name='진도율 점수 반영')),
                ('completion_passing_point', models.PositiveSmallIntegerField(default=80, verbose_name='진도율 합격 점수')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.gradingpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='시작 오프셋 (일)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='종료 오프셋 (일) (시작 오프셋 기준)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='과정')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='학습자')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.engagement')),
                ('last_lesson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.lesson', verbose_name='마지막 강의 위치')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lesson', verbose_name='마지막 강의 위치'),
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='시작 오프셋 (일)')),
                ('end_offset', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='종료 오프셋 (일) (시작 오프셋 기준)')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='과정')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordering')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='강의')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='미디어')),
            ],
            options={
                'verbose_name': '강의 미디어',
                'verbose_name_plural': '미디어',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='medias',
            field=models.ManyToManyField(through='course.LessonMedia', to='content.media', verbose_name='미디어'),
        ),
        migrations.CreateModel(
            name='LessonMediaEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('lesson', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.lesson', verbose_name='강의')),
                ('media', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='미디어')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.lessonmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('objective', models.TextField(blank=True, default='', verbose_name='목표')),
                ('preview_url', models.URLField(blank=True, null=True, verbose_name='미리보기 URL')),
                ('effort_hours', models.PositiveSmallIntegerField(verbose_name='학습 시간')),
                ('level', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급'), ('common', '공통')], max_length=20, verbose_name='레벨')),
                ('faq', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.faq', verbose_name='자주 묻는 질문')),
                ('honor_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='윤리 서약')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.course')),
                ('message_preset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.messagepreset', verbose_name='메시지 프리셋')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='message_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.messagepreset', verbose_name='메시지 프리셋'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."templates", NEW."title"); RETURN NULL;', hash='9cd7f44b90b2d85f9375d57c98646cc466baf431', operation='INSERT', pgid='pgtrigger_insert_insert_2ab28', table='course_messagepreset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."templates", NEW."title"); RETURN NULL;', hash='11d5dafc4401c223cdc79861ef45a7c2f739ee31', operation='UPDATE', pgid='pgtrigger_update_update_1065e', table='course_messagepreset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepreset',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_messagepresetevent" ("description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "templates", "title") VALUES (OLD."description", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."templates", OLD."title"); RETURN NULL;', hash='5c89a7410d23901493ddd4da76adfd868f7356f7', operation='DELETE', pgid='pgtrigger_delete_delete_c2b48', table='course_messagepreset', when='AFTER')),
        ),
        migrations.AddField(
            model_name='messagepresetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='messagepresetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='course.messagepreset'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f9ef44948d7b0cc08d2f83e55a6c0d55bbcfd467', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a4546', table='course_assessmentevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['item_type', 'item_id'], name='course_asse_item_ty_cecb28_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('course', 'item_type', 'item_id'), name='course_assessment_co_itty_itid_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."item_id", NEW."item_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."weight"); RETURN NULL;', hash='4addc97371e4a62b207678a693b26773aa9d505c', operation='INSERT', pgid='pgtrigger_insert_insert_976d7', table='course_assessment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (NEW."course_id", NEW."end_offset", NEW."id", NEW."item_id", NEW."item_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."weight"); RETURN NULL;', hash='6fd75d9477862aaf6fa99c241cc54cc5260f603d', operation='UPDATE', pgid='pgtrigger_update_update_df9e0', table='course_assessment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assessment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_assessmentevent" ("course_id", "end_offset", "id", "item_id", "item_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "weight") VALUES (OLD."course_id", OLD."end_offset", OLD."id", OLD."item_id", OLD."item_type_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."weight"); RETURN NULL;', hash='0f32009ec7a2a7720542d0965aa47010d714d981', operation='DELETE', pgid='pgtrigger_delete_delete_8e406', table='course_assessment', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course', 'instructor'), name='course_courseinstructor_co_in_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."course_id", NEW."id", NEW."instructor_id", NEW."lead", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='99efcd5a8625a584b41d9695be5adf369c7174db', operation='INSERT', pgid='pgtrigger_insert_insert_d457a', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."course_id", NEW."id", NEW."instructor_id", NEW."lead", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='d1ff7f945570e4c73deae28b48e2ac812d47b2dc', operation='UPDATE', pgid='pgtrigger_update_update_066e4', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseinstructorevent" ("course_id", "id", "instructor_id", "lead", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."course_id", OLD."id", OLD."instructor_id", OLD."lead", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='dd0c00a24f8535aa99f13a28f511df518f3c46ae', operation='DELETE', pgid='pgtrigger_delete_delete_6cad4', table='course_courseinstructor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseinstructorevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='02c654d89c7d7a629f40561785a1f5212094784f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a0cf5', table='course_courseinstructorevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='coursesurvey',
            constraint=models.UniqueConstraint(fields=('course', 'survey'), name='course_coursesurvey_co_su_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "survey_id", "timing") VALUES (NEW."course_id", NEW."id", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."survey_id", NEW."timing"); RETURN NULL;', hash='f86571a127a5474b240b7239186d005107f7a7e2', operation='INSERT', pgid='pgtrigger_insert_insert_11218', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_coursesurveyevent" ("course_id", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "survey_id", "timing") VALUES (NEW."course_id", NEW."id", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."survey_id", NEW."timing"); RETURN NULL;', hash='75e83f8c5e322ffd5daf68e633f04f339d4ddc0d', operation='UPDATE', pgid='pgtrigger_update_update_e49be', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "survey_id", "timing") VALUES (OLD."course_id", OLD."id", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."survey_id", OLD."timing"); RETURN NULL;', hash='0f67dd2256e2cdec76ce9c2d4e8239fa1b34e324', operation='DELETE', pgid='pgtrigger_delete_delete_7ee27', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurveyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c40e816ecc1fc5c64264da576ae9736beea4749b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3ddef', table='course_coursesurveyevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (NEW."completion_rate", NEW."confirmed", NEW."created", NEW."details", NEW."engagement_id", NEW."grader_id", NEW."id", NEW."modified", NEW."note", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."score"); RETURN NULL;', hash='17e9ce31cd0515fb3497dc5aeb814099f95c84df', operation='INSERT', pgid='pgtrigger_insert_insert_8a111', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."completion_rate" IS DISTINCT FROM (NEW."completion_rate") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."details" IS DISTINCT FROM (NEW."details") OR OLD."engagement_id" IS DISTINCT FROM (NEW."engagement_id") OR OLD."grader_id" IS DISTINCT FROM (NEW."grader_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (NEW."completion_rate", NEW."confirmed", NEW."created", NEW."details", NEW."engagement_id", NEW."grader_id", NEW."id", NEW."modified", NEW."note", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."score"); RETURN NULL;', hash='72f070d966c3ba92e441fcec7c1e6c794211634d', operation='UPDATE', pgid='pgtrigger_update_update_498d7', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebook',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradebookevent" ("completion_rate", "confirmed", "created", "details", "engagement_id", "grader_id", "id", "modified", "note", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score") VALUES (OLD."completion_rate", OLD."confirmed", OLD."created", OLD."details", OLD."engagement_id", OLD."grader_id", OLD."id", OLD."modified", OLD."note", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."score"); RETURN NULL;', hash='66f10f9480a24fa543416de010c860e9458bf298', operation='DELETE', pgid='pgtrigger_delete_delete_aba98', table='course_gradebook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradebookevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5ede85b84dce8d1784fbae07a6c176cff7933aa8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_252f1', table='course_gradebookevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."assessment_weight", NEW."completion_passing_point", NEW."completion_weight", NEW."course_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='1ad717d651b9dcfb962d4ce75bf61003b758ed4c', operation='INSERT', pgid='pgtrigger_insert_insert_9f27f', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."assessment_weight", NEW."completion_passing_point", NEW."completion_weight", NEW."course_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='717b008caebdeb241765db662fb9e3dcd3c37f01', operation='UPDATE', pgid='pgtrigger_update_update_eb935', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicy',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_gradingpolicyevent" ("assessment_weight", "completion_passing_point", "completion_weight", "course_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."assessment_weight", OLD."completion_passing_point", OLD."completion_weight", OLD."course_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='0e54137a78bb16bbd5a35fb16314d2dab0a94188', operation='DELETE', pgid='pgtrigger_delete_delete_7ade4', table='course_gradingpolicy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradingpolicyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4d8f76a7659a9748ee46b29af4f924e003a7b197', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0d3cc', table='course_gradingpolicyevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cd7a283f257446e37420ff52c4447e5fd99e8a9f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_aca6b', table='course_engagementevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['learner_id', 'active'], name='course_enga_learner_d73edb_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('course', 'learner'), name='course_engagement_co_le_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "course_id", "created", "id", "last_lesson_id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."course_id", NEW."created", NEW."id", NEW."last_lesson_id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='359a444a7e2d582bd8f2a5b7d44b8e951bbad35e', operation='INSERT', pgid='pgtrigger_insert_insert_dc2ef', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."course_id" IS DISTINCT FROM (NEW."course_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_lesson_id" IS DISTINCT FROM (NEW."last_lesson_id") OR OLD."learner_id" IS DISTINCT FROM (NEW."learner_id"))', func='INSERT INTO "course_engagementevent" ("active", "course_id", "created", "id", "last_lesson_id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."course_id", NEW."created", NEW."id", NEW."last_lesson_id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='9a2694f8173f553e09b95d8b93f0e867a12ce12d', operation='UPDATE', pgid='pgtrigger_update_update_bc152', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "course_id", "created", "id", "last_lesson_id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."course_id", OLD."created", OLD."id", OLD."last_lesson_id", OLD."learner_id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='6423e8b7de726f173a5d612a8a6531c151f98abf', operation='DELETE', pgid='pgtrigger_delete_delete_39407', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='05f4765679fc9105b65fd66f081b8d26035629f8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3c3de', table='course_lessonevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='lessonmedia',
            constraint=models.UniqueConstraint(fields=('lesson', 'media'), name='course_lessonmedia_le_me_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."lesson_id", NEW."media_id", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='b8e5eb9fc674e0854ab8526978956b940722ea52', operation='INSERT', pgid='pgtrigger_insert_insert_f7547', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."lesson_id", NEW."media_id", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='c737a5308431cb0054da307547f5a877cbfce824', operation='UPDATE', pgid='pgtrigger_update_update_5f7cd', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonmediaevent" ("id", "lesson_id", "media_id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."lesson_id", OLD."media_id", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='2a29b0d84faa7a7ec1aeac8bc79869646a0eb143', operation='DELETE', pgid='pgtrigger_delete_delete_62a0a', table='course_lessonmedia', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmedia',
            trigger=pgtrigger.compiler.Trigger(name='course_lessonmedia_unifier', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF EXISTS (\n                SELECT 1\n                FROM course_lessonmedia lm\n                JOIN course_lesson l ON l.id = lm.lesson_id\n                WHERE lm.media_id = NEW.media_id\n                  AND l.course_id = (\n                      SELECT course_id\n                      FROM course_lesson\n                      WHERE id = NEW.lesson_id\n                      LIMIT 1\n                  )\n                  AND lm.id IS DISTINCT FROM NEW.id\n            ) THEN\n                RAISE EXCEPTION 'Media already exists in this course';\n            END IF;\n            RETURN NEW;\n        ", hash='c0bd2db44450b8badb844ac64c5756f75edead83', operation='INSERT OR UPDATE', pgid='pgtrigger_course_lessonmedia_unifier_55a84', table='course_lessonmedia', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='course_lesson_co_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (NEW."course_id", NEW."description", NEW."end_offset", NEW."id", NEW."ordering", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."title"); RETURN NULL;', hash='fa80ae3ab69326da762bebda7598f2c0de6ac5b3', operation='INSERT', pgid='pgtrigger_insert_insert_d0598', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (NEW."course_id", NEW."description", NEW."end_offset", NEW."id", NEW."ordering", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."title"); RETURN NULL;', hash='b0528dc36b7f0b183ee5cea3d9fc18079f0d5060', operation='UPDATE', pgid='pgtrigger_update_update_1ef1e', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "ordering", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (OLD."course_id", OLD."description", OLD."end_offset", OLD."id", OLD."ordering", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."title"); RETURN NULL;', hash='4229af4f4008d2bbf42eb9a6b20160268ce3dca2', operation='DELETE', pgid='pgtrigger_delete_delete_9190d', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonmediaevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='806d35a36cb1bdd03c0c970f30b3ea61a809013f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3d264', table='course_lessonmediaevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='courseevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f09adf896ea92dc6a8893e28a7dde9013cae8066', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a11bd', table='course_courseevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='course_course_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."preview_url", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='9fe85073007a09e5148ab6b30524dcb7503f4153', operation='INSERT', pgid='pgtrigger_insert_insert_b0bd1', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."effort_hours" IS DISTINCT FROM (NEW."effort_hours") OR OLD."faq_id" IS DISTINCT FROM (NEW."faq_id") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."level" IS DISTINCT FROM (NEW."level") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."message_preset_id" IS DISTINCT FROM (NEW."message_preset_id") OR OLD."objective" IS DISTINCT FROM (NEW."objective") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."preview_url" IS DISTINCT FROM (NEW."preview_url") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."preview_url", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='a373dee0bf482e9ed118f5213782c7a604677733', operation='UPDATE', pgid='pgtrigger_update_update_8ff8f', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."effort_hours", OLD."faq_id", OLD."featured", OLD."format", OLD."honor_code_id", OLD."id", OLD."level", OLD."max_attempts", OLD."message_preset_id", OLD."modified", OLD."objective", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."preview_url", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='14a8249c4e43a125c597698d1a45c61d71bab83e', operation='DELETE', pgid='pgtrigger_delete_delete_36642', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='course_course_create_grading_policy', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO course_gradingpolicy (\n                course_id, assessment_weight, completion_weight, completion_passing_point\n            ) VALUES (\n                NEW.id, 100, 0, 80\n            );\n            RETURN NEW;\n        ', hash='2a1a440128250fd2bfc0802b65cdc22403216b02', operation='INSERT', pgid='pgtrigger_course_course_create_grading_policy_f5613', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagepresetevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bf5fa50fcebc8eaca18260a46c3e11eefd16dac8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e9086', table='course_messagepresetevent', when='BEFORE')),
        ),
    ]
