# Generated by Django 6.0.1 on 2026-01-13 07:37

import apps.common.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_remove_certificateaward_insert_insert_and_more'),
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0001_initial'),
        ('operation', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseinstructor',
            options={'verbose_name': 'Course Instructor', 'verbose_name_plural': 'Course Instructors'},
        ),
        migrations.AlterModelOptions(
            name='coursesurvey',
            options={'verbose_name': 'Course Survey', 'verbose_name_plural': 'Course Surveys'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name': 'Engagement', 'verbose_name_plural': 'Engagements'},
        ),
        migrations.AlterModelOptions(
            name='gradebook',
            options={'verbose_name': 'Gradebook', 'verbose_name_plural': 'Gradebooks'},
        ),
        migrations.AlterModelOptions(
            name='gradingpolicy',
            options={'verbose_name': 'Grading Policy', 'verbose_name_plural': 'Grading Policies'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonmedia',
            options={'verbose_name': 'Lesson Media', 'verbose_name_plural': 'Lesson Medias'},
        ),
        migrations.AlterModelOptions(
            name='messagepreset',
            options={'verbose_name': 'Message Preset', 'verbose_name_plural': 'Message Presets'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='item_id',
            field=models.CharField(max_length=36, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='item_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_offset',
            field=models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='item_id',
            field=models.CharField(max_length=36, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='item_type',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'model__in': ['exam', 'assignment', 'discussion']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='start_offset',
            field=models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)'),
        ),
        migrations.AlterField(
            model_name='assessmentevent',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='operation.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='competency.certificate', verbose_name='Certificates'),
        ),
        migrations.AlterField(
            model_name='course',
            name='effort_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Effort Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.faq', verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='honor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, through='course.CourseInstructor', to='operation.instructor', verbose_name='Instructors'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('common', 'Common')], max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='message_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.messagepreset', verbose_name='Message Preset'),
        ),
        migrations.AlterField(
            model_name='course',
            name='objective',
            field=models.TextField(blank=True, default='', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_url',
            field=models.URLField(blank=True, null=True, verbose_name='Preview URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='course.course', verbose_name='Related Courses'),
        ),
        migrations.AlterField(
            model_name='course',
            name='surveys',
            field=models.ManyToManyField(blank=True, through='course.CourseSurvey', to='survey.survey', verbose_name='Surveys'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='effort_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Effort Hours'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='faq',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.faq', verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='honor_code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('common', 'Common')], max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='message_preset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.messagepreset', verbose_name='Message Preset'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='objective',
            field=models.TextField(blank=True, default='', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='preview_url',
            field=models.URLField(blank=True, null=True, verbose_name='Preview URL'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='lead',
            field=models.BooleanField(default=False, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='courseinstructorevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseinstructorevent',
            name='instructor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='courseinstructorevent',
            name='lead',
            field=models.BooleanField(default=False, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='coursesurvey',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursesurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='coursesurvey',
            name='timing',
            field=models.CharField(choices=[('pre', 'Pre'), ('post', 'Post'), ('free', 'Free')], default='free', max_length=10, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='coursesurveyevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursesurveyevent',
            name='survey',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='survey.survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='coursesurveyevent',
            name='timing',
            field=models.CharField(choices=[('pre', 'Pre'), ('post', 'Post'), ('free', 'Free')], default='free', max_length=10, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lesson', verbose_name='Last Lesson'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Learner'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='last_lesson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.lesson', verbose_name='Last Lesson'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='learner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='completion_rate',
            field=models.FloatField(verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='confirmed',
            field=apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='details',
            field=models.JSONField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='engagement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.engagement', verbose_name='Engagement'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='passed',
            field=models.BooleanField(verbose_name='Passed'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='completion_rate',
            field=models.FloatField(verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='confirmed',
            field=apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='details',
            field=models.JSONField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='engagement',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.engagement', verbose_name='Engagement'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='grader',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='passed',
            field=models.BooleanField(verbose_name='Passed'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='assessment_weight',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Assessment Weight'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='completion_passing_point',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Completion Passing Point'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='completion_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Completion Weight'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='gradingpolicyevent',
            name='assessment_weight',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Assessment Weight'),
        ),
        migrations.AlterField(
            model_name='gradingpolicyevent',
            name='completion_passing_point',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Completion Passing Point'),
        ),
        migrations.AlterField(
            model_name='gradingpolicyevent',
            name='completion_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Completion Weight'),
        ),
        migrations.AlterField(
            model_name='gradingpolicyevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='medias',
            field=models.ManyToManyField(through='course.LessonMedia', to='content.media', verbose_name='Medias'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_offset',
            field=models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='start_offset',
            field=models.PositiveSmallIntegerField(verbose_name='Start Offset (Days)'),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='lessonmediaevent',
            name='lesson',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='course.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonmediaevent',
            name='media',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='content.media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='messagepreset',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='messagepreset',
            name='templates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Templates'),
        ),
        migrations.AlterField(
            model_name='messagepreset',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='messagepresetevent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='messagepresetevent',
            name='templates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Templates'),
        ),
        migrations.AlterField(
            model_name='messagepresetevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
