# Generated by Django 6.0.2 on 2026-03-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operation.faq', verbose_name='FAQ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='honor_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='faq',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.faq', verbose_name='FAQ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='honor_code',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code'),
            preserve_default=False,
        ),
    ]
