# Generated by Django 6.0.1 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradebook',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='gradebookevent',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed'),
        ),
    ]
