# Generated by Django 6.0.2 on 2026-02-25 05:23

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='engagement',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='engagement',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='engagement',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='last_lesson',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='engagementevent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='engagementevent',
            name='last_lesson',
        ),
        migrations.RemoveField(
            model_name='engagementevent',
            name='modified',
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='courseevent',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."preview_url", NEW."published", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='aabd0bb049bc09bd40f2f86de5d072499bf68196', operation='INSERT', pgid='pgtrigger_insert_insert_b0bd1', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."effort_hours" IS DISTINCT FROM (NEW."effort_hours") OR OLD."faq_id" IS DISTINCT FROM (NEW."faq_id") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."level" IS DISTINCT FROM (NEW."level") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."message_preset_id" IS DISTINCT FROM (NEW."message_preset_id") OR OLD."objective" IS DISTINCT FROM (NEW."objective") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."preview_url" IS DISTINCT FROM (NEW."preview_url") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."preview_url", NEW."published", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='f47ae042c6e7e7a10354192d997e81b5934e029b', operation='UPDATE', pgid='pgtrigger_update_update_8ff8f', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "published", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."effort_hours", OLD."faq_id", OLD."featured", OLD."format", OLD."honor_code_id", OLD."id", OLD."level", OLD."max_attempts", OLD."message_preset_id", OLD."modified", OLD."objective", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."preview_url", OLD."published", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='2d9743409281694ed38d213212c6c0d5697ce7bf', operation='DELETE', pgid='pgtrigger_delete_delete_36642', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (NEW."active", NEW."context", NEW."course_id", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."started"); RETURN NULL;', hash='355ab145a728354afebc187bffcf5ea2b51ccc24', operation='INSERT', pgid='pgtrigger_insert_insert_dc2ef', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (NEW."active", NEW."context", NEW."course_id", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."started"); RETURN NULL;', hash='646532a419d9328d25f82a9d3581963d46628ccb', operation='UPDATE', pgid='pgtrigger_update_update_bc152', table='course_engagement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_engagementevent" ("active", "context", "course_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (OLD."active", OLD."context", OLD."course_id", OLD."id", OLD."learner_id", OLD."mode", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."started"); RETURN NULL;', hash='52257ed31f728c7792d36f7f9534d16be2aa05de', operation='DELETE', pgid='pgtrigger_delete_delete_39407', table='course_engagement', when='AFTER')),
        ),
    ]
