# Generated by Django 6.0.2 on 2026-03-03 12:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_faq_alter_course_honor_code_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='course',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='course',
            name='published',
        ),
        migrations.RemoveField(
            model_name='courseevent',
            name='published',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."preview_url", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='9fe85073007a09e5148ab6b30524dcb7503f4153', operation='INSERT', pgid='pgtrigger_insert_insert_b0bd1', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."effort_hours" IS DISTINCT FROM (NEW."effort_hours") OR OLD."faq_id" IS DISTINCT FROM (NEW."faq_id") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."level" IS DISTINCT FROM (NEW."level") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."message_preset_id" IS DISTINCT FROM (NEW."message_preset_id") OR OLD."objective" IS DISTINCT FROM (NEW."objective") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."preview_url" IS DISTINCT FROM (NEW."preview_url") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."effort_hours", NEW."faq_id", NEW."featured", NEW."format", NEW."honor_code_id", NEW."id", NEW."level", NEW."max_attempts", NEW."message_preset_id", NEW."modified", NEW."objective", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."preview_url", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='a373dee0bf482e9ed118f5213782c7a604677733', operation='UPDATE', pgid='pgtrigger_update_update_8ff8f', table='course_course', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='course',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_courseevent" ("audience", "created", "description", "duration", "effort_hours", "faq_id", "featured", "format", "honor_code_id", "id", "level", "max_attempts", "message_preset_id", "modified", "objective", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "preview_url", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."effort_hours", OLD."faq_id", OLD."featured", OLD."format", OLD."honor_code_id", OLD."id", OLD."level", OLD."max_attempts", OLD."message_preset_id", OLD."modified", OLD."objective", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."preview_url", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='14a8249c4e43a125c597698d1a45c61d71bab83e', operation='DELETE', pgid='pgtrigger_delete_delete_36642', table='course_course', when='AFTER')),
        ),
    ]
