# Generated by Django 6.0.1 on 2026-01-14 17:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_assessment_options_alter_course_options_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='coursesurvey',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='coursesurvey',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='coursesurvey',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='coursesurvey',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='coursesurvey',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='coursesurveyevent',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='coursesurveyevent',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='lessonevent',
            name='ordering',
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='start_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Start Offset (Days)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesurveyevent',
            name='end_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Offset (Days) from Start Offset'),
        ),
        migrations.AddField(
            model_name='coursesurveyevent',
            name='start_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Start Offset (Days)'),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (NEW."course_id", NEW."end_offset", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."survey_id"); RETURN NULL;', hash='f246df283a2c16731262ce7cc3654c035a473786', operation='INSERT', pgid='pgtrigger_insert_insert_11218', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (NEW."course_id", NEW."end_offset", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."survey_id"); RETURN NULL;', hash='c54810920c4afcdad0a199f6e0e20cc074100d35', operation='UPDATE', pgid='pgtrigger_update_update_e49be', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coursesurvey',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_coursesurveyevent" ("course_id", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "survey_id") VALUES (OLD."course_id", OLD."end_offset", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."survey_id"); RETURN NULL;', hash='a3c4c018e6b395f83f430d8a3053402261124e57', operation='DELETE', pgid='pgtrigger_delete_delete_7ee27', table='course_coursesurvey', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (NEW."course_id", NEW."description", NEW."end_offset", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_offset", NEW."title"); RETURN NULL;', hash='5a1e3efdcd6d585bd31a01ad69eb4a99474f6414', operation='INSERT', pgid='pgtrigger_insert_insert_d0598', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (NEW."course_id", NEW."description", NEW."end_offset", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_offset", NEW."title"); RETURN NULL;', hash='e6640904def111d0e72f0431062c9ca68bc028c4', operation='UPDATE', pgid='pgtrigger_update_update_1ef1e', table='course_lesson', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "course_lessonevent" ("course_id", "description", "end_offset", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_offset", "title") VALUES (OLD."course_id", OLD."description", OLD."end_offset", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_offset", OLD."title"); RETURN NULL;', hash='a2fb499ccc9c755a32b9a8403c4e6c37d909a1a4', operation='DELETE', pgid='pgtrigger_delete_delete_9190d', table='course_lesson', when='AFTER')),
        ),
    ]
