# Generated by Django 6.0.1 on 2026-01-11 01:20

import apps.common.models
import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input'), ('essay', 'Essay')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('point', models.PositiveSmallIntegerField(default=1, verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('honor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.attempt')),
                ('exam', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.exam', verbose_name='Exam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(to='exam.question', verbose_name='Questions'),
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('composition', models.JSONField(verbose_name='Question Composition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('format', models.CharField(choices=[('single_choice', 'Single Choice'), ('text_input', 'Text Input'), ('number_input', 'Number Input'), ('essay', 'Essay')], max_length=20, verbose_name='Format')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Options')),
                ('point', models.PositiveSmallIntegerField(default=1, verbose_name='Point')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.question')),
                ('pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('honor_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.exam')),
                ('question_pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='question_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='QuestionPoolEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('composition', models.JSONField(verbose_name='Question Composition')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.questionpool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Correct Answers')),
                ('correct_criteria', models.TextField(blank=True, default='', verbose_name='Correct Criteria')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Reference')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='SolutionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Correct Answers')),
                ('correct_criteria', models.TextField(blank=True, default='', verbose_name='Correct Criteria')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Reference')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.solution')),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.question', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.attempt', verbose_name='Attempt')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Temporary Answer',
                'verbose_name_plural': 'Temporary Answers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempAnswerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='exam.attempt', verbose_name='Attempt')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='exam.tempanswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attemptevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='3978707fe6bc7c00b31b92b9e8e129f64e6e16e8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_31d6a', table='exam_attemptevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='b5136eba81a27d0774d898d1703a43fc09fc4691', operation='INSERT', pgid='pgtrigger_insert_insert_45a80', table='exam_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."completed" IS DISTINCT FROM (NEW."completed") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."earned_details" IS DISTINCT FROM (NEW."earned_details") OR OLD."earned_point" IS DISTINCT FROM (NEW."earned_point") OR OLD."feedback" IS DISTINCT FROM (NEW."feedback") OR OLD."grader_id" IS DISTINCT FROM (NEW."grader_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."possible_point" IS DISTINCT FROM (NEW."possible_point") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "exam_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='dbaa3d8d85a0ce201cbff8db4e438938aa546445', operation='UPDATE', pgid='pgtrigger_update_update_8ecf5', table='exam_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (OLD."attempt_id", OLD."completed", OLD."confirmed", OLD."created", OLD."earned_details", OLD."earned_point", OLD."feedback", OLD."grader_id", OLD."id", OLD."modified", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."possible_point", OLD."score"); RETURN NULL;', hash='7158af2162c49e30d29370921716311172dae696', operation='DELETE', pgid='pgtrigger_delete_delete_3a8d0', table='exam_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='3e841f2b3a1ef5b9b904fcda18768a9e351fff38', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_8da0c', table='exam_gradeevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['learner_id', 'active'], name='exam_attemp_learner_6ceeba_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('exam', 'learner', 'context'), name='exam_attemp_ex_le_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (NEW."active", NEW."context", NEW."exam_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."started"); RETURN NULL;', hash='d7dd0f142fe0c41a49d68539bebc0dec45bbf6dd', operation='INSERT', pgid='pgtrigger_insert_insert_d95a6', table='exam_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (NEW."active", NEW."context", NEW."exam_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."started"); RETURN NULL;', hash='2c63056411146226c0ff4560ebb1c6abb0c0071b', operation='UPDATE', pgid='pgtrigger_update_update_3268a', table='exam_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started") VALUES (OLD."active", OLD."context", OLD."exam_id", OLD."id", OLD."learner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."started"); RETURN NULL;', hash='12e06e226202f2b7b70e253b5ef83b91549505e6', operation='DELETE', pgid='pgtrigger_delete_delete_9811e', table='exam_attempt', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='exam_questionpool_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_questionpoolevent" ("composition", "description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."composition", NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='ff01d0f776a4c293727d513a9bf486c717e38ef6', operation='INSERT', pgid='pgtrigger_insert_insert_dd4cc', table='exam_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "exam_questionpoolevent" ("composition", "description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."composition", NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='27e98c9a0372f9db5d76e8f13e983f8de7f426d9', operation='UPDATE', pgid='pgtrigger_update_update_fa9c5', table='exam_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_questionpoolevent" ("composition", "description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."composition", OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='744883de9a7b94be37bab62288adc8a377f82066', operation='DELETE', pgid='pgtrigger_delete_delete_e30fd', table='exam_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9f3d859121a86d12e6c412a1e42ad537a75f9639', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_302e6', table='exam_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_questionevent" ("format", "id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."options", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='6ed83b6e774eed117b97f7d560843d7a6d36141f', operation='INSERT', pgid='pgtrigger_insert_insert_11e5f', table='exam_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "exam_questionevent" ("format", "id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (NEW."format", NEW."id", NEW."options", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='5baeea7b742ca2c83593bf467be1b66116911460', operation='UPDATE', pgid='pgtrigger_update_update_69721', table='exam_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_questionevent" ("format", "id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (OLD."format", OLD."id", OLD."options", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point", OLD."pool_id", OLD."question", OLD."supplement"); RETURN NULL;', hash='0ce499bf514ffe5e4e96be1ba3f42f4fae27a2ef', operation='DELETE', pgid='pgtrigger_delete_delete_2b22e', table='exam_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='examevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cfa60eff7a4ce0f03dcb58ed46826f8b292670f2', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ed8b9', table='exam_examevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='exam_exam_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exam',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_examevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='1375a0d2e60696035a475bd21b8a697d49f2ddb6', operation='INSERT', pgid='pgtrigger_insert_insert_8cb8f', table='exam_exam', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exam',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "exam_examevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='3c2d835341815a8e0f6d7033915aad21bb3fce28', operation='UPDATE', pgid='pgtrigger_update_update_e5bfc', table='exam_exam', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exam',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_examevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='46f54dde7462afe5c8c2330c7066c39905624df1', operation='DELETE', pgid='pgtrigger_delete_delete_2a8e1', table='exam_exam', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpoolevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bae63d1857200889a856629b09ee1bd96f5862e6', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d3b53', table='exam_questionpoolevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_solutionevent" ("correct_answers", "correct_criteria", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference") VALUES (NEW."correct_answers", NEW."correct_criteria", NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."reference"); RETURN NULL;', hash='367118e8e04668a034bba62e3f4b8cc694678619', operation='INSERT', pgid='pgtrigger_insert_insert_1c17b', table='exam_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "exam_solutionevent" ("correct_answers", "correct_criteria", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference") VALUES (NEW."correct_answers", NEW."correct_criteria", NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."reference"); RETURN NULL;', hash='b74e436b19605878ab9271305870750b8fd4aeaa', operation='UPDATE', pgid='pgtrigger_update_update_7711c', table='exam_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_solutionevent" ("correct_answers", "correct_criteria", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "reference") VALUES (OLD."correct_answers", OLD."correct_criteria", OLD."explanation", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."reference"); RETURN NULL;', hash='18f39e1cd31eb0d5f50a3acb037f70e20b41d3f9', operation='DELETE', pgid='pgtrigger_delete_delete_b0805', table='exam_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solutionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='2fb13e7ea326a923cdc09730607601d49a98b465', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0d1fd', table='exam_solutionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='6d82f4576b56fe1efa98ec57ffdb6b64336c5b2f', operation='INSERT', pgid='pgtrigger_insert_insert_87440', table='exam_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "exam_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='5f1c66caf9f676bb3fbb5d29b95c81aa2912f445', operation='UPDATE', pgid='pgtrigger_update_update_234bb', table='exam_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."answers", OLD."attempt_id", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='4366c9fe45589a229b5d10233b94a677dd15eb6c', operation='DELETE', pgid='pgtrigger_delete_delete_980ca', table='exam_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cddb5c670942a43e562614e44a3395b8b9cd3d79', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_bff5e', table='exam_submissionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tempanswer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_tempanswerevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='62a62093b065003e237b5b83c77020c5d0490389', operation='INSERT', pgid='pgtrigger_insert_insert_cf31e', table='exam_tempanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tempanswer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "exam_tempanswerevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='24622e334d604c979380b9f27907a27582892f4f', operation='UPDATE', pgid='pgtrigger_update_update_2d7c2', table='exam_tempanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tempanswer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_tempanswerevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."answers", OLD."attempt_id", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='9043b8283dc16f8e040bc030cdb1b3d636ffc212', operation='DELETE', pgid='pgtrigger_delete_delete_d8cb6', table='exam_tempanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tempanswerevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9aae48ca77910b95bd5f0b017a2ee5d4e10ab803', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_cf595', table='exam_tempanswerevent', when='BEFORE')),
        ),
    ]
