# Generated by Django 6.0.1 on 2026-01-19 17:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."exam_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."retry", NEW."started"); RETURN NULL;', hash='a18f524488a9bc1ac5247e49d18127b3b5502b12', operation='INSERT', pgid='pgtrigger_insert_insert_d95a6', table='exam_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."exam_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."retry", NEW."started"); RETURN NULL;', hash='2464d810d238cc570809ff634f0b22e05f7628a9', operation='UPDATE', pgid='pgtrigger_update_update_3268a', table='exam_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "exam_attemptevent" ("active", "context", "exam_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "retry", "started") VALUES (OLD."active", OLD."context", OLD."exam_id", OLD."id", OLD."learner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."retry", OLD."started"); RETURN NULL;', hash='d584810eeff08bff630f2728f2f8d3e5ba13e471', operation='DELETE', pgid='pgtrigger_delete_delete_9811e', table='exam_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='exam_attempt_retry_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                SELECT COALESCE(MAX(retry), -1) + 1\n                INTO NEW.retry\n                FROM exam_attempt\n                WHERE exam_id = NEW.exam_id \n                  AND learner_id = NEW.learner_id \n                  AND context = NEW.context;\n                RETURN NEW;\n            END;\n        ', hash='f3b731a5312117ec7b422e8da20da5a244a33a15', operation='INSERT', pgid='pgtrigger_exam_attempt_retry_count_b5030', table='exam_attempt', when='BEFORE')),
        ),
    ]
