/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteRouteImport } from './routes/tutor/route'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as authPasswordChangeRouteImport } from './routes/(auth)/password-change'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authJoinRouteImport } from './routes/(auth)/join'
import { Route as authActivateRouteImport } from './routes/(auth)/activate'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appAccountRouteRouteImport } from './routes/(app)/account/route'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as StudioAppIdRouteImport } from './routes/studio/$app.$id'
import { Route as publicSurveyIdRouteImport } from './routes/(public)/survey/$id'
import { Route as appMediaIdRouteImport } from './routes/(app)/media/$id'
import { Route as appDashboardSearchRouteImport } from './routes/(app)/dashboard/search'
import { Route as appDashboardReportRouteImport } from './routes/(app)/dashboard/report'
import { Route as appDashboardLearningRouteImport } from './routes/(app)/dashboard/learning'
import { Route as appDashboardInquiryRouteImport } from './routes/(app)/dashboard/inquiry'
import { Route as appDashboardGoalRouteImport } from './routes/(app)/dashboard/goal'
import { Route as appDashboardCatalogRouteImport } from './routes/(app)/dashboard/catalog'
import { Route as appDashboardAnnouncementRouteImport } from './routes/(app)/dashboard/announcement'
import { Route as appDashboardAchievementRouteImport } from './routes/(app)/dashboard/achievement'
import { Route as appAccountProfileRouteImport } from './routes/(app)/account/profile'
import { Route as appAccountLinkRouteImport } from './routes/(app)/account/link'
import { Route as appAccountGroupRouteImport } from './routes/(app)/account/group'
import { Route as appAccountEmailChangeRouteImport } from './routes/(app)/account/email-change'
import { Route as appAccountDeviceRouteImport } from './routes/(app)/account/device'
import { Route as TutorExamIdGradingRouteImport } from './routes/tutor/exam/$id.grading'
import { Route as TutorDiscussionIdGradingRouteImport } from './routes/tutor/discussion/$id.grading'
import { Route as TutorAssignmentIdGradingRouteImport } from './routes/tutor/assignment/$id.grading'
import { Route as TutorAppIdAppealRouteImport } from './routes/tutor/$app.$id.appeal'
import { Route as appExamIdSessionRouteImport } from './routes/(app)/exam/$id.session'
import { Route as appDiscussionIdSessionRouteImport } from './routes/(app)/discussion/$id.session'
import { Route as appCourseIdSessionRouteImport } from './routes/(app)/course/$id.session'
import { Route as appAssignmentIdSessionRouteImport } from './routes/(app)/assignment/$id.session'

const TutorRouteRoute = TutorRouteRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRouteRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const authPasswordChangeRoute = authPasswordChangeRouteImport.update({
  id: '/password-change',
  path: '/password-change',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authJoinRoute = authJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => authRouteRoute,
} as any)
const authActivateRoute = authActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => authRouteRoute,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAccountRouteRoute = appAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const StudioAppIdRoute = StudioAppIdRouteImport.update({
  id: '/$app/$id',
  path: '/$app/$id',
  getParentRoute: () => StudioRouteRoute,
} as any)
const publicSurveyIdRoute = publicSurveyIdRouteImport.update({
  id: '/(public)/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const appMediaIdRoute = appMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardSearchRoute = appDashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardReportRoute = appDashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardLearningRoute = appDashboardLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardInquiryRoute = appDashboardInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardGoalRoute = appDashboardGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardCatalogRoute = appDashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardAnnouncementRoute =
  appDashboardAnnouncementRouteImport.update({
    id: '/announcement',
    path: '/announcement',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardAchievementRoute = appDashboardAchievementRouteImport.update({
  id: '/achievement',
  path: '/achievement',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appAccountProfileRoute = appAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appAccountRouteRoute,
} as any)
const appAccountLinkRoute = appAccountLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => appAccountRouteRoute,
} as any)
const appAccountGroupRoute = appAccountGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => appAccountRouteRoute,
} as any)
const appAccountEmailChangeRoute = appAccountEmailChangeRouteImport.update({
  id: '/email-change',
  path: '/email-change',
  getParentRoute: () => appAccountRouteRoute,
} as any)
const appAccountDeviceRoute = appAccountDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => appAccountRouteRoute,
} as any)
const TutorExamIdGradingRoute = TutorExamIdGradingRouteImport.update({
  id: '/exam/$id/grading',
  path: '/exam/$id/grading',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorDiscussionIdGradingRoute =
  TutorDiscussionIdGradingRouteImport.update({
    id: '/discussion/$id/grading',
    path: '/discussion/$id/grading',
    getParentRoute: () => TutorRouteRoute,
  } as any)
const TutorAssignmentIdGradingRoute =
  TutorAssignmentIdGradingRouteImport.update({
    id: '/assignment/$id/grading',
    path: '/assignment/$id/grading',
    getParentRoute: () => TutorRouteRoute,
  } as any)
const TutorAppIdAppealRoute = TutorAppIdAppealRouteImport.update({
  id: '/$app/$id/appeal',
  path: '/$app/$id/appeal',
  getParentRoute: () => TutorRouteRoute,
} as any)
const appExamIdSessionRoute = appExamIdSessionRouteImport.update({
  id: '/exam/$id/session',
  path: '/exam/$id/session',
  getParentRoute: () => appRouteRoute,
} as any)
const appDiscussionIdSessionRoute = appDiscussionIdSessionRouteImport.update({
  id: '/discussion/$id/session',
  path: '/discussion/$id/session',
  getParentRoute: () => appRouteRoute,
} as any)
const appCourseIdSessionRoute = appCourseIdSessionRouteImport.update({
  id: '/course/$id/session',
  path: '/course/$id/session',
  getParentRoute: () => appRouteRoute,
} as any)
const appAssignmentIdSessionRoute = appAssignmentIdSessionRouteImport.update({
  id: '/assignment/$id/session',
  path: '/assignment/$id/session',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/account': typeof appAccountRouteRouteWithChildren
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/activate': typeof authActivateRoute
  '/join': typeof authJoinRoute
  '/login': typeof authLoginRoute
  '/password-change': typeof authPasswordChangeRoute
  '/studio/': typeof StudioIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/account/device': typeof appAccountDeviceRoute
  '/account/email-change': typeof appAccountEmailChangeRoute
  '/account/group': typeof appAccountGroupRoute
  '/account/link': typeof appAccountLinkRoute
  '/account/profile': typeof appAccountProfileRoute
  '/dashboard/achievement': typeof appDashboardAchievementRoute
  '/dashboard/announcement': typeof appDashboardAnnouncementRoute
  '/dashboard/catalog': typeof appDashboardCatalogRoute
  '/dashboard/goal': typeof appDashboardGoalRoute
  '/dashboard/inquiry': typeof appDashboardInquiryRoute
  '/dashboard/learning': typeof appDashboardLearningRoute
  '/dashboard/report': typeof appDashboardReportRoute
  '/dashboard/search': typeof appDashboardSearchRoute
  '/media/$id': typeof appMediaIdRoute
  '/survey/$id': typeof publicSurveyIdRoute
  '/studio/$app/$id': typeof StudioAppIdRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/assignment/$id/session': typeof appAssignmentIdSessionRoute
  '/course/$id/session': typeof appCourseIdSessionRoute
  '/discussion/$id/session': typeof appDiscussionIdSessionRoute
  '/exam/$id/session': typeof appExamIdSessionRoute
  '/tutor/$app/$id/appeal': typeof TutorAppIdAppealRoute
  '/tutor/assignment/$id/grading': typeof TutorAssignmentIdGradingRoute
  '/tutor/discussion/$id/grading': typeof TutorDiscussionIdGradingRoute
  '/tutor/exam/$id/grading': typeof TutorExamIdGradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof appAccountRouteRouteWithChildren
  '/activate': typeof authActivateRoute
  '/join': typeof authJoinRoute
  '/login': typeof authLoginRoute
  '/password-change': typeof authPasswordChangeRoute
  '/studio': typeof StudioIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/account/device': typeof appAccountDeviceRoute
  '/account/email-change': typeof appAccountEmailChangeRoute
  '/account/group': typeof appAccountGroupRoute
  '/account/link': typeof appAccountLinkRoute
  '/account/profile': typeof appAccountProfileRoute
  '/dashboard/achievement': typeof appDashboardAchievementRoute
  '/dashboard/announcement': typeof appDashboardAnnouncementRoute
  '/dashboard/catalog': typeof appDashboardCatalogRoute
  '/dashboard/goal': typeof appDashboardGoalRoute
  '/dashboard/inquiry': typeof appDashboardInquiryRoute
  '/dashboard/learning': typeof appDashboardLearningRoute
  '/dashboard/report': typeof appDashboardReportRoute
  '/dashboard/search': typeof appDashboardSearchRoute
  '/media/$id': typeof appMediaIdRoute
  '/survey/$id': typeof publicSurveyIdRoute
  '/studio/$app/$id': typeof StudioAppIdRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/assignment/$id/session': typeof appAssignmentIdSessionRoute
  '/course/$id/session': typeof appCourseIdSessionRoute
  '/discussion/$id/session': typeof appDiscussionIdSessionRoute
  '/exam/$id/session': typeof appExamIdSessionRoute
  '/tutor/$app/$id/appeal': typeof TutorAppIdAppealRoute
  '/tutor/assignment/$id/grading': typeof TutorAssignmentIdGradingRoute
  '/tutor/discussion/$id/grading': typeof TutorDiscussionIdGradingRoute
  '/tutor/exam/$id/grading': typeof TutorExamIdGradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/(app)/account': typeof appAccountRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(auth)/activate': typeof authActivateRoute
  '/(auth)/join': typeof authJoinRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/password-change': typeof authPasswordChangeRoute
  '/studio/': typeof StudioIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/(app)/account/device': typeof appAccountDeviceRoute
  '/(app)/account/email-change': typeof appAccountEmailChangeRoute
  '/(app)/account/group': typeof appAccountGroupRoute
  '/(app)/account/link': typeof appAccountLinkRoute
  '/(app)/account/profile': typeof appAccountProfileRoute
  '/(app)/dashboard/achievement': typeof appDashboardAchievementRoute
  '/(app)/dashboard/announcement': typeof appDashboardAnnouncementRoute
  '/(app)/dashboard/catalog': typeof appDashboardCatalogRoute
  '/(app)/dashboard/goal': typeof appDashboardGoalRoute
  '/(app)/dashboard/inquiry': typeof appDashboardInquiryRoute
  '/(app)/dashboard/learning': typeof appDashboardLearningRoute
  '/(app)/dashboard/report': typeof appDashboardReportRoute
  '/(app)/dashboard/search': typeof appDashboardSearchRoute
  '/(app)/media/$id': typeof appMediaIdRoute
  '/(public)/survey/$id': typeof publicSurveyIdRoute
  '/studio/$app/$id': typeof StudioAppIdRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/assignment/$id/session': typeof appAssignmentIdSessionRoute
  '/(app)/course/$id/session': typeof appCourseIdSessionRoute
  '/(app)/discussion/$id/session': typeof appDiscussionIdSessionRoute
  '/(app)/exam/$id/session': typeof appExamIdSessionRoute
  '/tutor/$app/$id/appeal': typeof TutorAppIdAppealRoute
  '/tutor/assignment/$id/grading': typeof TutorAssignmentIdGradingRoute
  '/tutor/discussion/$id/grading': typeof TutorDiscussionIdGradingRoute
  '/tutor/exam/$id/grading': typeof TutorExamIdGradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/tutor'
    | '/account'
    | '/dashboard'
    | '/activate'
    | '/join'
    | '/login'
    | '/password-change'
    | '/studio/'
    | '/tutor/'
    | '/account/device'
    | '/account/email-change'
    | '/account/group'
    | '/account/link'
    | '/account/profile'
    | '/dashboard/achievement'
    | '/dashboard/announcement'
    | '/dashboard/catalog'
    | '/dashboard/goal'
    | '/dashboard/inquiry'
    | '/dashboard/learning'
    | '/dashboard/report'
    | '/dashboard/search'
    | '/media/$id'
    | '/survey/$id'
    | '/studio/$app/$id'
    | '/dashboard/'
    | '/assignment/$id/session'
    | '/course/$id/session'
    | '/discussion/$id/session'
    | '/exam/$id/session'
    | '/tutor/$app/$id/appeal'
    | '/tutor/assignment/$id/grading'
    | '/tutor/discussion/$id/grading'
    | '/tutor/exam/$id/grading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activate'
    | '/join'
    | '/login'
    | '/password-change'
    | '/studio'
    | '/tutor'
    | '/account/device'
    | '/account/email-change'
    | '/account/group'
    | '/account/link'
    | '/account/profile'
    | '/dashboard/achievement'
    | '/dashboard/announcement'
    | '/dashboard/catalog'
    | '/dashboard/goal'
    | '/dashboard/inquiry'
    | '/dashboard/learning'
    | '/dashboard/report'
    | '/dashboard/search'
    | '/media/$id'
    | '/survey/$id'
    | '/studio/$app/$id'
    | '/dashboard'
    | '/assignment/$id/session'
    | '/course/$id/session'
    | '/discussion/$id/session'
    | '/exam/$id/session'
    | '/tutor/$app/$id/appeal'
    | '/tutor/assignment/$id/grading'
    | '/tutor/discussion/$id/grading'
    | '/tutor/exam/$id/grading'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/studio'
    | '/tutor'
    | '/(app)/account'
    | '/(app)/dashboard'
    | '/(auth)/activate'
    | '/(auth)/join'
    | '/(auth)/login'
    | '/(auth)/password-change'
    | '/studio/'
    | '/tutor/'
    | '/(app)/account/device'
    | '/(app)/account/email-change'
    | '/(app)/account/group'
    | '/(app)/account/link'
    | '/(app)/account/profile'
    | '/(app)/dashboard/achievement'
    | '/(app)/dashboard/announcement'
    | '/(app)/dashboard/catalog'
    | '/(app)/dashboard/goal'
    | '/(app)/dashboard/inquiry'
    | '/(app)/dashboard/learning'
    | '/(app)/dashboard/report'
    | '/(app)/dashboard/search'
    | '/(app)/media/$id'
    | '/(public)/survey/$id'
    | '/studio/$app/$id'
    | '/(app)/dashboard/'
    | '/(app)/assignment/$id/session'
    | '/(app)/course/$id/session'
    | '/(app)/discussion/$id/session'
    | '/(app)/exam/$id/session'
    | '/tutor/$app/$id/appeal'
    | '/tutor/assignment/$id/grading'
    | '/tutor/discussion/$id/grading'
    | '/tutor/exam/$id/grading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  TutorRouteRoute: typeof TutorRouteRouteWithChildren
  publicSurveyIdRoute: typeof publicSurveyIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/(auth)/password-change': {
      id: '/(auth)/password-change'
      path: '/password-change'
      fullPath: '/password-change'
      preLoaderRoute: typeof authPasswordChangeRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/join': {
      id: '/(auth)/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof authJoinRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/activate': {
      id: '/(auth)/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof authActivateRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/account': {
      id: '/(app)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appAccountRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/studio/$app/$id': {
      id: '/studio/$app/$id'
      path: '/$app/$id'
      fullPath: '/studio/$app/$id'
      preLoaderRoute: typeof StudioAppIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/(public)/survey/$id': {
      id: '/(public)/survey/$id'
      path: '/survey/$id'
      fullPath: '/survey/$id'
      preLoaderRoute: typeof publicSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/media/$id': {
      id: '/(app)/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof appMediaIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/search': {
      id: '/(app)/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof appDashboardSearchRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/report': {
      id: '/(app)/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof appDashboardReportRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/learning': {
      id: '/(app)/dashboard/learning'
      path: '/learning'
      fullPath: '/dashboard/learning'
      preLoaderRoute: typeof appDashboardLearningRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/inquiry': {
      id: '/(app)/dashboard/inquiry'
      path: '/inquiry'
      fullPath: '/dashboard/inquiry'
      preLoaderRoute: typeof appDashboardInquiryRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/goal': {
      id: '/(app)/dashboard/goal'
      path: '/goal'
      fullPath: '/dashboard/goal'
      preLoaderRoute: typeof appDashboardGoalRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/catalog': {
      id: '/(app)/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof appDashboardCatalogRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/announcement': {
      id: '/(app)/dashboard/announcement'
      path: '/announcement'
      fullPath: '/dashboard/announcement'
      preLoaderRoute: typeof appDashboardAnnouncementRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/achievement': {
      id: '/(app)/dashboard/achievement'
      path: '/achievement'
      fullPath: '/dashboard/achievement'
      preLoaderRoute: typeof appDashboardAchievementRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/account/profile': {
      id: '/(app)/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof appAccountProfileRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
    '/(app)/account/link': {
      id: '/(app)/account/link'
      path: '/link'
      fullPath: '/account/link'
      preLoaderRoute: typeof appAccountLinkRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
    '/(app)/account/group': {
      id: '/(app)/account/group'
      path: '/group'
      fullPath: '/account/group'
      preLoaderRoute: typeof appAccountGroupRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
    '/(app)/account/email-change': {
      id: '/(app)/account/email-change'
      path: '/email-change'
      fullPath: '/account/email-change'
      preLoaderRoute: typeof appAccountEmailChangeRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
    '/(app)/account/device': {
      id: '/(app)/account/device'
      path: '/device'
      fullPath: '/account/device'
      preLoaderRoute: typeof appAccountDeviceRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
    '/tutor/exam/$id/grading': {
      id: '/tutor/exam/$id/grading'
      path: '/exam/$id/grading'
      fullPath: '/tutor/exam/$id/grading'
      preLoaderRoute: typeof TutorExamIdGradingRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/discussion/$id/grading': {
      id: '/tutor/discussion/$id/grading'
      path: '/discussion/$id/grading'
      fullPath: '/tutor/discussion/$id/grading'
      preLoaderRoute: typeof TutorDiscussionIdGradingRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/assignment/$id/grading': {
      id: '/tutor/assignment/$id/grading'
      path: '/assignment/$id/grading'
      fullPath: '/tutor/assignment/$id/grading'
      preLoaderRoute: typeof TutorAssignmentIdGradingRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/$app/$id/appeal': {
      id: '/tutor/$app/$id/appeal'
      path: '/$app/$id/appeal'
      fullPath: '/tutor/$app/$id/appeal'
      preLoaderRoute: typeof TutorAppIdAppealRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/(app)/exam/$id/session': {
      id: '/(app)/exam/$id/session'
      path: '/exam/$id/session'
      fullPath: '/exam/$id/session'
      preLoaderRoute: typeof appExamIdSessionRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/discussion/$id/session': {
      id: '/(app)/discussion/$id/session'
      path: '/discussion/$id/session'
      fullPath: '/discussion/$id/session'
      preLoaderRoute: typeof appDiscussionIdSessionRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/course/$id/session': {
      id: '/(app)/course/$id/session'
      path: '/course/$id/session'
      fullPath: '/course/$id/session'
      preLoaderRoute: typeof appCourseIdSessionRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/assignment/$id/session': {
      id: '/(app)/assignment/$id/session'
      path: '/assignment/$id/session'
      fullPath: '/assignment/$id/session'
      preLoaderRoute: typeof appAssignmentIdSessionRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appAccountRouteRouteChildren {
  appAccountDeviceRoute: typeof appAccountDeviceRoute
  appAccountEmailChangeRoute: typeof appAccountEmailChangeRoute
  appAccountGroupRoute: typeof appAccountGroupRoute
  appAccountLinkRoute: typeof appAccountLinkRoute
  appAccountProfileRoute: typeof appAccountProfileRoute
}

const appAccountRouteRouteChildren: appAccountRouteRouteChildren = {
  appAccountDeviceRoute: appAccountDeviceRoute,
  appAccountEmailChangeRoute: appAccountEmailChangeRoute,
  appAccountGroupRoute: appAccountGroupRoute,
  appAccountLinkRoute: appAccountLinkRoute,
  appAccountProfileRoute: appAccountProfileRoute,
}

const appAccountRouteRouteWithChildren = appAccountRouteRoute._addFileChildren(
  appAccountRouteRouteChildren,
)

interface appDashboardRouteRouteChildren {
  appDashboardAchievementRoute: typeof appDashboardAchievementRoute
  appDashboardAnnouncementRoute: typeof appDashboardAnnouncementRoute
  appDashboardCatalogRoute: typeof appDashboardCatalogRoute
  appDashboardGoalRoute: typeof appDashboardGoalRoute
  appDashboardInquiryRoute: typeof appDashboardInquiryRoute
  appDashboardLearningRoute: typeof appDashboardLearningRoute
  appDashboardReportRoute: typeof appDashboardReportRoute
  appDashboardSearchRoute: typeof appDashboardSearchRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardAchievementRoute: appDashboardAchievementRoute,
  appDashboardAnnouncementRoute: appDashboardAnnouncementRoute,
  appDashboardCatalogRoute: appDashboardCatalogRoute,
  appDashboardGoalRoute: appDashboardGoalRoute,
  appDashboardInquiryRoute: appDashboardInquiryRoute,
  appDashboardLearningRoute: appDashboardLearningRoute,
  appDashboardReportRoute: appDashboardReportRoute,
  appDashboardSearchRoute: appDashboardSearchRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

interface appRouteRouteChildren {
  appAccountRouteRoute: typeof appAccountRouteRouteWithChildren
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
  appMediaIdRoute: typeof appMediaIdRoute
  appAssignmentIdSessionRoute: typeof appAssignmentIdSessionRoute
  appCourseIdSessionRoute: typeof appCourseIdSessionRoute
  appDiscussionIdSessionRoute: typeof appDiscussionIdSessionRoute
  appExamIdSessionRoute: typeof appExamIdSessionRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAccountRouteRoute: appAccountRouteRouteWithChildren,
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
  appMediaIdRoute: appMediaIdRoute,
  appAssignmentIdSessionRoute: appAssignmentIdSessionRoute,
  appCourseIdSessionRoute: appCourseIdSessionRoute,
  appDiscussionIdSessionRoute: appDiscussionIdSessionRoute,
  appExamIdSessionRoute: appExamIdSessionRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authActivateRoute: typeof authActivateRoute
  authJoinRoute: typeof authJoinRoute
  authLoginRoute: typeof authLoginRoute
  authPasswordChangeRoute: typeof authPasswordChangeRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authActivateRoute: authActivateRoute,
  authJoinRoute: authJoinRoute,
  authLoginRoute: authLoginRoute,
  authPasswordChangeRoute: authPasswordChangeRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioAppIdRoute: typeof StudioAppIdRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioAppIdRoute: StudioAppIdRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface TutorRouteRouteChildren {
  TutorIndexRoute: typeof TutorIndexRoute
  TutorAppIdAppealRoute: typeof TutorAppIdAppealRoute
  TutorAssignmentIdGradingRoute: typeof TutorAssignmentIdGradingRoute
  TutorDiscussionIdGradingRoute: typeof TutorDiscussionIdGradingRoute
  TutorExamIdGradingRoute: typeof TutorExamIdGradingRoute
}

const TutorRouteRouteChildren: TutorRouteRouteChildren = {
  TutorIndexRoute: TutorIndexRoute,
  TutorAppIdAppealRoute: TutorAppIdAppealRoute,
  TutorAssignmentIdGradingRoute: TutorAssignmentIdGradingRoute,
  TutorDiscussionIdGradingRoute: TutorDiscussionIdGradingRoute,
  TutorExamIdGradingRoute: TutorExamIdGradingRoute,
}

const TutorRouteRouteWithChildren = TutorRouteRoute._addFileChildren(
  TutorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  TutorRouteRoute: TutorRouteRouteWithChildren,
  publicSurveyIdRoute: publicSurveyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
