# Generated by Django 6.0.1 on 2026-01-11 01:20

import apps.common.models
import apps.common.util
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), verbose_name='Options')),
                ('point', models.PositiveSmallIntegerField(default=1, verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('questions', models.ManyToManyField(to='quiz.question', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.attempt', verbose_name='Attempt')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('select_count', models.PositiveSmallIntegerField(verbose_name='Select Count')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('question', models.TextField(verbose_name='Question')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), verbose_name='Options')),
                ('point', models.PositiveSmallIntegerField(default=1, verbose_name='Point')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.question')),
                ('pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='QuestionPoolEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('select_count', models.PositiveSmallIntegerField(verbose_name='Select Count')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.questionpool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('question_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('started', models.DateTimeField(verbose_name='Attempt Start')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.attempt')),
                ('quiz', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.quiz')),
                ('question_pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Correct Answers')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='SolutionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='Correct Answers')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.solution')),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='quiz.attempt', verbose_name='Attempt')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='quiz.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='0934dc0c13ab1a781325b810bfa74ef76b5c2fe3', operation='INSERT', pgid='pgtrigger_insert_insert_3900b', table='quiz_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."completed" IS DISTINCT FROM (NEW."completed") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."earned_details" IS DISTINCT FROM (NEW."earned_details") OR OLD."earned_point" IS DISTINCT FROM (NEW."earned_point") OR OLD."feedback" IS DISTINCT FROM (NEW."feedback") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."possible_point" IS DISTINCT FROM (NEW."possible_point") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "quiz_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='115283de5fe77ac3b6dd2e1e5744757acdbd796d', operation='UPDATE', pgid='pgtrigger_update_update_198ac', table='quiz_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (OLD."attempt_id", OLD."completed", OLD."confirmed", OLD."created", OLD."earned_details", OLD."earned_point", OLD."feedback", OLD."id", OLD."modified", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."possible_point", OLD."score"); RETURN NULL;', hash='ef648511e209002b0403587da5342a813b6c27d5', operation='DELETE', pgid='pgtrigger_delete_delete_af3e7', table='quiz_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='ddbf94dc634fb3ee28b21346f7fd8407a3c64ae5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_264b7', table='quiz_gradeevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='quiz_questionpool_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "select_count", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."select_count", NEW."title"); RETURN NULL;', hash='74f72957f9d51b7a3eb6ce343f3e084075fb4a00', operation='INSERT', pgid='pgtrigger_insert_insert_b8017', table='quiz_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "quiz_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "select_count", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."select_count", NEW."title"); RETURN NULL;', hash='e36ecefe007a9f11fa72692589d8985737d5c82f', operation='UPDATE', pgid='pgtrigger_update_update_cefde', table='quiz_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "select_count", "title") VALUES (OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."select_count", OLD."title"); RETURN NULL;', hash='ea0f9ac43c43fba1a68fbe52f5905fe31819eb03', operation='DELETE', pgid='pgtrigger_delete_delete_0a09e', table='quiz_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d2a8afdce447fa1a646d7b0a5d170a9db0d502c0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3260a', table='quiz_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_questionevent" ("id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (NEW."id", NEW."options", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='e55e19e2bbb644ff5a88e7a316bba26d2b118fef', operation='INSERT', pgid='pgtrigger_insert_insert_d850e', table='quiz_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "quiz_questionevent" ("id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (NEW."id", NEW."options", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point", NEW."pool_id", NEW."question", NEW."supplement"); RETURN NULL;', hash='c352dc5af349efb069fb6672c422d95ba14a59cd', operation='UPDATE', pgid='pgtrigger_update_update_03322', table='quiz_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_questionevent" ("id", "options", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point", "pool_id", "question", "supplement") VALUES (OLD."id", OLD."options", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point", OLD."pool_id", OLD."question", OLD."supplement"); RETURN NULL;', hash='1c5c01463aef78c801deec11ea6e378694df00dd', operation='DELETE', pgid='pgtrigger_delete_delete_99f99', table='quiz_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpoolevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e6016099629139cc40c88b67e13f6861ce2988c5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3f662', table='quiz_questionpoolevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='quiz_quiz_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='e1abb8363684986fd0f9709e30efb82a1fb7c3ef', operation='INSERT', pgid='pgtrigger_insert_insert_433ea', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='d5cd748c9f8c3af9c6f9b4bab91b646ffbdfa00b', operation='UPDATE', pgid='pgtrigger_update_update_44448', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='d6ad87bf29cff4a1441c2118693294ec1382f6fa', operation='DELETE', pgid='pgtrigger_delete_delete_56331', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attemptevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='46b71f28dc79400b8e012405b9acdf915242c99b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d2a70', table='quiz_attemptevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('quiz', 'learner', 'context'), name='quiz_attemp_qu_le_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "started") VALUES (NEW."active", NEW."context", NEW."created", NEW."id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quiz_id", NEW."started"); RETURN NULL;', hash='ebea86a9a3557498cf22c1dbde1ccf105613f5a0', operation='INSERT', pgid='pgtrigger_insert_insert_db65b', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."learner_id" IS DISTINCT FROM (NEW."learner_id") OR OLD."quiz_id" IS DISTINCT FROM (NEW."quiz_id") OR OLD."started" IS DISTINCT FROM (NEW."started"))', func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "started") VALUES (NEW."active", NEW."context", NEW."created", NEW."id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quiz_id", NEW."started"); RETURN NULL;', hash='817b7ce74c137587e10955a1e7904f09a779d976', operation='UPDATE', pgid='pgtrigger_update_update_7b6c0', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "started") VALUES (OLD."active", OLD."context", OLD."created", OLD."id", OLD."learner_id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quiz_id", OLD."started"); RETURN NULL;', hash='1e63a3722a545b88eb4328fb132bea22ea36a0f4', operation='DELETE', pgid='pgtrigger_delete_delete_12426', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quizevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='1374cc8d78e9fc2d07e4b631e63d9b057315203e', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_5a122', table='quiz_quizevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_solutionevent" ("correct_answers", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id") VALUES (NEW."correct_answers", NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id"); RETURN NULL;', hash='1df3cba73b372a56c059aa788473abcd8f2a913f', operation='INSERT', pgid='pgtrigger_insert_insert_78a02', table='quiz_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "quiz_solutionevent" ("correct_answers", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id") VALUES (NEW."correct_answers", NEW."explanation", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id"); RETURN NULL;', hash='379f09cb2bb958289903fc76145389cfa9d4a775', operation='UPDATE', pgid='pgtrigger_update_update_b2490', table='quiz_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_solutionevent" ("correct_answers", "explanation", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id") VALUES (OLD."correct_answers", OLD."explanation", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id"); RETURN NULL;', hash='9f46a5aa6770aa1db7a821d608d14eba76bc8465', operation='DELETE', pgid='pgtrigger_delete_delete_025f2', table='quiz_solution', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='solutionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6ac850c9f01feb3bb1c5108283ce425edd693e6a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4b56e', table='quiz_solutionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='49502b69a82a2b155cf1cb291aa3e84491f8f64d', operation='INSERT', pgid='pgtrigger_insert_insert_bad20', table='quiz_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."answers" IS DISTINCT FROM (NEW."answers") OR OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "quiz_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answers", NEW."attempt_id", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='80efe0d358d4d15f8a34d51435e8db5435d43392', operation='UPDATE', pgid='pgtrigger_update_update_16b62', table='quiz_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_submissionevent" ("answers", "attempt_id", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."answers", OLD."attempt_id", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='509d77feacf43a452319d24a1035ab4281b2696f', operation='DELETE', pgid='pgtrigger_delete_delete_54c5d', table='quiz_submission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='submissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cf9f36b719d056d4fb5b680da6042f9a55d1a1c1', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_af252', table='quiz_submissionevent', when='BEFORE')),
        ),
    ]
