# Generated by Django 6.0.1 on 2026-01-19 12:32

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."created", NEW."id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quiz_id", NEW."retry", NEW."started"); RETURN NULL;', hash='ed7193492733d2da673eae5cda7b11d02b8b4339', operation='INSERT', pgid='pgtrigger_insert_insert_db65b', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."context" IS DISTINCT FROM (NEW."context") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."learner_id" IS DISTINCT FROM (NEW."learner_id") OR OLD."quiz_id" IS DISTINCT FROM (NEW."quiz_id") OR OLD."retry" IS DISTINCT FROM (NEW."retry") OR OLD."started" IS DISTINCT FROM (NEW."started"))', func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."created", NEW."id", NEW."learner_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quiz_id", NEW."retry", NEW."started"); RETURN NULL;', hash='3773ca61b77e712a33d6b977767467aac404db71', operation='UPDATE', pgid='pgtrigger_update_update_7b6c0', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "created", "id", "learner_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (OLD."active", OLD."context", OLD."created", OLD."id", OLD."learner_id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quiz_id", OLD."retry", OLD."started"); RETURN NULL;', hash='75564a83440571fb473e36dc451b6b9d6a15d2b9', operation='DELETE', pgid='pgtrigger_delete_delete_12426', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='quiz_attempt_retry_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                SELECT COALESCE(MAX(retry), -1) + 1\n                INTO NEW.retry\n                FROM quiz_attempt\n                WHERE quiz_id = NEW.quiz_id \n                  AND learner_id = NEW.learner_id \n                  AND context = NEW.context;\n                RETURN NEW;\n            END;\n        ', hash='a6cd812c16db1c935379927b47de0e0693af6457', operation='INSERT', pgid='pgtrigger_quiz_attempt_retry_count_6f046', table='quiz_attempt', when='BEFORE')),
        ),
    ]
