# Generated by Django 6.0.2 on 2026-02-25 05:23

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='attemptevent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attemptevent',
            name='modified',
        ),
        migrations.AddField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='mode',
            field=models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='quizevent',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='attemptevent',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quiz_id", NEW."retry", NEW."started"); RETURN NULL;', hash='975c7ce3d64d1ccb276250e020528303986cebc6', operation='INSERT', pgid='pgtrigger_insert_insert_db65b', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "quiz_attemptevent" ("active", "context", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quiz_id", NEW."retry", NEW."started"); RETURN NULL;', hash='47bc85779a76d44d2ac5cda8b1946b46c03841b4', operation='UPDATE', pgid='pgtrigger_update_update_7b6c0', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_attemptevent" ("active", "context", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quiz_id", "retry", "started") VALUES (OLD."active", OLD."context", OLD."id", OLD."learner_id", OLD."mode", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quiz_id", OLD."retry", OLD."started"); RETURN NULL;', hash='68622659dc0eba5b20e531b8cac252759a3c68fa', operation='DELETE', pgid='pgtrigger_delete_delete_12426', table='quiz_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='2b8c28133d8d66edbcfea1937024e91f237d610a', operation='INSERT', pgid='pgtrigger_insert_insert_433ea', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='ec946ee67a9903dff656301a748f8a0d542ef595', operation='UPDATE', pgid='pgtrigger_update_update_44448', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='169f80cc2078c6339c393b401074367fc4ec4cb3', operation='DELETE', pgid='pgtrigger_delete_delete_56331', table='quiz_quiz', when='AFTER')),
        ),
    ]
