# Generated by Django 6.0.2 on 2026-03-03 12:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_insert_insert_remove_quiz_update_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='quiz',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='quizevent',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='2b8c28133d8d66edbcfea1937024e91f237d610a', operation='INSERT', pgid='pgtrigger_insert_insert_433ea', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."audience", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='ec946ee67a9903dff656301a748f8a0d542ef595', operation='UPDATE', pgid='pgtrigger_update_update_44448', table='quiz_quiz', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='quiz',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "quiz_quizevent" ("audience", "created", "description", "duration", "featured", "format", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."audience", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='169f80cc2078c6339c393b401074367fc4ec4cb3', operation='DELETE', pgid='pgtrigger_delete_delete_56331', table='quiz_quiz', when='AFTER')),
        ),
    ]
