# Generated by Django 6.0.1 on 2026-01-11 01:22

import apps.common.models
import apps.common.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, null=True, storage=apps.common.storage.AvatarStorage(access_key='minima', bucket_name='minima', endpoint_url='http://localhost:9000', location='avatar', querystring_expire=86400, secret_key='minima.dev'), upload_to='', verbose_name='Avatar')),
                ('kind', models.CharField(choices=[('assistant', 'Assistant'), ('curator', 'Curator')], default='assistant', max_length=50, verbose_name='Plugin')),
                ('system_instruction', models.TextField(blank=True, default='', verbose_name='System Instruction')),
            ],
            options={
                'verbose_name': 'Assistant Bot',
                'verbose_name_plural': 'Assistant Bots',
            },
        ),
        migrations.CreateModel(
            name='AssistantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Assistant Note',
                'verbose_name_plural': 'Assistant Notes',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Deleted')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('message_count', models.PositiveSmallIntegerField(default=0, verbose_name='Message Count')),
                ('last_message', models.DateTimeField(blank=True, null=True, verbose_name='Last Message')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.assistantbot', verbose_name='Bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('deleted', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Deleted')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('response', models.TextField(blank=True, default='', verbose_name='Response')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('completed', apps.common.models.BooleanNowField(blank=True, null=True, verbose_name='Completed')),
                ('bookmarked', models.BooleanField(default=False, verbose_name='Bookmarked')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Input Tokens')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Output Tokens')),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.chat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chat',
            trigger=pgtrigger.compiler.Trigger(name='assistant_chat_ensure_single_active', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                IF NEW.active = TRUE AND NEW.deleted IS NULL THEN\n                    UPDATE assistant_chat\n                    SET active = FALSE\n                    WHERE user_id = NEW.user_id AND id != NEW.id AND active = TRUE AND deleted IS NULL;\n                END IF;\n                RETURN NEW;\n            END;\n        ', hash='192f2ff3782ec8349b92518a2392c6ad9a858524', operation='INSERT OR UPDATE', pgid='pgtrigger_assistant_chat_ensure_single_active_7df50', table='assistant_chat', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chatmessage',
            trigger=pgtrigger.compiler.Trigger(name='assistant_chatmessage_insert_message_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                BEGIN\n                    IF NEW.deleted IS NULL THEN\n                        UPDATE assistant_chat\n                        SET message_count = message_count + 1,\n                            last_message = NEW.created\n                        WHERE id = NEW.chat_id;\n                    END IF;\n                    RETURN NEW;\n                END;\n            ', hash='8ce01e073888e4d3e4e7c2731a29c353c66cd51a', operation='INSERT', pgid='pgtrigger_assistant_chatmessage_insert_message_count_79efc', table='assistant_chatmessage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chatmessage',
            trigger=pgtrigger.compiler.Trigger(name='assistant_chatmessage_update_message_count', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                BEGIN\n                    IF NEW.chat_id != OLD.chat_id THEN\n                        RAISE EXCEPTION 'Cannot change chat_id of a message';\n                    END IF;\n\n                    IF OLD.deleted IS NULL AND NEW.deleted IS NOT NULL THEN\n                        UPDATE assistant_chat\n                        SET message_count = GREATEST(message_count - 1, 0),\n                            last_message = (\n                                SELECT MAX(created)\n                                FROM assistant_chatmessage\n                                WHERE chat_id = NEW.chat_id AND deleted IS NULL\n                            )\n                        WHERE id = NEW.chat_id;\n                    END IF;\n\n                    IF OLD.deleted IS NOT NULL AND NEW.deleted IS NULL THEN\n                        UPDATE assistant_chat\n                        SET message_count = message_count + 1,\n                            last_message = GREATEST(COALESCE(last_message, NEW.created), NEW.created)\n                        WHERE id = NEW.chat_id;\n                    END IF;\n\n                    RETURN NEW;\n                END;\n            ", hash='e418ccc92708ae8f492be7ee95dd8c6494a1a37e', operation='UPDATE', pgid='pgtrigger_assistant_chatmessage_update_message_count_1a1ab', table='assistant_chatmessage', when='AFTER')),
        ),
    ]
