# Generated by Django 6.0.1 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted'),
        ),
    ]
