# Generated by Django 6.0.1 on 2026-02-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_chat_deleted_alter_chatmessage_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='url',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Path'),
        ),
    ]
