# Generated by Django 6.0.2 on 2026-03-02 17:13

import apps.common.util
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('honor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('mode', models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], db_index=True, default='', max_length=30, verbose_name='Mode')),
                ('retry', models.PositiveSmallIntegerField(default=0, verbose_name='Retry')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussion', verbose_name='Discussion')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discussion.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('earned_details', models.JSONField(verbose_name='Earned Details')),
                ('possible_point', models.PositiveSmallIntegerField(verbose_name='Possible Point')),
                ('earned_point', models.PositiveSmallIntegerField(verbose_name='Earned Point')),
                ('score', models.FloatField(verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Completed')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.attempt', verbose_name='Attempt')),
                ('grader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Grader')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='discussion.attempt', verbose_name='Attempt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discussion.post', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('attempt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.attempt', verbose_name='Attempt')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.post', verbose_name='Parent')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive', models.TextField(verbose_name='Directive')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('post_point', models.PositiveSmallIntegerField(default=1, verbose_name='Post Point')),
                ('reply_point', models.PositiveSmallIntegerField(default=1, verbose_name='Reply Point')),
                ('tutor_assessment_point', models.PositiveSmallIntegerField(default=1, verbose_name='Tutor Assessment Point')),
                ('post_min_characters', models.PositiveSmallIntegerField(default=200, verbose_name='Post Min Characters')),
                ('reply_min_characters', models.PositiveSmallIntegerField(default=100, verbose_name='Reply Min Characters')),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='operation.attachment', verbose_name='Attachments')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='Context Key')),
                ('mode', models.CharField(choices=[('', ''), ('preview', 'Preview'), ('audit', 'Audit')], default='', max_length=30, verbose_name='Mode')),
                ('retry', models.PositiveSmallIntegerField(default=0, verbose_name='Retry')),
                ('learner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.attempt')),
                ('discussion', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.discussion', verbose_name='Discussion')),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.question', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.question', verbose_name='Question'),
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('directive', models.TextField(verbose_name='Directive')),
                ('supplement', models.TextField(blank=True, default='', verbose_name='Supplement')),
                ('post_point', models.PositiveSmallIntegerField(default=1, verbose_name='Post Point')),
                ('reply_point', models.PositiveSmallIntegerField(default=1, verbose_name='Reply Point')),
                ('tutor_assessment_point', models.PositiveSmallIntegerField(default=1, verbose_name='Tutor Assessment Point')),
                ('post_min_characters', models.PositiveSmallIntegerField(default=200, verbose_name='Post Min Characters')),
                ('reply_min_characters', models.PositiveSmallIntegerField(default=100, verbose_name='Reply Min Characters')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.question')),
                ('pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discussion.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='DiscussionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(default=apps.common.util.tuid, editable=False, max_length=12, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('audience', models.TextField(blank=True, default='', verbose_name='Audience')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('format', models.CharField(blank=True, default='', max_length=30, verbose_name='Format')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('passing_point', models.PositiveSmallIntegerField(default=60, verbose_name='Passing Point')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Max Attempts')),
                ('verification_required', models.BooleanField(default=False, verbose_name='Verification Required')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('grade_due_days', models.PositiveSmallIntegerField(verbose_name='Grading Due Days')),
                ('appeal_deadline_days', models.PositiveSmallIntegerField(verbose_name='Appeal Deadline Days')),
                ('confirm_due_days', models.PositiveSmallIntegerField(verbose_name='Confirm Due Days')),
                ('honor_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='operation.honorcode', verbose_name='Honor Code')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.discussion')),
                ('question_pool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='discussion.questionpool', verbose_name='Question Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='question_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.questionpool', verbose_name='Question Pool'),
        ),
        migrations.CreateModel(
            name='QuestionPoolEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discussion.questionpool')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='5a5cec10fa42054ec8cb99b9800d231540515fcb', operation='INSERT', pgid='pgtrigger_insert_insert_b42fa', table='discussion_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."completed" IS DISTINCT FROM (NEW."completed") OR OLD."confirmed" IS DISTINCT FROM (NEW."confirmed") OR OLD."earned_details" IS DISTINCT FROM (NEW."earned_details") OR OLD."earned_point" IS DISTINCT FROM (NEW."earned_point") OR OLD."feedback" IS DISTINCT FROM (NEW."feedback") OR OLD."grader_id" IS DISTINCT FROM (NEW."grader_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."passed" IS DISTINCT FROM (NEW."passed") OR OLD."possible_point" IS DISTINCT FROM (NEW."possible_point") OR OLD."score" IS DISTINCT FROM (NEW."score"))', func='INSERT INTO "discussion_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (NEW."attempt_id", NEW."completed", NEW."confirmed", NEW."created", NEW."earned_details", NEW."earned_point", NEW."feedback", NEW."grader_id", NEW."id", NEW."modified", NEW."passed", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."possible_point", NEW."score"); RETURN NULL;', hash='e8d3821c80af6f15c34432db2f315ef1080290c3', operation='UPDATE', pgid='pgtrigger_update_update_12f56', table='discussion_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grade',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_gradeevent" ("attempt_id", "completed", "confirmed", "created", "earned_details", "earned_point", "feedback", "grader_id", "id", "modified", "passed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "possible_point", "score") VALUES (OLD."attempt_id", OLD."completed", OLD."confirmed", OLD."created", OLD."earned_details", OLD."earned_point", OLD."feedback", OLD."grader_id", OLD."id", OLD."modified", OLD."passed", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."possible_point", OLD."score"); RETURN NULL;', hash='e456ac8afc8529e692d72dfdbe271977defca520', operation='DELETE', pgid='pgtrigger_delete_delete_228de', table='discussion_grade', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gradeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d2b55aeaa512f62d188ee9883c21487c923dd4f1', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a5db1', table='discussion_gradeevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_postevent" ("attempt_id", "body", "created", "id", "modified", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."attempt_id", NEW."body", NEW."created", NEW."id", NEW."modified", NEW."parent_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='10bd6f1dd2d669a745ec146106bc562e6fc007e7', operation='INSERT', pgid='pgtrigger_insert_insert_915c2', table='discussion_post', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."attempt_id" IS DISTINCT FROM (NEW."attempt_id") OR OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."parent_id" IS DISTINCT FROM (NEW."parent_id") OR OLD."title" IS DISTINCT FROM (NEW."title"))', func='INSERT INTO "discussion_postevent" ("attempt_id", "body", "created", "id", "modified", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."attempt_id", NEW."body", NEW."created", NEW."id", NEW."modified", NEW."parent_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='2b803c8478bdb98dca385953fc065addf69023cd', operation='UPDATE', pgid='pgtrigger_update_update_fdd95', table='discussion_post', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_postevent" ("attempt_id", "body", "created", "id", "modified", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."attempt_id", OLD."body", OLD."created", OLD."id", OLD."modified", OLD."parent_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='cc4d75e9814d10f99772d55bc57abd32e39d1cd3', operation='DELETE', pgid='pgtrigger_delete_delete_3ebde', table='discussion_post', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='postevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='2c722f6cbc9e927c31407dd726c0bd37e45734ee', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_40fb0', table='discussion_postevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attemptevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='73ecb023433b37f1dda827c1e8c4c08a99c47ab9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3154a', table='discussion_attemptevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['learner_id', 'active'], name='discussion__learner_ef00b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('discussion', 'learner', 'context'), name='discussion_attemp_di_le_co_ke_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."discussion_id", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='0d46845e7851c82fcd70d20e8735e894f1550364', operation='INSERT', pgid='pgtrigger_insert_insert_c592d', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."discussion_id", NEW."id", NEW."learner_id", NEW."mode", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='95ef4e3333085a7128756233a7e58c4a5f7bde79', operation='UPDATE', pgid='pgtrigger_update_update_7f758', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (OLD."active", OLD."context", OLD."discussion_id", OLD."id", OLD."learner_id", OLD."mode", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."retry", OLD."started"); RETURN NULL;', hash='785dd072e5f98a9ced87e44aa6bdbde75a2c73a8', operation='DELETE', pgid='pgtrigger_delete_delete_88e52', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='discussion_attempt_retry_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                SELECT COALESCE(MAX(retry), -1) + 1\n                INTO NEW.retry\n                FROM discussion_attempt\n                WHERE discussion_id = NEW.discussion_id \n                  AND learner_id = NEW.learner_id \n                  AND context = NEW.context;\n                RETURN NEW;\n            END;\n        ', hash='9cc50cfad036a231ad5e243ef2788c52258e5fbe', operation='INSERT', pgid='pgtrigger_discussion_attempt_retry_count_ca6dd', table='discussion_attempt', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='discussion_questionpool_ti_ow_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='79a0b603c7fec3285353485bebca5e12dd5ee52c', operation='INSERT', pgid='pgtrigger_insert_insert_56c45', table='discussion_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "discussion_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."description", NEW."id", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='bfbebfec880aa9294f77e1f766689a584a9a83ce', operation='UPDATE', pgid='pgtrigger_update_update_0e20e', table='discussion_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpool',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_questionpoolevent" ("description", "id", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."description", OLD."id", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title"); RETURN NULL;', hash='f05abec3cbf3575384b5e8149dfb0d836978067b', operation='DELETE', pgid='pgtrigger_delete_delete_3d1a2', table='discussion_questionpool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c00deeaf42dd42237048a7bd87a83c5d01a42ffb', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_5fd8a', table='discussion_questionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_questionevent" ("directive", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "post_min_characters", "post_point", "reply_min_characters", "reply_point", "supplement", "tutor_assessment_point") VALUES (NEW."directive", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pool_id", NEW."post_min_characters", NEW."post_point", NEW."reply_min_characters", NEW."reply_point", NEW."supplement", NEW."tutor_assessment_point"); RETURN NULL;', hash='554abb6a335155cef0e8374b60b1da58adf0b99f', operation='INSERT', pgid='pgtrigger_insert_insert_50060', table='discussion_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "discussion_questionevent" ("directive", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "post_min_characters", "post_point", "reply_min_characters", "reply_point", "supplement", "tutor_assessment_point") VALUES (NEW."directive", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pool_id", NEW."post_min_characters", NEW."post_point", NEW."reply_min_characters", NEW."reply_point", NEW."supplement", NEW."tutor_assessment_point"); RETURN NULL;', hash='fbb8663ba5d3eb0a096a6c05ddd61abdd0e3133a', operation='UPDATE', pgid='pgtrigger_update_update_addb0', table='discussion_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_questionevent" ("directive", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pool_id", "post_min_characters", "post_point", "reply_min_characters", "reply_point", "supplement", "tutor_assessment_point") VALUES (OLD."directive", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pool_id", OLD."post_min_characters", OLD."post_point", OLD."reply_min_characters", OLD."reply_point", OLD."supplement", OLD."tutor_assessment_point"); RETURN NULL;', hash='f2620b2ca6e4e9f656ef3150bddd246fbf7671da', operation='DELETE', pgid='pgtrigger_delete_delete_66381', table='discussion_question', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discussionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bda8bc7d737ea1294cb4acb4b0ac6c620fb6552f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_1c33b', table='discussion_discussionevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='discussion_ow_ti_uniq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discussion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_discussionevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='2b6c62087495152dc9dbe739b3e046586395d219', operation='INSERT', pgid='pgtrigger_insert_insert_f0c80', table='discussion_discussion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discussion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appeal_deadline_days" IS DISTINCT FROM (NEW."appeal_deadline_days") OR OLD."audience" IS DISTINCT FROM (NEW."audience") OR OLD."confirm_due_days" IS DISTINCT FROM (NEW."confirm_due_days") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."featured" IS DISTINCT FROM (NEW."featured") OR OLD."format" IS DISTINCT FROM (NEW."format") OR OLD."grade_due_days" IS DISTINCT FROM (NEW."grade_due_days") OR OLD."honor_code_id" IS DISTINCT FROM (NEW."honor_code_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."passing_point" IS DISTINCT FROM (NEW."passing_point") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."question_pool_id" IS DISTINCT FROM (NEW."question_pool_id") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."verification_required" IS DISTINCT FROM (NEW."verification_required"))', func='INSERT INTO "discussion_discussionevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (NEW."appeal_deadline_days", NEW."audience", NEW."confirm_due_days", NEW."created", NEW."description", NEW."duration", NEW."featured", NEW."format", NEW."grade_due_days", NEW."honor_code_id", NEW."id", NEW."max_attempts", NEW."modified", NEW."owner_id", NEW."passing_point", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published", NEW."question_pool_id", NEW."thumbnail", NEW."title", NEW."verification_required"); RETURN NULL;', hash='fd3dba4e8c7ab982d57cc6422b147fd013acb029', operation='UPDATE', pgid='pgtrigger_update_update_a3185', table='discussion_discussion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discussion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_discussionevent" ("appeal_deadline_days", "audience", "confirm_due_days", "created", "description", "duration", "featured", "format", "grade_due_days", "honor_code_id", "id", "max_attempts", "modified", "owner_id", "passing_point", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "question_pool_id", "thumbnail", "title", "verification_required") VALUES (OLD."appeal_deadline_days", OLD."audience", OLD."confirm_due_days", OLD."created", OLD."description", OLD."duration", OLD."featured", OLD."format", OLD."grade_due_days", OLD."honor_code_id", OLD."id", OLD."max_attempts", OLD."modified", OLD."owner_id", OLD."passing_point", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."question_pool_id", OLD."thumbnail", OLD."title", OLD."verification_required"); RETURN NULL;', hash='c2cd7907ec6a057ca116329cfcf04070420a4e8a', operation='DELETE', pgid='pgtrigger_delete_delete_a1d65', table='discussion_discussion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionpoolevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8bbcf840c2736adc5bd54d5086153d9d51ca99a4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d847e', table='discussion_questionpoolevent', when='BEFORE')),
        ),
    ]
