# Generated by Django 6.0.1 on 2026-01-19 17:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attempt',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='retry',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retry'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."discussion_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='ac2f0f664051895944176f200005334efb018eab', operation='INSERT', pgid='pgtrigger_insert_insert_c592d', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (NEW."active", NEW."context", NEW."discussion_id", NEW."id", NEW."learner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."retry", NEW."started"); RETURN NULL;', hash='e2b76326b3682c0b10dcf26a45222e5cb8baeebe', operation='UPDATE', pgid='pgtrigger_update_update_7f758', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discussion_attemptevent" ("active", "context", "discussion_id", "id", "learner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "retry", "started") VALUES (OLD."active", OLD."context", OLD."discussion_id", OLD."id", OLD."learner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."question_id", OLD."retry", OLD."started"); RETURN NULL;', hash='1eed75c7bc5c2b7961872a5befa801b9ff0c7cd0', operation='DELETE', pgid='pgtrigger_delete_delete_88e52', table='discussion_attempt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attempt',
            trigger=pgtrigger.compiler.Trigger(name='discussion_attempt_retry_count', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                SELECT COALESCE(MAX(retry), -1) + 1\n                INTO NEW.retry\n                FROM discussion_attempt\n                WHERE discussion_id = NEW.discussion_id \n                  AND learner_id = NEW.learner_id \n                  AND context = NEW.context;\n                RETURN NEW;\n            END;\n        ', hash='9cc50cfad036a231ad5e243ef2788c52258e5fbe', operation='INSERT', pgid='pgtrigger_discussion_attempt_retry_count_ca6dd', table='discussion_attempt', when='BEFORE')),
        ),
    ]
